"""Native marker output is generated by model-owned FK, never q-as-marker."""

from __future__ import annotations

from dataclasses import replace
import math
from pathlib import Path

import numpy as np
import pytest

from src.engines.feedback_comparison import DriveMode, FeedbackComparisonRegistry
from src.engines.feedback_native_execution import (
    NativeAdapterBinding,
    NativeReplayRequest,
)
from src.engines.feedback_native_markers import (
    NativeMarkerAttachment,
    NativeMarkerMap,
    build_native_marker_replay_report,
    execute_native_marker_replay,
)
from src.engines.model_inventory import EngineModelInventory

pytestmark = pytest.mark.unit


@pytest.fixture()
def registry() -> FeedbackComparisonRegistry:
    root = Path(__file__).resolve().parents[3]
    return FeedbackComparisonRegistry(EngineModelInventory.load(repo_root=root))


def _registry_binding(
    registry: FeedbackComparisonRegistry,
    bundle,
    engine: str,
) -> tuple[FeedbackComparisonRegistry, NativeAdapterBinding]:
    row = registry.get(f"{engine}/driver", "default", DriveMode.TORQUE)
    row = replace(
        row,
        source_model_sha256=bundle.model.source_model_sha256,
        provider_id="synthetic-inventory-provider",
        provider_sha256="e" * 64,
        availability="available",
    )
    registry.rows = (row,)
    return registry, NativeAdapterBinding(
        row.package_id,
        row.variant_id,
        row.drive_mode,
        bundle.model.model_id,
        bundle.model.variant_id,
        bundle.model.provider_id,
        bundle.model.provider_sha256,
        bundle.model.source_model_sha256,
        bundle.model.loaded_native_model_sha256,
        bundle.state_schema_sha256,
        bundle.input_channel_schema_sha256,
        bundle.model.ordered_input_channel_ids,
    )


def _rotate_wxyz(quaternion: np.ndarray, vector: np.ndarray) -> np.ndarray:
    scalar = quaternion[0]
    axis = quaternion[1:]
    cross = 2 * np.cross(axis, vector)
    return vector + scalar * cross + np.cross(axis, cross)


def test_mujoco_markers_use_native_fk_with_floating_base_and_local_offset(
    registry: FeedbackComparisonRegistry,
    tmp_path: Path,
) -> None:
    mujoco = pytest.importorskip("mujoco")
    from src.engines.physics_engines.mujoco.python.native_torque_replay import (
        build_native_torque_bundle,
        replay_native_torque_bundle,
    )

    model_path = tmp_path / "floating_marker.xml"
    model_path.write_text(
        """<mujoco model="marker_fk">
  <option timestep="0.001" gravity="0 0 0"/>
  <worldbody><body name="root"><freejoint name="floating"/>
    <geom type="sphere" size="0.03" mass="1"/>
    <body name="arm" pos="0 0 0.3"><joint name="hinge" axis="0 0 1"/>
      <geom type="capsule" size="0.02 0.1" mass="1"/>
    </body>
  </body></worldbody>
  <actuator><motor name="motor" joint="hinge"/></actuator>
</mujoco>""",
        encoding="utf-8",
    )
    model = mujoco.MjModel.from_xml_path(str(model_path))
    data = mujoco.MjData(model)
    data.qpos[:7] = [0.2, -0.1, 0.4, math.sqrt(0.5), 0.0, 0.0, math.sqrt(0.5)]
    data.qpos[7] = 0.35
    mujoco.mj_forward(model, data)
    initial = np.empty(mujoco.mj_stateSize(model, mujoco.mjtState.mjSTATE_INTEGRATION))
    mujoco.mj_getState(model, data, initial, mujoco.mjtState.mjSTATE_INTEGRATION)
    bundle = build_native_torque_bundle(
        model_path,
        initial,
        np.asarray([0.0, 0.001, 0.002]),
        np.asarray([[0.1], [0.2], [0.2]]),
    )
    registry, binding = _registry_binding(registry, bundle, "mujoco")
    request = NativeReplayRequest(binding, bundle, model_path)
    offset = (0.2, -0.1, 0.05)
    marker_map = NativeMarkerMap(
        "mujoco",
        bundle.model.model_id,
        bundle.model.variant_id,
        bundle.model.provider_id,
        bundle.model.provider_sha256,
        bundle.model.source_model_sha256,
        bundle.model.loaded_native_model_sha256,
        "world",
        bundle.input_history.timebase_id,
        (NativeMarkerAttachment("marker-a", "arm", offset),),
    )

    evidence = execute_native_marker_replay(request, registry, marker_map)

    positions = np.asarray(evidence.native_output.positions_m)
    assert positions.shape == (3, 1, 3)
    assert evidence.qualification == "unqualified"
    assert evidence.marker_map_sha256 == marker_map.sha256
    assert evidence.native_execution_receipt.output_state_sha256
    changed_map = replace(
        marker_map,
        attachments=(
            replace(marker_map.attachments[0], local_position_m=(0.21, -0.1, 0.05)),
        ),
    )
    assert changed_map.sha256 != marker_map.sha256
    replay = replay_native_torque_bundle(bundle, model_path)
    for sample, state in enumerate(replay.qpos):
        angle = state[7]
        local = np.asarray(offset)
        hinge = np.array(
            [
                math.cos(angle) * local[0] - math.sin(angle) * local[1],
                math.sin(angle) * local[0] + math.cos(angle) * local[1],
                local[2],
            ]
        )
        local_from_root = np.array([0.0, 0.0, 0.3]) + hinge
        expected = state[:3] + _rotate_wxyz(state[3:7], local_from_root)
        np.testing.assert_allclose(positions[sample, 0], expected, atol=1e-10)


def test_marker_map_rejects_stale_loaded_model_identity(
    registry: FeedbackComparisonRegistry,
    tmp_path: Path,
) -> None:
    mujoco = pytest.importorskip("mujoco")
    from src.engines.physics_engines.mujoco.python.native_torque_replay import (
        build_native_torque_bundle,
    )

    model_path = tmp_path / "hinge.xml"
    model_path.write_text(
        """<mujoco model="marker_fk"><option timestep="0.001"/>
<worldbody><body name="arm">
 <joint name="hinge"/><geom type="capsule" size="0.02 0.1" mass="1"/>
</body></worldbody><actuator><motor name="motor" joint="hinge"/></actuator></mujoco>""",
        encoding="utf-8",
    )
    model = mujoco.MjModel.from_xml_path(str(model_path))
    data = mujoco.MjData(model)
    initial = np.empty(mujoco.mj_stateSize(model, mujoco.mjtState.mjSTATE_INTEGRATION))
    mujoco.mj_getState(model, data, initial, mujoco.mjtState.mjSTATE_INTEGRATION)
    bundle = build_native_torque_bundle(
        model_path,
        initial,
        np.asarray([0.0, 0.001, 0.002]),
        np.asarray([[0.1], [0.1], [0.1]]),
    )
    registry, binding = _registry_binding(registry, bundle, "mujoco")
    marker_map = NativeMarkerMap(
        "mujoco",
        bundle.model.model_id,
        bundle.model.variant_id,
        bundle.model.provider_id,
        bundle.model.provider_sha256,
        bundle.model.source_model_sha256,
        "f" * 64,
        "world",
        bundle.input_history.timebase_id,
        (NativeMarkerAttachment("marker-a", "arm", (0.0, 0.2, 0.0)),),
    )

    with pytest.raises(ValueError, match="model or provider identity differs"):
        execute_native_marker_replay(
            NativeReplayRequest(binding, bundle, model_path), registry, marker_map
        )

    valid_map = replace(
        marker_map, loaded_native_model_sha256=bundle.model.loaded_native_model_sha256
    )
    unknown_body = replace(
        valid_map,
        attachments=(replace(valid_map.attachments[0], frame_id="missing-body"),),
    )
    with pytest.raises(ValueError, match="unknown native marker body"):
        execute_native_marker_replay(
            NativeReplayRequest(binding, bundle, model_path), registry, unknown_body
        )


def test_marker_report_preserves_every_required_engine_without_fk_requests(
    registry: FeedbackComparisonRegistry,
) -> None:
    report = build_native_marker_replay_report(registry, ())

    assert len(report.rows) == len(registry.rows)
    assert set(report.required_engine_ids) == {
        "drake",
        "mujoco",
        "myosuite",
        "opensim",
        "pinocchio",
        "simscape",
    }
    assert report.missing_engine_ids == report.required_engine_ids
    assert not report.has_full_required_fk_coverage
    assert all(row.status == "missing_marker_map" for row in report.rows)


def test_drake_markers_use_native_fk_with_floating_base_and_local_offset(
    registry: FeedbackComparisonRegistry,
    tmp_path: Path,
) -> None:
    pytest.importorskip("pydrake.multibody.plant")
    from pydrake.math import RigidTransform
    from pydrake.multibody.parsing import Parser
    from pydrake.multibody.plant import MultibodyPlant

    from src.engines.physics_engines.drake.python.native_torque_replay import (
        build_native_drake_torque_bundle,
        replay_native_drake_torque_bundle,
    )

    urdf = """<robot name="floating_marker_fk">
  <link name="base"><inertial><mass value="2"/><inertia ixx="0.2" iyy="0.2" izz="0.2" ixy="0" ixz="0" iyz="0"/></inertial></link>
  <link name="arm"><inertial><mass value="1"/><inertia ixx="0.1" iyy="0.1" izz="0.1" ixy="0" ixz="0" iyz="0"/></inertial></link>
  <joint name="hinge" type="revolute"><parent link="base"/><child link="arm"/><axis xyz="0 0 1"/><limit lower="-3" upper="3" effort="2" velocity="100"/></joint>
  <transmission name="motor"><type>transmission_interface/SimpleTransmission</type><joint name="hinge"/><actuator name="motor"><mechanicalReduction>1</mechanicalReduction></actuator></transmission>
</robot>"""
    model_path = tmp_path / "floating_marker.urdf"
    model_path.write_text(urdf, encoding="utf-8")
    plant = MultibodyPlant(0.001)
    plant.SetUseSampledOutputPorts(False)
    Parser(plant).AddModelsFromString(urdf, "urdf")
    plant.Finalize()
    context = plant.CreateDefaultContext()
    plant.SetFreeBodyPose(
        context,
        plant.GetBodyByName("base"),
        RigidTransform(np.asarray([0.3, -0.2, 0.5])),
    )
    plant.GetJointByName("hinge").set_angle(context, 0.4)
    initial = context.get_discrete_state_vector().CopyToVector()
    bundle = build_native_drake_torque_bundle(
        model_path,
        initial,
        np.asarray([0.0, 0.001, 0.002]),
        np.zeros((3, 1)),
    )
    registry, binding = _registry_binding(registry, bundle, "drake")
    offset = np.asarray([0.2, 0.1, 0.05])
    marker_map = NativeMarkerMap(
        "drake",
        bundle.model.model_id,
        bundle.model.variant_id,
        bundle.model.provider_id,
        bundle.model.provider_sha256,
        bundle.model.source_model_sha256,
        bundle.model.loaded_native_model_sha256,
        "world",
        bundle.input_history.timebase_id,
        (NativeMarkerAttachment("marker-a", "arm", tuple(offset)),),
    )

    evidence = execute_native_marker_replay(
        NativeReplayRequest(binding, bundle, model_path), registry, marker_map
    )

    positions = np.asarray(evidence.native_output.positions_m)
    assert evidence.native_execution_receipt.nq == 8
    assert evidence.native_execution_receipt.nv == 7
    assert np.all(np.linalg.norm(positions[:, 0], axis=1) > 0)
    frame = plant.GetFrameByName("arm")
    replayed = replay_native_drake_torque_bundle(bundle, model_path)
    for sample, qpos in enumerate(replayed.qpos):
        plant.SetPositions(context, qpos)
        pose = frame.CalcPoseInWorld(context)
        expected = pose.translation() + pose.rotation().matrix() @ offset
        np.testing.assert_allclose(positions[sample, 0], expected, atol=1e-10)
