function tests = test_metrics
%TEST_METRICS Unit tests for the canonical metrics.Metrics classdef.
%   Mirrors tests/unit/motion_matching/test_metrics.py.
    tests = functiontests(localfunctions);
end

function s = good_struct(~)
    s = struct( ...
        'swing_id', "TW_ProV1", ...
        'option', 1, ...
        'solver', "fmincon-sqp", ...
        'n_iterations', 42, ...
        'rmse_clubhead_mm', 3.21, ...
        'rmse_butt_mm', 1.85, ...
        'rmse_orientation_deg', 2.4, ...
        'clubhead_speed_at_impact_mph', 112.3, ...
        'clubhead_speed_meas_mph', 113.5, ...
        'total_work_J', 310.5, ...
        'peak_power_W', 2845.0, ...
        'wall_clock_s', 17.4, ...
        'git_commit', repmat("a", 1, 40), ...
        'matlab_version', "R2024b", ...
        'python_version', "", ...
        'timestamp_iso8601', "2026-05-05T17:34:21Z", ...
        'schema_version', "1.0.0");
    s.git_commit = string(repmat('a', 1, 40));
end

function test_construct_valid(testCase)
    s = good_struct();
    m = metrics.Metrics(s);
    verifyEqual(testCase, m.option, 1);
    verifyEqual(testCase, m.schema_version, "1.0.0");
end

function test_validates_finite(testCase)
    s = good_struct();
    s.rmse_clubhead_mm = NaN;
    verifyError(testCase, @() metrics.Metrics(s), ...
        "metrics:Metrics:nonFinite");
end

function test_validates_iso8601(testCase)
    s = good_struct();
    s.timestamp_iso8601 = "not-a-timestamp";
    verifyError(testCase, @() metrics.Metrics(s), ...
        "metrics:Metrics:badTimestamp");
end

function test_validates_schema_version(testCase)
    s = good_struct();
    s.schema_version = "0.9.0";
    verifyError(testCase, @() metrics.Metrics(s), ...
        "metrics:Metrics:badSchema");
end

function test_validates_option_range(testCase)
    s = good_struct();
    s.option = 5;
    verifyError(testCase, @() metrics.Metrics(s), ...
        "metrics:Metrics:badOption");
end

function test_validates_negative_rmse(testCase)
    s = good_struct();
    s.rmse_clubhead_mm = -1.0;
    verifyError(testCase, @() metrics.Metrics(s), ...
        "metrics:Metrics:negative");
end

function test_to_json_round_trip(testCase)
    m = metrics.Metrics(good_struct());
    j = m.to_json();
    m2 = metrics.Metrics.from_json(j);
    verifyEqual(testCase, m2.swing_id, m.swing_id);
    verifyEqual(testCase, m2.option, m.option);
    verifyEqual(testCase, m2.rmse_clubhead_mm, m.rmse_clubhead_mm);
end

function test_to_csv_row_round_trip(testCase)
    m = metrics.Metrics(good_struct());
    row = m.to_csv_row();
    m2 = metrics.Metrics.from_csv_row(row);
    verifyEqual(testCase, m2.swing_id, m.swing_id);
    verifyEqual(testCase, m2.option, m.option);
    verifyEqual(testCase, m2.rmse_clubhead_mm, m.rmse_clubhead_mm, ...
        'AbsTol', 1e-10);
end

function test_legacy_struct_converted(testCase)
    legacy = struct( ...
        'swing_id', "TW_ProV1", ...
        'option', 2, ...
        'solver', "surrogate+fmincon", ...
        'rmse_clubhead', 4.2, ...
        'rmse_butt', 2.1, ...
        'rmse_orient', 3.0, ...
        'chs_impact', 110.0, ...
        'chs_meas', 111.5, ...
        'total_work', 295.0, ...
        'peak_power', 2700.0, ...
        'wall_clock', 12.3, ...
        'git_commit', string(repmat('b', 1, 40)), ...
        'timestamp', "2026-05-05T18:00:00Z");
    m = metrics.Metrics.fromLegacyStruct(legacy);
    verifyEqual(testCase, m.rmse_clubhead_mm, 4.2);
    verifyEqual(testCase, m.clubhead_speed_at_impact_mph, 110.0);
    verifyEqual(testCase, m.schema_version, "1.0.0");
end

function test_fixture_loadable(testCase)
    here = fileparts(mfilename('fullpath'));
    fixturePath = fullfile(here, '..', '..', '..', '..', '..', '..', ...
        '..', 'tests', 'motion_matching', 'shared', 'fixtures', ...
        'metrics_example.json');
    if ~isfile(fixturePath)
        % Best-effort; CI may run from a different cwd.
        return;
    end
    txt = fileread(fixturePath);
    m = metrics.Metrics.from_json(string(txt));
    verifyEqual(testCase, m.swing_id, "TW_ProV1");
    verifyEqual(testCase, m.schema_version, "1.0.0");
end
