"""Compatibility matrix tests for the motion capture pipeline.

Part of issue #4571. Generates a markdown matrix into docs/motion_pipeline/compat.md
so the supported combinations are always discoverable.
"""

from __future__ import annotations

import os
import sys
from pathlib import Path
from typing import NamedTuple

REPO_ROOT = Path(__file__).resolve().parents[3]
DOCS_DIR = REPO_ROOT / "docs" / "motion_pipeline"

# ---------------------------------------------------------------------------
# Matrix Configuration
# ---------------------------------------------------------------------------


class MatrixResult(NamedTuple):
    """Result of a compatibility matrix test."""

    source_format: str
    ik_backend: str
    matching_backend: str
    status: str  # "pass", "skip", "fail"
    reason: str


# All source formats to test
SOURCE_FORMATS = [
    "c3d",  # C3D motion capture (Vicon, Qualisys)
    "trc",  # Theia3D / Vicon Nexus TRC
    "bvh",  # BioVision Hierarchy (Move.ai, etc.)
    "openpose_json",  # OpenPose 2D keypoints
    "mediapipe_json",  # MediaPipe Pose 2D keypoints
    "fbx",  # FBX animation (Blender conversion)
]

# All IK backends
IK_BACKENDS = [
    "mujoco",  # MuJoCo inverse kinematics
    "drake",  # Drake differential IK
    "pinocchio",  # Pinocchio analytical IK
    "opensim",  # OpenSim IK (experimental)
]

# All motion matching backends
MATCHING_BACKENDS = [
    "mujoco",  # MuJoCo torque tracking
    "drake",  # Drake trajectory optimization
    "pinocchio",  # Pinocchio operational space control
]

# Known unsupported combinations with reasons
KNOWN_UNSUPPORTED = {
    ("openpose_json", "drake", "mujoco"): "2D lifting not implemented for Drake IK",
    ("mediapipe_json", "drake", "mujoco"): "2D lifting not implemented for Drake IK",
    ("fbx", "opensim", "mujoco"): "FBX loader not implemented",
    ("c3d", "opensim", "mujoco"): "OpenSim IK backend under development (#4490)",
}

# Heavy integration tests that may be skipped in CI
HEAVY_COMBINATIONS = {
    ("c3d", "drake", "drake"): "Drake trajopt is computationally expensive",
    ("trc", "drake", "drake"): "Drake trajopt is computationally expensive",
}

# ---------------------------------------------------------------------------
# Matrix Generation
# ---------------------------------------------------------------------------


def generate_compatibility_matrix() -> str:
    """Generate the compatibility matrix markdown table.

    Returns:
        Markdown string containing the compatibility matrix
    """
    lines = [
        "# Motion Pipeline — Compatibility Matrix",
        "",
        "> Auto-generated by `test_compat_matrix.py`. Do not edit manually.",
        "",
        "## Source Format × Backend Compatibility",
        "",
    ]

    # Generate matrix for each source format
    for fmt in SOURCE_FORMATS:
        lines.append(f"### {fmt.upper()}")
        lines.append("")
        lines.append("| IK Backend | Matching Backend | Status | Notes |")
        lines.append("|------------|------------------|--------|-------|")

        for ik in IK_BACKENDS:
            for mm in MATCHING_BACKENDS:
                key = (fmt, ik, mm)

                if key in KNOWN_UNSUPPORTED:
                    status = "❌ Unsupported"
                    notes = KNOWN_UNSUPPORTED[key]
                elif key in HEAVY_COMBINATIONS:
                    status = "⚠️ Heavy"
                    notes = HEAVY_COMBINATIONS[key]
                else:
                    status = "✅ Supported"
                    notes = ""

                lines.append(f"| {ik} | {mm} | {status} | {notes} |")

        lines.append("")

    # Add legend
    lines.extend(
        [
            "## Legend",
            "",
            "- ✅ Supported: Tested and working",
            "- ⚠️ Heavy: Works but computationally expensive, may be skipped in CI",
            "- ❌ Unsupported: Known incompatible combination",
            "- ⏳ Pending: Implementation in progress",
            "",
            "## Generation Command",
            "",
            "```bash",
            "# Regenerate this matrix",
            "python3 tests/integration/motion_pipeline/test_compat_matrix.py --generate",
            "```",
            "",
            "## Related Documents",
            "",
            "- [User Workflow Guide](README.md)",
            "- [Format Matrix](formats.md)",
            "- [Troubleshooting](troubleshooting.md)",
            "- [Architecture ADR](../adr/0007-motion-pipeline-architecture.md)",
        ]
    )

    return "\n".join(lines)


def generate_matrix_file() -> None:
    """Generate the compatibility matrix markdown file."""
    # Ensure docs directory exists
    DOCS_DIR.mkdir(parents=True, exist_ok=True)

    matrix_md = generate_compatibility_matrix()
    matrix_path = DOCS_DIR / "compat.md"

    # Write the matrix
    matrix_path.write_text(matrix_md, encoding="utf-8")

    print(f"Generated compatibility matrix: {matrix_path}")


# ---------------------------------------------------------------------------
# Test Functions (only defined when pytest is available)
# ---------------------------------------------------------------------------

# Check if running under pytest (but not --generate)
_args = sys.argv[1:]
if "pytest" in sys.modules or (
    any(arg.startswith("-") for arg in _args) and "--generate" not in _args
):
    import pytest

    pytestmark = [pytest.mark.integration, pytest.mark.motion_pipeline]

    def _check_backend_available(backend: str) -> tuple[bool, str]:
        """Check if a backend is available for testing."""
        try:
            if backend == "mujoco":
                import mujoco  # noqa: F401
            elif backend == "drake":
                from pydrake.all import MultibodyPlant  # noqa: F401
            elif backend == "pinocchio":
                import pinocchio  # noqa: F401
            elif backend == "opensim":
                import opensim  # noqa: F401
            else:
                return False, f"Unknown backend: {backend}"
            return True, ""
        except ImportError as e:
            return False, f"Backend not installed: {e}"

    def _check_source_format_available(fmt: str) -> tuple[bool, str]:
        """Check if a source format loader is available."""
        try:
            if fmt == "c3d":
                import c3d  # noqa: F401
            elif fmt == "trc":
                pass  # TRC is CSV-based, always available
            elif fmt == "bvh":
                pass  # BVH parser is pure Python
            elif fmt in ("openpose_json", "mediapipe_json"):
                pass  # JSON parsing is built-in
            elif fmt == "fbx":
                try:
                    import bpy  # noqa: F401
                except ImportError:
                    return False, "Blender Python not available for FBX"
            else:
                return False, f"Unknown format: {fmt}"
            return True, ""
        except ImportError as e:
            return False, f"Format loader not available: {e}"

    @pytest.mark.parametrize(
        "source_format,ik_backend,matching_backend",
        [
            (sf, ik, mm)
            for sf in SOURCE_FORMATS
            for ik in IK_BACKENDS
            for mm in MATCHING_BACKENDS
        ],
    )
    def test_compatibility_matrix(
        source_format: str,
        ik_backend: str,
        matching_backend: str,
    ) -> None:
        """Test each combination of source format and backends."""
        key = (source_format, ik_backend, matching_backend)
        if key in KNOWN_UNSUPPORTED:
            pytest.skip(f"Known unsupported: {KNOWN_UNSUPPORTED[key]}")

        if key in HEAVY_COMBINATIONS and os.environ.get("CI") == "true":
            pytest.skip(
                f"Heavy integration test skipped in CI: {HEAVY_COMBINATIONS[key]}"
            )

        ik_available, ik_reason = _check_backend_available(ik_backend)
        if not ik_available:
            pytest.skip(f"IK backend unavailable: {ik_reason}")

        mm_available, mm_reason = _check_backend_available(matching_backend)
        if not mm_available:
            pytest.skip(f"Matching backend unavailable: {mm_reason}")

        fmt_available, fmt_reason = _check_source_format_available(source_format)
        if not fmt_available:
            pytest.skip(f"Source format unavailable: {fmt_reason}")

        try:
            from src.engines.motion_pipeline.core.pipeline import MotionPipeline
            from src.engines.motion_pipeline.core.config import PipelineConfig

            config = PipelineConfig(
                source_format=source_format,
                ik_backend=ik_backend,
                matching_backend=matching_backend,
            )
            _ = MotionPipeline(config)

        except ImportError as e:
            pytest.skip(f"Pipeline not available: {e}")
        except NotImplementedError as e:
            pytest.xfail(f"Pipeline stage not implemented: {e}")

    def test_generate_matrix_file() -> None:
        """Generate the compatibility matrix markdown file."""
        DOCS_DIR.mkdir(parents=True, exist_ok=True)

        matrix_md = generate_compatibility_matrix()
        matrix_path = DOCS_DIR / "compat.md"

        matrix_path.write_text(matrix_md, encoding="utf-8")

        assert matrix_path.exists(), f"Matrix file not created: {matrix_path}"
        assert len(matrix_md) > 100, "Matrix file seems too short"


# ---------------------------------------------------------------------------
# CLI Entry Point
# ---------------------------------------------------------------------------


if __name__ == "__main__":
    if "--generate" in sys.argv:
        generate_matrix_file()
        sys.exit(0)

    # Run pytest if available
    try:
        import pytest

        sys.exit(pytest.main([__file__, "-v"]))
    except ImportError:
        print("pytest not installed. Run with --generate to generate matrix file.")
        sys.exit(1)
