cd(matlabdrive);
cd '2DModel/Scripts/_BaseData Scripts';

% PauseTime=0;

SCRIPT_101_PLOT_BaseData_AngularWork;
SCRIPT_102_PLOT_BaseData_AngularPower;
SCRIPT_103_PLOT_BaseData_LinearPower;
SCRIPT_104_PLOT_BaseData_LinearWork;
SCRIPT_105_PLOT_BaseData_JointTorqueInputs;
SCRIPT_106_PLOT_BaseData_TotalWork;
SCRIPT_107_PLOT_BaseData_TotalPower;
SCRIPT_112_QUIVER_BaseData_NetForceEquivalentCouple;
SCRIPT_113_QUIVER_BaseData_NetForce;
SCRIPT_114_QUIVER_BaseData_LWRWForce;
SCRIPT_115_QUIVER_BaseData_LWRWTorque;
SCRIPT_116_QUIVER_BaseData_AllTorqueandMoments;
SCRIPT_117_QUIVER_BaseData_AllMoments;
SCRIPT_118_QUIVER_BaseData_LeftUpperArmMoments;
SCRIPT_119_QUIVER_BaseData_RightUpperArmMoments;
SCRIPT_120_QUIVER_BaseData_LForearmMoments;
SCRIPT_121_QUIVER_BaseData_RForearmMoments;
SCRIPT_122_PLOT_BaseData_ForceAlongHandPath;
SCRIPT_123_PLOT_BaseData_CHSandHandSpeed;
SCRIPT_124_PLOT_BaseData_KinematicSequence;
SCRIPT_125_PLOT_BaseData_LeftHandRightHandForceAlongHandPath;
SCRIPT_126_PLOT_BaseData_LinearImpulse;
SCRIPT_127_PLOT_BaseData_LinearWork;
SCRIPT_128_PLOT_BaseData_LinearImpulse;
SCRIPT_129_PLOT_BaseData_EquivalentCoupleandMOF;
SCRIPT_130_PLOT_BaseData_LSWork;
SCRIPT_131_PLOT_BaseData_LSPower;
SCRIPT_132_PLOT_BaseData_RSWork;
SCRIPT_133_PLOT_BaseData_RSPower;
SCRIPT_134_PLOT_BaseData_LEWork;
SCRIPT_135_PLOT_BaseData_LEPower;
SCRIPT_136_PLOT_BaseData_REWork;
SCRIPT_137_PLOT_BaseData_REPower;
SCRIPT_138_PLOT_BaseData_LWWork;
SCRIPT_139_PLOT_BaseData_LWPower;
SCRIPT_140_PLOT_BaseData_RWWork;
SCRIPT_141_PLOT_BaseData_RWPower;
SCRIPT_142_QUIVER_BaseData_LHRHLinearImpulse;
SCRIPT_143_QUIVER_BaseData_LHRH_BaseData_AngularImpulse
SCRIPT_144_QUIVER_BaseData_TotalLinearImpulse;
SCRIPT_145_QUIVER_BaseData_TotalAngularImpulse;
SCRIPT_146_QUIVER_BaseData_NetForceEquivalantCoupleShaftsAdded;
SCRIPT_148_PLOT_BaseData_LocalHandForces;

% clear PauseTime;


