# WARNING: DO NOT EDIT THIS FILE DIRECTLY.
# This file is a child copy that shadows or shares code with the Tools repository.
# Canonical changes must be made in the Tools repository under src/shared/python/
# and synchronized back to UpstreamDrift. Direct edits here risk being lost.

"""Authentication and authorization module for AI features."""

from src.shared.python.ai.auth.authentication import (
    AuthManager,
    AuthToken,
    FeatureGate,
    SubscriptionTier,
    UserProfile,
    get_auth_manager,
)

__all__ = [
    "AuthManager",
    "FeatureGate",
    "SubscriptionTier",
    "UserProfile",
    "AuthToken",
    "get_auth_manager",
]
