"""MATLAB / Simscape model parameters exporter for canonical golfer specification.

Generates `InitModelParameters.m` declaring segment masses, lengths, and inertias
for consumption by Simscape Multibody models.
"""

from __future__ import annotations

import logging
from pathlib import Path

from tools.model_converter.schema_validator import CanonicalModel

logger = logging.getLogger(__name__)


def export_matlab_parameters(
    model: CanonicalModel, out_path: Path | None = None
) -> str:
    """Generate MATLAB script initializing canonical model parameters for Simscape."""
    lines: list[str] = [
        "% ============================================================================",
        "% InitModelParameters.m - Simscape Multibody Canonical Model Parameters",
        "% ============================================================================",
        "% Automatically generated by tools/model_converter/build_models.py",
        "% Source: src/engines/physics_engines/pinocchio/models/spec/golfer_canonical.yaml",
        "% ============================================================================",
        "",
        "function params = InitModelParameters()",
        "    % Returns a struct containing validated canonical segment parameters.",
        "    params = struct();",
        "",
        f"    % Total system mass: {model.total_mass:.4f} kg",
        f"    params.TotalMass = {model.total_mass:.6f};",
        "",
        "    % Pelvis (Root)",
        f"    params.Pelvis.Mass = {model.root.mass:.6f};",
        f"    params.Pelvis.Position = [{model.root.position[0]:g}, {model.root.position[1]:g}, {model.root.position[2]:g}];",
        f"    params.Pelvis.Inertia = [{model.root.inertia.ixx:g}, {model.root.inertia.iyy:g}, {model.root.inertia.izz:g}];",
        "",
        "    % Segments",
    ]

    for seg in model.segments:
        safe_name = seg.name.replace("-", "_")
        lines.extend(
            [
                f"    params.Segments.{safe_name}.Mass = {seg.mass:.6f};",
                f"    params.Segments.{safe_name}.Origin = [{seg.origin.xyz[0]:g}, {seg.origin.xyz[1]:g}, {seg.origin.xyz[2]:g}];",
                f"    params.Segments.{safe_name}.Inertia = [{seg.inertia.ixx:g}, {seg.inertia.iyy:g}, {seg.inertia.izz:g}];",
            ]
        )

    lines.extend(
        [
            "",
            "    % Assign directly into base workspace if invoked as a script",
            "    assignin('base', 'CanonicalGolferParams', params);",
            "end",
            "",
        ]
    )

    content = "\n".join(lines)
    if out_path:
        out_path = Path(out_path)
        out_path.parent.mkdir(parents=True, exist_ok=True)
        out_path.write_text(content, encoding="utf-8")
        logger.info("Wrote Simscape parameters script to %s", out_path)

    return content
