function tbl = to_machinelearning_columns(target, opts)
%TO_MACHINELEARNING_COLUMNS  Project a canonical target onto a flat table.
%
%   TBL = ML_COMPAT.TO_MACHINELEARNING_COLUMNS(TARGET) defaults to the
%   "clubface_*" schema. Use OPTS.schema = "clublogs" to emit
%   ClubLogs_CHGlobal* columns instead.
%
%   The butt position and orientation quaternion are not represented in
%   either flat schema and are silently dropped.

    arguments
        target struct
        opts.schema (1,1) string {mustBeMember(opts.schema, ["clubface","clublogs"])} = "clubface"
    end

    time = target.time(:);
    clubhead = target.clubhead;
    velocity = gradient_along(clubhead, time);
    acceleration = gradient_along(velocity, time);

    n = numel(time);
    impact = repmat(double(target.impact_idx), n, 1);

    if opts.schema == "clubface"
        tbl = table( ...
            time, ...
            clubhead(:,1), clubhead(:,2), clubhead(:,3), ...
            velocity(:,1), velocity(:,2), velocity(:,3), ...
            acceleration(:,1), acceleration(:,2), acceleration(:,3), ...
            impact, ...
            'VariableNames', { ...
                'time', ...
                'clubface_x','clubface_y','clubface_z', ...
                'clubface_vx','clubface_vy','clubface_vz', ...
                'clubface_ax','clubface_ay','clubface_az', ...
                'impact_idx'});
    else
        tbl = table( ...
            time, ...
            clubhead(:,1), clubhead(:,2), clubhead(:,3), ...
            velocity(:,1), velocity(:,2), velocity(:,3), ...
            acceleration(:,1), acceleration(:,2), acceleration(:,3), ...
            impact, ...
            'VariableNames', { ...
                'time', ...
                'ClubLogs_CHGlobalPosition_1', ...
                'ClubLogs_CHGlobalPosition_2', ...
                'ClubLogs_CHGlobalPosition_3', ...
                'ClubLogs_CHGlobalVelocity_1', ...
                'ClubLogs_CHGlobalVelocity_2', ...
                'ClubLogs_CHGlobalVelocity_3', ...
                'ClubLogs_CHGlobalAcceleration_1', ...
                'ClubLogs_CHGlobalAcceleration_2', ...
                'ClubLogs_CHGlobalAcceleration_3', ...
                'impact_idx'});
    end
end

function out = gradient_along(x, t)
    out = zeros(size(x));
    if size(x,1) > 1 && all(isfinite(t)) && numel(unique(t)) > 1
        for c = 1:size(x,2)
            out(:,c) = gradient(x(:,c), t);
        end
    else
        out(:) = NaN;
    end
end
