% ============================================================================
% InitModelParameters.m - Simscape Multibody Canonical Model Parameters
% ============================================================================
% Automatically generated by tools/model_converter/build_models.py
% Source: src/engines/physics_engines/pinocchio/models/spec/golfer_canonical.yaml
% ============================================================================

function params = InitModelParameters()
    % Returns a struct containing validated canonical segment parameters.
    params = struct();

    % Total system mass: 77.9500 kg
    params.TotalMass = 77.950000;

    % Pelvis (Root)
    params.Pelvis.Mass = 11.700000;
    params.Pelvis.Position = [0, 0, 0.9];
    params.Pelvis.Inertia = [0.1337, 0.1337, 0.1337];

    % Segments
    params.Segments.lumbar1.Mass = 2.000000;
    params.Segments.lumbar1.Origin = [0, 0, 0.12];
    params.Segments.lumbar1.Inertia = [0.015, 0.015, 0.002];
    params.Segments.lumbar2.Mass = 2.000000;
    params.Segments.lumbar2.Origin = [0, 0, 0.12];
    params.Segments.lumbar2.Inertia = [0.015, 0.015, 0.002];
    params.Segments.lumbar3.Mass = 2.000000;
    params.Segments.lumbar3.Origin = [0, 0, 0.12];
    params.Segments.lumbar3.Inertia = [0.015, 0.015, 0.002];
    params.Segments.thorax1.Mass = 6.000000;
    params.Segments.thorax1.Origin = [0, 0, 0.12];
    params.Segments.thorax1.Inertia = [0.0733, 0.0667, 0.0333];
    params.Segments.thorax2.Mass = 6.000000;
    params.Segments.thorax2.Origin = [0, 0, 0.1];
    params.Segments.thorax2.Inertia = [0.0733, 0.0667, 0.0333];
    params.Segments.thorax3.Mass = 6.000000;
    params.Segments.thorax3.Origin = [0, 0, 0.1];
    params.Segments.thorax3.Inertia = [0.0734, 0.0666, 0.0334];
    params.Segments.head.Mass = 5.000000;
    params.Segments.head.Origin = [0, 0, 0.15];
    params.Segments.head.Inertia = [0.03, 0.03, 0.03];
    params.Segments.scapula_right.Mass = 1.500000;
    params.Segments.scapula_right.Origin = [0, -0.18, 0.28];
    params.Segments.scapula_right.Inertia = [0.005, 0.005, 0.002];
    params.Segments.scapula_left.Mass = 1.500000;
    params.Segments.scapula_left.Origin = [0, 0.18, 0.28];
    params.Segments.scapula_left.Inertia = [0.005, 0.005, 0.002];
    params.Segments.upper_arm_right.Mass = 2.500000;
    params.Segments.upper_arm_right.Origin = [0, -0.04, 0.1];
    params.Segments.upper_arm_right.Inertia = [0.018, 0.018, 0.004];
    params.Segments.upper_arm_left.Mass = 2.500000;
    params.Segments.upper_arm_left.Origin = [0, 0.04, 0.1];
    params.Segments.upper_arm_left.Inertia = [0.018, 0.018, 0.004];
    params.Segments.forearm_right.Mass = 1.500000;
    params.Segments.forearm_right.Origin = [0, 0, -0.26];
    params.Segments.forearm_right.Inertia = [0.008, 0.008, 0.0015];
    params.Segments.forearm_left.Mass = 1.500000;
    params.Segments.forearm_left.Origin = [0, 0, -0.26];
    params.Segments.forearm_left.Inertia = [0.008, 0.008, 0.0015];
    params.Segments.hand_right.Mass = 0.500000;
    params.Segments.hand_right.Origin = [0, 0, -0.19];
    params.Segments.hand_right.Inertia = [0.001, 0.001, 0.0005];
    params.Segments.hand_left.Mass = 0.500000;
    params.Segments.hand_left.Origin = [0, 0, -0.19];
    params.Segments.hand_left.Inertia = [0.001, 0.001, 0.0005];
    params.Segments.fingers_right.Mass = 0.200000;
    params.Segments.fingers_right.Origin = [0, 0, -0.05];
    params.Segments.fingers_right.Inertia = [0.0003, 0.0003, 0.0001];
    params.Segments.fingers_left.Mass = 0.200000;
    params.Segments.fingers_left.Origin = [0, 0, -0.05];
    params.Segments.fingers_left.Inertia = [0.0003, 0.0003, 0.0001];
    params.Segments.right_thigh.Mass = 7.050000;
    params.Segments.right_thigh.Origin = [0, -0.09, -0.05];
    params.Segments.right_thigh.Inertia = [0.1058, 0.1058, 0.0203];
    params.Segments.right_shank.Mass = 3.530000;
    params.Segments.right_shank.Origin = [0, 0, -0.43];
    params.Segments.right_shank.Inertia = [0.0401, 0.0401, 0.0042];
    params.Segments.right_foot.Mass = 1.370000;
    params.Segments.right_foot.Origin = [0, 0, -0.43];
    params.Segments.right_foot.Inertia = [0.0034, 0.009, 0.009];
    params.Segments.right_toes.Mass = 0.300000;
    params.Segments.right_toes.Origin = [0.12, 0, -0.02];
    params.Segments.right_toes.Inertia = [0.0005, 0.0005, 0.0002];
    params.Segments.left_thigh.Mass = 7.050000;
    params.Segments.left_thigh.Origin = [0, 0.09, -0.05];
    params.Segments.left_thigh.Inertia = [0.1058, 0.1058, 0.0203];
    params.Segments.left_shank.Mass = 3.530000;
    params.Segments.left_shank.Origin = [0, 0, -0.43];
    params.Segments.left_shank.Inertia = [0.0401, 0.0401, 0.0042];
    params.Segments.left_foot.Mass = 1.370000;
    params.Segments.left_foot.Origin = [0, 0, -0.43];
    params.Segments.left_foot.Inertia = [0.0034, 0.009, 0.009];
    params.Segments.left_toes.Mass = 0.300000;
    params.Segments.left_toes.Origin = [0.12, 0, -0.02];
    params.Segments.left_toes.Inertia = [0.0005, 0.0005, 0.0002];
    params.Segments.club_shaft.Mass = 0.120000;
    params.Segments.club_shaft.Origin = [0, 0, -0.12];
    params.Segments.club_shaft.Inertia = [0.02, 0.02, 0.0001];
    params.Segments.club_head.Mass = 0.230000;
    params.Segments.club_head.Origin = [0, 0, -0.5];
    params.Segments.club_head.Inertia = [0.025, 0.025, 0.0001];

    % Assign directly into base workspace if invoked as a script
    assignin('base', 'CanonicalGolferParams', params);
end
