# WARNING: DO NOT EDIT THIS FILE DIRECTLY.
# This file is a child copy that shadows or shares code with the Tools repository.
# Canonical changes must be made in the Tools repository under src/shared/python/
# and synchronized back to UpstreamDrift. Direct edits here risk being lost.

"""Shared theme REST API router for FastAPI applications.

Provides a reusable router factory that any app with FastAPI can mount
to expose theme CRUD operations via REST endpoints.

Usage:
    from shared.python.theme.api import create_theme_router
    from shared.python.theme import ThemeManager

    manager = ThemeManager.instance()
    theme_router = create_theme_router(manager)
    app.include_router(theme_router, prefix="/api/v1/themes", tags=["Themes"])
"""

from __future__ import annotations

import logging
from typing import Any

from fastapi import APIRouter, HTTPException
from pydantic import BaseModel, ConfigDict, Field

logger = logging.getLogger(__name__)


# ---------------------------------------------------------------------------
# Pydantic models
# ---------------------------------------------------------------------------


class ThemeColors(BaseModel):
    """Canonical semantic colour schema for a fleet theme.

    This model is the single source of truth for the design-token vocabulary
    that consumers (PyQt6 widgets, React panes, matplotlib plots) read from.

    The schema is organised in tiers:

    - **Surface** — bg, bg_base, bg_deep, bg_surface, bg_elevated, bg_highlight,
      group_bg, input_bg
    - **Border** — border, border_subtle, border_default, border_strong,
      border_focus
    - **Text**   — text, text_primary, text_secondary, text_tertiary,
      text_quaternary, text_link, label
    - **Brand**  — primary, primary_hover, primary_pressed, primary_muted,
      accent, focus, button_hover
    - **Semantic** — success/warning/error/info, each with hover + muted
    - **Component** — title_bg, title_border, table_header, table_alt
    - **Chart** — chart_blue/green/orange/red/purple/cyan/yellow/brown
    - **Effect** — grid_line, axis_line, tick_color, shadow_light/medium/heavy

    Only the 14 base surface/border/text/component tokens are required at
    construction time; the rest are derived by ``model_post_init`` from those
    base tokens if not supplied, so partially-specified themes (custom user
    themes, the 22-token themes.json schema) still produce a fully populated
    instance.
    """

    model_config = ConfigDict(extra="allow", populate_by_name=True)

    # --- Identity ------------------------------------------------------------
    name: str | None = Field(default=None, description="Theme display name")
    is_dark: bool | None = Field(default=None, description="Whether theme is dark")

    # --- Surface (required base) --------------------------------------------
    bg: str = Field(..., description="Main background colour")
    group_bg: str = Field(..., description="Group/panel background")
    input_bg: str = Field(..., description="Input field background")

    # --- Border / text / accent (required base) -----------------------------
    border: str = Field(..., description="Standard border colour")
    text: str = Field(..., description="Primary text colour")
    text_secondary: str = Field(..., description="Secondary text colour")
    label: str = Field(..., description="Label / muted text colour")
    focus: str = Field(..., description="Focus highlight colour")
    accent: str = Field(..., description="Accent colour")

    # --- Component (required base) ------------------------------------------
    title_bg: str = Field(..., description="Title/header background")
    title_border: str = Field(..., description="Title/header border")
    table_header: str = Field(..., description="Table header background")
    table_alt: str = Field(..., description="Alternate table row")
    button_hover: str = Field(..., description="Button hover background")

    # --- Surface (derived) ---------------------------------------------------
    bg_base: str | None = Field(default=None, description="Alias of bg")
    bg_deep: str | None = Field(default=None, description="Deeper background")
    bg_surface: str | None = Field(default=None, description="Surface tier")
    bg_elevated: str | None = Field(default=None, description="Elevated surface")
    bg_highlight: str | None = Field(default=None, description="Highlighted surface")

    # --- Border (derived) ----------------------------------------------------
    border_subtle: str | None = Field(default=None)
    border_default: str | None = Field(default=None)
    border_strong: str | None = Field(default=None)
    border_focus: str | None = Field(default=None)

    # --- Text (derived) ------------------------------------------------------
    text_primary: str | None = Field(default=None)
    text_tertiary: str | None = Field(default=None)
    text_quaternary: str | None = Field(default=None)
    text_link: str | None = Field(default=None)

    # --- Brand / primary (derived) ------------------------------------------
    primary: str | None = Field(default=None)
    primary_hover: str | None = Field(default=None)
    primary_pressed: str | None = Field(default=None)
    primary_muted: str | None = Field(default=None)

    # --- Semantic (success / warning / error / info) ------------------------
    success: str | None = Field(default=None)
    success_hover: str | None = Field(default=None)
    success_muted: str | None = Field(default=None)
    warning: str | None = Field(default=None)
    warning_hover: str | None = Field(default=None)
    warning_muted: str | None = Field(default=None)
    error: str | None = Field(default=None)
    error_hover: str | None = Field(default=None)
    error_muted: str | None = Field(default=None)
    info: str | None = Field(default=None)
    info_hover: str | None = Field(default=None)
    info_muted: str | None = Field(default=None)
    link: str | None = Field(default=None)
    link_hover: str | None = Field(default=None)
    selection_bg: str | None = Field(default=None)
    selection_text: str | None = Field(default=None)

    # --- Charts --------------------------------------------------------------
    chart_blue: str | None = Field(default=None)
    chart_green: str | None = Field(default=None)
    chart_orange: str | None = Field(default=None)
    chart_red: str | None = Field(default=None)
    chart_purple: str | None = Field(default=None)
    chart_cyan: str | None = Field(default=None)
    chart_yellow: str | None = Field(default=None)
    chart_brown: str | None = Field(default=None)

    # --- Effects -------------------------------------------------------------
    grid_line: str | None = Field(default=None)
    axis_line: str | None = Field(default=None)
    tick_color: str | None = Field(default=None)
    shadow_light: str | None = Field(default=None)
    shadow_medium: str | None = Field(default=None)
    shadow_heavy: str | None = Field(default=None)

    # ------------------------------------------------------------------------
    # Derivation
    # ------------------------------------------------------------------------

    def model_post_init(self, __context: Any) -> None:
        """Fill in any unsupplied derived tokens from the base 14."""
        from . import color_derivation as _cd

        is_dark = self.is_dark
        if is_dark is None:
            is_dark = _cd.is_dark_bg(self.bg)
            object.__setattr__(self, "is_dark", is_dark)

        defaults: dict[str, str] = {
            "bg_base": self.bg,
            "bg_deep": self.input_bg,
            "bg_surface": self.group_bg,
            "bg_elevated": self.table_header,
            "bg_highlight": self.title_bg,
            "border_default": self.border,
            "border_subtle": _cd.adjust(self.border, 0.8 if is_dark else 1.1),
            "border_strong": _cd.adjust(self.border, 1.2 if is_dark else 0.9),
            "border_focus": self.focus,
            "text_primary": self.text,
            "text_tertiary": self.label,
            "text_quaternary": _cd.adjust(self.label, 0.7),
            "text_link": self.accent,
            "primary": self.accent,
            "primary_hover": _cd.adjust(self.accent, 1.2),
            "primary_pressed": _cd.adjust(self.accent, 0.8),
            "primary_muted": _cd.with_alpha(self.accent, 0x40),
            "success": "#30D158" if is_dark else "#28A745",
            "warning": "#FF9F0A" if is_dark else "#E67E00",
            "error": "#FF375F" if is_dark else "#DC3545",
            "info": "#64D2FF" if is_dark else "#17A2B8",
            "link": self.accent,
            "link_hover": _cd.adjust(self.accent, 1.2),
            "selection_bg": _cd.with_alpha(self.accent, 0x60),
            "selection_text": self.text,
            "chart_blue": self.accent,
            "chart_purple": "#BF5AF2" if is_dark else "#9B59B6",
            "chart_yellow": "#FFD60A" if is_dark else "#F0AD4E",
            "chart_brown": "#AC8E68" if is_dark else "#8B6914",
            "axis_line": self.border,
            "tick_color": self.label,
            "grid_line": _cd.adjust(self.border, 0.7 if is_dark else 1.2),
            "shadow_light": "rgba(0, 0, 0, 0.15)" if is_dark else "rgba(0, 0, 0, 0.08)",
            "shadow_medium": "rgba(0, 0, 0, 0.25)"
            if is_dark
            else "rgba(0, 0, 0, 0.12)",
            "shadow_heavy": "rgba(0, 0, 0, 0.40)" if is_dark else "rgba(0, 0, 0, 0.20)",
        }
        for key, val in defaults.items():
            if getattr(self, key, None) is None:
                object.__setattr__(self, key, val)

        for base_name in ("success", "warning", "error", "info"):
            base_val = getattr(self, base_name)
            if base_val is None:
                continue
            if getattr(self, f"{base_name}_hover", None) is None:
                object.__setattr__(
                    self, f"{base_name}_hover", _cd.adjust(base_val, 1.2)
                )
            if getattr(self, f"{base_name}_muted", None) is None:
                object.__setattr__(
                    self, f"{base_name}_muted", _cd.with_alpha(base_val, 0x40)
                )

        if self.chart_green is None:
            object.__setattr__(self, "chart_green", self.success)
        if self.chart_orange is None:
            object.__setattr__(self, "chart_orange", self.warning)
        if self.chart_red is None:
            object.__setattr__(self, "chart_red", self.error)
        if self.chart_cyan is None:
            object.__setattr__(self, "chart_cyan", self.info)

    # ------------------------------------------------------------------------
    # Backwards-compatible dict-style access
    # ------------------------------------------------------------------------

    def __getitem__(self, key: str) -> Any:
        try:
            return getattr(self, key)
        except AttributeError as err:
            extra = self.__pydantic_extra__ or {}
            if key in extra:
                return extra[key]
            raise KeyError(key) from err

    def __contains__(self, key: str) -> bool:
        if key in type(self).model_fields:
            return getattr(self, key, None) is not None
        return key in (self.__pydantic_extra__ or {})

    def get(self, key: str, default: Any = None) -> Any:
        """dict.get-compatible lookup that returns None / default for missing keys."""
        try:
            val = self[key]
        except KeyError:
            return default
        return default if val is None else val

    def keys(self) -> list[str]:
        """Return all declared + extra field names with non-None values."""
        declared = [
            k for k in type(self).model_fields if getattr(self, k, None) is not None
        ]
        return declared + list((self.__pydantic_extra__ or {}).keys())

    def as_dict(self) -> dict[str, Any]:
        """Return the resolved token dict (all derived defaults applied)."""
        data = self.model_dump(exclude_none=False)
        data.update(self.__pydantic_extra__ or {})
        return data


class ThemeDefinition(BaseModel):
    """Full theme definition with name and colors."""

    name: str
    is_builtin: bool = False
    colors: dict[str, str]


class ThemeListResponse(BaseModel):
    """Response for listing themes."""

    themes: dict[str, ThemeDefinition]


class ActiveThemeResponse(BaseModel):
    """Response for the active theme."""

    name: str
    is_builtin: bool
    colors: dict[str, str]


class SetActiveThemeRequest(BaseModel):
    """Request to change the active theme."""

    name: str = Field(..., description="Theme name to activate")


class SaveCustomThemeRequest(BaseModel):
    """Request to create or update a custom theme."""

    name: str = Field(..., description="Custom theme name")
    colors: dict[str, str] = Field(..., description="Color key-value pairs")
    apply: bool = Field(False, description="Apply theme immediately after saving")


class ThemeOperationResponse(BaseModel):
    """Generic response for theme operations."""

    success: bool
    message: str
    theme_name: str | None = None

    @property
    def solver_status(self) -> str:
        """Return 'success' or 'failed' based on success flag."""
        return "success" if self.success else "failed"


# ---------------------------------------------------------------------------
# Router factory
# ---------------------------------------------------------------------------


def _register_builtin_endpoints(router: APIRouter, theme_manager: Any) -> None:
    """Register built-in theme listing endpoint."""

    @router.get(
        "/builtin",
        response_model=ThemeListResponse,
        summary="List all built-in themes",
    )
    async def get_builtin_themes() -> ThemeListResponse:
        """Return all built-in theme definitions."""
        themes: dict[str, ThemeDefinition] = {}
        for name in theme_manager.get_builtin_themes():
            colors = theme_manager.get_theme_colors(name)
            if colors:
                themes[name] = ThemeDefinition(
                    name=name, is_builtin=True, colors=colors
                )
        return ThemeListResponse(themes=themes)


def _register_custom_endpoints(router: APIRouter, theme_manager: Any) -> None:
    """Register custom theme CRUD endpoints."""

    if router is None:
        raise ValueError("router must be provided")

    @router.get(
        "/custom",
        response_model=ThemeListResponse,
        summary="List all custom themes",
    )
    async def get_custom_themes() -> ThemeListResponse:
        """Return all user-defined custom themes."""
        themes: dict[str, ThemeDefinition] = {}
        for name in theme_manager.get_custom_theme_names():
            colors = theme_manager.get_theme_colors(name)
            if colors:
                themes[name] = ThemeDefinition(
                    name=name, is_builtin=False, colors=colors
                )
        return ThemeListResponse(themes=themes)

    @router.post(
        "/custom",
        response_model=ThemeOperationResponse,
        summary="Create or update a custom theme",
    )
    async def save_custom_theme(
        request: SaveCustomThemeRequest,
    ) -> ThemeOperationResponse:
        """Save a custom theme. Overwrites if the name already exists."""
        try:
            saved_name = theme_manager.save_custom_theme(
                request.name, request.colors, request.apply
            )
            return ThemeOperationResponse(
                success=True,
                message=f"Theme '{saved_name}' saved successfully",
                theme_name=saved_name,
            )
        except ValueError as exc:
            raise HTTPException(status_code=400, detail=str(exc)) from exc

    @router.delete(
        "/custom/{theme_id}",
        response_model=ThemeOperationResponse,
        summary="Delete a custom theme",
    )
    async def delete_custom_theme(theme_id: str) -> ThemeOperationResponse:
        """Delete a user-defined custom theme by name."""
        success = theme_manager.delete_custom_theme(theme_id)
        if not success:
            raise HTTPException(
                status_code=404, detail=f"Custom theme '{theme_id}' not found"
            )
        return ThemeOperationResponse(
            success=True,
            message=f"Theme '{theme_id}' deleted",
            theme_name=theme_id,
        )


def _register_active_and_list_endpoints(router: APIRouter, theme_manager: Any) -> None:  # noqa: C901
    """Register active theme and full listing endpoints."""

    if router is None:
        raise ValueError("router must be provided")

    @router.get(
        "/active",
        response_model=ActiveThemeResponse,
        summary="Get the currently active theme",
    )
    async def get_active_theme() -> ActiveThemeResponse:
        """Return the currently active theme with its colors."""
        name = theme_manager.get_current_theme_name()
        colors = theme_manager.get_current_colors()
        is_builtin = name in theme_manager.get_builtin_themes()
        return ActiveThemeResponse(name=name, is_builtin=is_builtin, colors=colors)

    @router.put(
        "/active",
        response_model=ThemeOperationResponse,
        summary="Set the active theme",
    )
    async def set_active_theme(
        request: SetActiveThemeRequest,
    ) -> ThemeOperationResponse:
        """Change the currently active theme."""
        available = theme_manager.get_available_themes()
        if request.name not in available:
            raise HTTPException(
                status_code=404,
                detail=f"Theme '{request.name}' not found. "
                f"Available: {', '.join(available)}",
            )
        theme_manager.change_theme(request.name)
        return ThemeOperationResponse(
            success=True,
            message=f"Active theme set to '{request.name}'",
            theme_name=request.name,
        )

    @router.get(
        "/",
        response_model=ThemeListResponse,
        summary="List all available themes",
    )
    async def get_all_themes() -> ThemeListResponse:
        """Return all themes (built-in and custom)."""
        themes: dict[str, ThemeDefinition] = {}

        for name in theme_manager.get_builtin_themes():
            colors = theme_manager.get_theme_colors(name)
            if colors:
                themes[name] = ThemeDefinition(
                    name=name, is_builtin=True, colors=colors
                )

        for name in theme_manager.get_custom_theme_names():
            colors = theme_manager.get_theme_colors(name)
            if colors:
                themes[name] = ThemeDefinition(
                    name=name, is_builtin=False, colors=colors
                )

        return ThemeListResponse(themes=themes)


def create_theme_router(theme_manager: Any, *, prefix: str = "") -> APIRouter:
    """Create a FastAPI router for theme CRUD operations.

    The router exposes endpoints for listing, creating, updating, and
    deleting themes. It wraps an existing ThemeManager instance.

    Args:
        theme_manager: A ThemeManager instance (from shared.python.theme)
        prefix: Optional URL prefix for the router (e.g., "/themes")

    Returns:
        FastAPI APIRouter ready to be mounted
    """
    router = APIRouter(prefix=prefix)
    _register_builtin_endpoints(router, theme_manager)
    _register_custom_endpoints(router, theme_manager)
    _register_active_and_list_endpoints(router, theme_manager)
    return router
