"""Configuration management, environment, and model registry."""

from .config_utils import ConfigLoader, load_json_config, load_yaml_config, merge_configs, save_json_config, save_yaml_config, validate_config
from .configuration_manager import ConfigurationManager, SimulationConfig
from .environment import (
    EnvironmentError,
    get_admin_password,
    get_api_host,
    get_api_port,
    get_database_url,
    get_env,
    get_env_bool,
    get_env_float,
    get_env_int,
    get_env_list,
    get_environment,
    get_golf_port,
    get_golf_suite_mode,
    get_golf_ui_dist,
    get_log_level,
    get_secret_key,
    is_auth_disabled,
    is_browser_suppressed,
    is_development,
    is_docker,
    is_headless,
    is_production,
    is_wsl,
    require_env,
)
from .handedness_support import (
    Handedness,
    HandednessConverter,
    MirrorTransform,
    create_mirror_transform,
    detect_handedness_from_metadata,
    mirror_joint_configuration,
    mirror_position,
    mirror_rotation_matrix,
    mirror_trajectory,
    mirror_velocity,
    validate_energy_conservation,
    validate_mirror_trajectory,
)
from .model_pack_manifest import (
    CrossEngineIdentity,
    ExchangeArtifact,
    LauncherPresentationMetadata,
    ModelPackEntry,
    ModelPackManifest,
    ProvenanceMetadata,
    group_entries_by_canonical_id,
)
from .model_registry import ModelConfig, ModelRegistry, ModelRegistryLoadError
from .model_source_providers import (
    LocalRepoModelSourceProvider,
    ModelSourcePathPolicy,
    ResolvedModelSource,
    SiblingRepoModelSourceProvider,
    collect_engine_provider_paths,
    iter_unique_python_path_strings,
    resolve_model_artifact,
    resolve_model_python_paths,
    resolve_model_source,
    resolve_model_source_root,
    resolve_model_working_directory,
)
from .provider_catalog import (
    ProviderRepoDefinition,
    infer_repo_root_from_config,
    iter_configured_provider_roots,
    iter_known_engine_provider_ids,
    iter_known_provider_ids,
    iter_known_provider_repo_names,
    iter_known_utility_provider_ids,
    iter_provider_manifest_specs,
)
from .settings import get_setting, load_settings, save_settings
from .standard_models import StandardModelManager

__all__: list[str] = [
    # config_utils
    "ConfigLoader",
    "load_json_config",
    "load_yaml_config",
    "merge_configs",
    "save_json_config",
    "save_yaml_config",
    "validate_config",
    # configuration_manager
    "ConfigurationManager",
    "SimulationConfig",
    # environment
    "EnvironmentError",
    "get_admin_password",
    "get_api_host",
    "get_api_port",
    "get_database_url",
    "get_env",
    "get_env_bool",
    "get_env_float",
    "get_env_int",
    "get_env_list",
    "get_environment",
    "get_golf_port",
    "get_golf_suite_mode",
    "get_golf_ui_dist",
    "get_log_level",
    "get_secret_key",
    "is_auth_disabled",
    "is_browser_suppressed",
    "is_development",
    "is_docker",
    "is_headless",
    "is_production",
    "is_wsl",
    "require_env",
    # handedness_support
    "Handedness",
    "HandednessConverter",
    "MirrorTransform",
    "create_mirror_transform",
    "detect_handedness_from_metadata",
    "mirror_joint_configuration",
    "mirror_position",
    "mirror_rotation_matrix",
    "mirror_trajectory",
    "mirror_velocity",
    "validate_energy_conservation",
    "validate_mirror_trajectory",
    # model_pack_manifest
    "CrossEngineIdentity",
    "ExchangeArtifact",
    "LauncherPresentationMetadata",
    "ModelPackEntry",
    "ModelPackManifest",
    "ProvenanceMetadata",
    "group_entries_by_canonical_id",
    # model_registry
    "ModelConfig",
    "ModelRegistry",
    "ModelRegistryLoadError",
    # model_source_providers
    "LocalRepoModelSourceProvider",
    "ModelSourcePathPolicy",
    "ResolvedModelSource",
    "SiblingRepoModelSourceProvider",
    "collect_engine_provider_paths",
    "iter_unique_python_path_strings",
    "resolve_model_artifact",
    "resolve_model_python_paths",
    "resolve_model_source",
    "resolve_model_source_root",
    "resolve_model_working_directory",
    # provider_catalog
    "ProviderRepoDefinition",
    "infer_repo_root_from_config",
    "iter_configured_provider_roots",
    "iter_known_engine_provider_ids",
    "iter_known_provider_ids",
    "iter_known_provider_repo_names",
    "iter_known_utility_provider_ids",
    "iter_provider_manifest_specs",
    # settings
    "get_setting",
    "load_settings",
    "save_settings",
    # standard_models
    "StandardModelManager",
]