# WARNING: DO NOT EDIT THIS FILE DIRECTLY.
# This file is a child copy that shadows or shares code with the Tools repository.
# Canonical changes must be made in the Tools repository under src/shared/python/
# and synchronized back to UpstreamDrift. Direct edits here risk being lost.

"""UI managers for Upstream Drift Tools."""

from .unit_preferences_manager import (
    UNIT_CATEGORIES,
    UnitCategory,
    UnitPreferencesManager,
    get_unit_preferences_manager,
)

__all__ = [
    "UNIT_CATEGORIES",
    "UnitCategory",
    "UnitPreferencesManager",
    "get_unit_preferences_manager",
]
