# WARNING: DO NOT EDIT THIS FILE DIRECTLY.
# This file is a child copy that shadows or shares code with the Tools repository.
# Canonical changes must be made in the Tools repository under src/shared/python/
# and synchronized back to UpstreamDrift. Direct edits here risk being lost.

"""test_contracts.py module."""

import pytest
from humanoid_character_builder.contracts import (
    ContractViolationError,
    invariant,
    postcondition,
    precondition,
)


def test_precondition_valid() -> None:
    @precondition(lambda x: x > 0)
    def func(x: int) -> int:
        return x

    assert func(5) == 5


def test_precondition_invalid() -> None:
    @precondition(lambda x: x > 0)
    def func(x: int) -> int:
        return x

    with pytest.raises(ContractViolationError):
        func(-1)


def test_precondition_argument_binding() -> None:
    @precondition(lambda y: y > 0)
    def func(x: int, y: int) -> int:
        return x + y

    assert func(1, 2) == 3

    with pytest.raises(ContractViolationError):
        func(1, -2)


def test_precondition_with_kwargs() -> None:
    @precondition(lambda y: y > 0)
    def func(x: int, y: int = 10) -> int:
        return x + y

    assert func(1) == 11
    assert func(1, y=5) == 6

    with pytest.raises(ContractViolationError):
        func(1, y=-1)


def test_postcondition_valid() -> None:
    @postcondition(lambda r: r > 0)
    def func(x: int) -> int:
        return x * x

    assert func(2) == 4


def test_postcondition_invalid() -> None:
    @postcondition(lambda r: r > 0)
    def func(x: int) -> int:
        return x

    with pytest.raises(ContractViolationError):
        func(-1)


def test_invariant() -> None:
    @invariant(lambda self: self.value > 0)
    class Counter:
        def __init__(self, value: int) -> None:
            self.value = value

        def increment(self) -> int:
            self.value += 1
            return self.value

        def decrement(self) -> int:
            self.value -= 1
            return self.value

    c = Counter(5)
    assert c.increment() == 6

    with pytest.raises(ContractViolationError):
        Counter(-1)

    c = Counter(1)
    with pytest.raises(ContractViolationError):
        c.decrement()  # Becomes 0, fails invariant > 0


def test_precondition_message() -> None:
    @precondition(lambda x: x > 0, "X must be positive")
    def func(x: int) -> int:
        return x

    with pytest.raises(ContractViolationError, match="X must be positive"):
        func(-1)
