//! Full-stack parity tests vs the Python source-of-truth.
//!
//! Covers:
//!
//! 1. `parity_activation.csv`   — Euler-step activation dynamics
//! 2. `parity_muscle_force.csv` — `HillMuscleModel.compute_force`
//! 3. `parity_joint_torque.csv` — `MuscleGroup.compute_net_torque`
//! 4. `parity_step_full.csv`    — Combined RL step (u → a → F → τ)
//!
//! Acceptance bar (UD#5216): max abs diff <= 1e-6 per row.
//!
//! Fixtures are regenerated by
//! `scripts/generate_parity_fixture_full.py`. The reference values come
//! from `src/shared/python/biomechanics/*.py`, which is the documented
//! contract for OpenSim/MuJoCo numerical parity (it ports the OpenSim
//! analytical curves verbatim).

use std::fs;
use std::path::PathBuf;

use upstream_muscle::activation::ActivationDynamics;
use upstream_muscle::model::{HillMuscleModel, MuscleParameters, MuscleState};
use upstream_muscle::multi::joint_torque;

const PARITY_TOL: f64 = 1e-6;

fn fixture(name: &str) -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .join("tests")
        .join(name)
}

fn read_csv(name: &str) -> Vec<Vec<String>> {
    let text = fs::read_to_string(fixture(name)).expect("read fixture");
    text.lines()
        .skip(1) // header
        .filter(|line| !line.trim().is_empty())
        .map(|line| line.split(',').map(|s| s.to_string()).collect())
        .collect()
}

fn parse_f(s: &str) -> f64 {
    s.trim()
        .parse()
        .unwrap_or_else(|_| panic!("parse f64 from '{s}'"))
}

#[test]
fn activation_dynamics_matches_python_within_1e_minus_6() {
    let rows = read_csv("parity_activation.csv");
    assert!(!rows.is_empty(), "activation fixture must not be empty");
    let mut max_diff = 0.0_f64;
    for r in rows {
        let tau_act = parse_f(&r[0]);
        let tau_deact = parse_f(&r[1]);
        let min_act = parse_f(&r[2]);
        let u = parse_f(&r[3]);
        let a = parse_f(&r[4]);
        let dt_or_t = parse_f(&r[5]);
        let a_new_py = parse_f(&r[6]);
        let dyn_params =
            ActivationDynamics::new(tau_act, tau_deact, min_act).expect("valid activation params");
        let a_new_rs = if a == 0.0 && dt_or_t > 0.0011 {
            // Step-response trace sample: replay from t=0 with the same
            // square-wave excitation the fixture writer used.
            let n = (dt_or_t / 0.001).round() as usize;
            let mut a_run = 0.0;
            for k in 0..n {
                let uu = if k < 100 { 1.0 } else { 0.0 };
                a_run = dyn_params.update(uu, a_run, 0.001).unwrap();
            }
            a_run
        } else {
            dyn_params.update(u, a, dt_or_t).unwrap()
        };
        let d = (a_new_rs - a_new_py).abs();
        if d > max_diff {
            max_diff = d;
        }
    }
    assert!(
        max_diff <= PARITY_TOL,
        "activation parity exceeded {PARITY_TOL:e}: max abs diff = {max_diff:e}"
    );
    eprintln!("activation parity OK: max abs diff = {max_diff:e}");
}

#[test]
fn muscle_force_matches_python_within_1e_minus_6() {
    let rows = read_csv("parity_muscle_force.csv");
    assert!(!rows.is_empty(), "muscle force fixture must not be empty");
    let mut max_diff = 0.0_f64;
    for r in rows {
        let params = MuscleParameters::new(
            parse_f(&r[0]),
            parse_f(&r[1]),
            parse_f(&r[2]),
            parse_f(&r[3]),
            parse_f(&r[4]),
            parse_f(&r[5]),
        )
        .expect("valid muscle params");
        let model = HillMuscleModel::new(params, Some(parse_f(&r[6])));
        let s = MuscleState {
            activation: parse_f(&r[7]),
            l_ce: parse_f(&r[8]),
            v_ce: parse_f(&r[9]),
            l_mt: 0.0,
        };
        let f_py = parse_f(&r[10]);
        let f_rs = model.compute_force(&s).expect("compute_force");
        let d = (f_rs - f_py).abs();
        if d > max_diff {
            max_diff = d;
        }
    }
    assert!(
        max_diff <= PARITY_TOL,
        "muscle force parity exceeded {PARITY_TOL:e}: max abs diff = {max_diff:e}"
    );
    eprintln!("muscle force parity OK: max abs diff = {max_diff:e}");
}

fn elbow_muscles() -> Vec<(HillMuscleModel, f64)> {
    vec![
        (
            HillMuscleModel::new(
                MuscleParameters::new(1000.0, 0.15, 0.20, 10.0, 0.0, 0.05).unwrap(),
                None,
            ),
            0.04,
        ),
        (
            HillMuscleModel::new(
                MuscleParameters::new(800.0, 0.12, 0.10, 10.0, 0.0, 0.05).unwrap(),
                None,
            ),
            0.03,
        ),
        (
            HillMuscleModel::new(
                MuscleParameters::new(1200.0, 0.18, 0.22, 10.0, 0.0, 0.05).unwrap(),
                None,
            ),
            -0.035,
        ),
    ]
}

#[test]
fn joint_torque_matches_python_within_1e_minus_6() {
    let rows = read_csv("parity_joint_torque.csv");
    assert!(!rows.is_empty(), "joint torque fixture must not be empty");

    let muscles = elbow_muscles();
    let mut max_diff = 0.0_f64;
    for r in rows {
        let acts = [parse_f(&r[0]), parse_f(&r[1]), parse_f(&r[2])];
        let l_ratio = parse_f(&r[3]);
        let v_ratio = parse_f(&r[4]);
        let tau_py = parse_f(&r[5]);

        let mut forces = [0.0; 3];
        let mut arms = [0.0; 3];
        for (i, (model, r_arm)) in muscles.iter().enumerate() {
            let s = MuscleState {
                activation: acts[i],
                l_ce: l_ratio * model.params.l_opt,
                v_ce: v_ratio * model.params.v_max * model.params.l_opt,
                l_mt: 0.0,
            };
            forces[i] = model.compute_force(&s).unwrap();
            arms[i] = *r_arm;
        }
        let tau_rs = joint_torque(&arms, &forces);
        let d = (tau_rs - tau_py).abs();
        if d > max_diff {
            max_diff = d;
        }
    }
    assert!(
        max_diff <= PARITY_TOL,
        "joint torque parity exceeded {PARITY_TOL:e}: max abs diff = {max_diff:e}"
    );
    eprintln!("joint torque parity OK: max abs diff = {max_diff:e}");
}

#[test]
fn step_full_matches_python_within_1e_minus_6() {
    let rows = read_csv("parity_step_full.csv");
    assert!(!rows.is_empty(), "step_full fixture must not be empty");

    let muscles = elbow_muscles();
    let dyn_params = ActivationDynamics::default();
    let dt = 0.001;
    let mut a = [0.0_f64; 3];
    let mut max_diff_a = 0.0_f64;
    let mut max_diff_tau = 0.0_f64;

    for (k, r) in rows.iter().enumerate() {
        let u = [parse_f(&r[1]), parse_f(&r[2]), parse_f(&r[3])];
        let a_py = [parse_f(&r[4]), parse_f(&r[5]), parse_f(&r[6])];
        let tau_py = parse_f(&r[10]);

        for i in 0..3 {
            a[i] = dyn_params.update(u[i], a[i], dt).unwrap();
        }
        let mut forces = [0.0; 3];
        for (i, (model, _)) in muscles.iter().enumerate() {
            let s = MuscleState {
                activation: a[i],
                l_ce: model.params.l_opt,
                v_ce: 0.0,
                l_mt: 0.0,
            };
            forces[i] = model.compute_force(&s).unwrap();
        }
        let arms: [f64; 3] = [muscles[0].1, muscles[1].1, muscles[2].1];
        let tau_rs = joint_torque(&arms, &forces);

        for i in 0..3 {
            let d = (a[i] - a_py[i]).abs();
            if d > max_diff_a {
                max_diff_a = d;
            }
        }
        let d = (tau_rs - tau_py).abs();
        if d > max_diff_tau {
            max_diff_tau = d;
        }

        if k == 0 {
            assert!(a.iter().all(|x| x.is_finite()));
        }
    }
    assert!(
        max_diff_a <= PARITY_TOL,
        "step_full activation parity exceeded {PARITY_TOL:e}: max abs diff = {max_diff_a:e}"
    );
    assert!(
        max_diff_tau <= PARITY_TOL,
        "step_full torque parity exceeded {PARITY_TOL:e}: max abs diff = {max_diff_tau:e}"
    );
    eprintln!("step_full parity OK: max abs diff a = {max_diff_a:e}, tau = {max_diff_tau:e}");
}
