# WARNING: DO NOT EDIT THIS FILE DIRECTLY.
# This file is a child copy that shadows or shares code with the Tools repository.
# Canonical changes must be made in the Tools repository under src/shared/python/
# and synchronized back to UpstreamDrift. Direct edits here risk being lost.

"""Global report registry — maps report type names to ``JinjaReportTemplate`` instances.

Usage::

    from src.shared.python.reporting import GLOBAL_REPORT_REGISTRY

    template = GLOBAL_REPORT_REGISTRY["swing_analysis"]
    md = template.render({"title": "Driver Swing", "run_id": "run_001", ...})

Registry keys
-------------
- ``swing_analysis``  — full swing biomechanics and kinematics report
- ``ball_flight``     — aerodynamic trajectory and landing analysis report
- ``biomechanics``    — joint angles, torques, and energy transfer report
- ``equipment``       — club/ball equipment specification and performance report

Implements part of Issue #5423.
"""

from __future__ import annotations

from src.shared.python.reporting._jinja_template import JinjaReportTemplate

# ---------------------------------------------------------------------------
# Template bodies (DRY: each section is defined once)
# ---------------------------------------------------------------------------

_SWING_ANALYSIS_TEMPLATE = """\
# Swing Analysis Report — {{ title | default('Untitled') }}

**Run ID:** {{ run_id }}
**Date:** {{ date | default('N/A') }}
**Engine:** {{ engine | default('Unknown') }}

---

## Club Head Speed
- **Peak CHS:** {{ peak_chs_mph | default('N/A') }} mph
- **At Impact:** {{ impact_chs_mph | default('N/A') }} mph

## Kinematic Sequence
{{ kinematic_sequence | default('No kinematic sequence data available.') }}

## Launch Conditions
- **Ball Speed:** {{ ball_speed_mph | default('N/A') }} mph
- **Launch Angle:** {{ launch_angle_deg | default('N/A') }}°
- **Spin Rate:** {{ spin_rate_rpm | default('N/A') }} rpm

## Insights
{{ insights | default('Run analysis to generate insights.') }}

---
*Generated by UpstreamDrift Swing Analysis Reporter*
"""

_BALL_FLIGHT_TEMPLATE = """\
# Ball Flight Report — {{ title | default('Untitled') }}

**Run ID:** {{ run_id }}
**Date:** {{ date | default('N/A') }}
**Flight Model:** {{ flight_model | default('Unknown') }}

---

## Trajectory Summary
- **Carry Distance:** {{ carry_yards | default('N/A') }} yards
- **Total Distance:** {{ total_yards | default('N/A') }} yards
- **Max Height:** {{ max_height_ft | default('N/A') }} ft
- **Landing Angle:** {{ landing_angle_deg | default('N/A') }}°

## Aerodynamics
- **Initial Speed:** {{ initial_speed_mph | default('N/A') }} mph
- **Launch Angle:** {{ launch_angle_deg | default('N/A') }}°
- **Spin Rate:** {{ spin_rate_rpm | default('N/A') }} rpm
- **Wind:** {{ wind_description | default('None') }}

## Insights
{{ insights | default('Run analysis to generate insights.') }}

---
*Generated by UpstreamDrift Ball Flight Reporter*
"""

_BIOMECHANICS_TEMPLATE = """\
# Biomechanics Report — {{ title | default('Untitled') }}

**Run ID:** {{ run_id }}
**Date:** {{ date | default('N/A') }}
**Model:** {{ humanoid_model | default('Unknown') }}

---

## Joint Angles at Impact
{{ joint_angles | default('No joint angle data available.') }}

## Peak Torques
{{ peak_torques | default('No torque data available.') }}

## Energy Transfer
- **Total Mechanical Work:** {{ total_work_j | default('N/A') }} J
- **Transfer Efficiency:** {{ transfer_efficiency_pct | default('N/A') }}%

## Muscle Activity
{{ muscle_activity | default('No muscle activity data available.') }}

## Insights
{{ insights | default('Run analysis to generate insights.') }}

---
*Generated by UpstreamDrift Biomechanics Reporter*
"""

_EQUIPMENT_TEMPLATE = """\
# Equipment Report — {{ title | default('Untitled') }}

**Run ID:** {{ run_id }}
**Date:** {{ date | default('N/A') }}

---

## Club Specification
- **Type:** {{ club_type | default('Driver') }}
- **Loft:** {{ loft_deg | default('N/A') }}°
- **Length:** {{ shaft_length_in | default('N/A') }} in
- **Flex:** {{ shaft_flex | default('N/A') }}
- **Swing Weight:** {{ swing_weight | default('N/A') }}

## Ball Specification
- **Model:** {{ ball_model | default('Standard') }}
- **Diameter:** {{ ball_diameter_mm | default('42.67') }} mm
- **Mass:** {{ ball_mass_g | default('45.9') }} g
- **Dimple Pattern:** {{ dimple_pattern | default('Standard') }}

## Performance Metrics
- **Smash Factor:** {{ smash_factor | default('N/A') }}
- **Gear Effect Spin:** {{ gear_effect_spin_rpm | default('N/A') }} rpm

## Insights
{{ insights | default('Run analysis to generate insights.') }}

---
*Generated by UpstreamDrift Equipment Reporter*
"""

# ---------------------------------------------------------------------------
# Public registry — one entry per report type
# ---------------------------------------------------------------------------

GLOBAL_REPORT_REGISTRY: dict[str, JinjaReportTemplate] = {
    "swing_analysis": JinjaReportTemplate("swing_analysis", _SWING_ANALYSIS_TEMPLATE),
    "ball_flight": JinjaReportTemplate("ball_flight", _BALL_FLIGHT_TEMPLATE),
    "biomechanics": JinjaReportTemplate("biomechanics", _BIOMECHANICS_TEMPLATE),
    "equipment": JinjaReportTemplate("equipment", _EQUIPMENT_TEMPLATE),
}
"""Global mapping of report type → ``JinjaReportTemplate`` instance.

Registered report types: ``swing_analysis``, ``ball_flight``,
``biomechanics``, ``equipment``.
"""
