"""Advanced export formats for golf swing data.

This module re-exports the canonical implementations from
``src.shared.python.export`` to maintain backward compatibility.
MuJoCo-specific additions (MATLAB script generation) are kept here.

DRY refactoring: duplicate MATLAB/HDF5/C3D functions removed in favour
of the shared module (Issue #842).
"""

from __future__ import annotations

from pathlib import Path
from typing import Any

from src.shared.python.data_io.export import (
    export_recording_all_formats as _shared_export_all,
)

# Re-export all shared export functions so existing imports still work
from src.shared.python.data_io.export import (  # noqa: F401
    export_to_c3d,  # noqa: F401
    export_to_hdf5,  # noqa: F401
    export_to_matlab,  # noqa: F401
    get_available_export_formats,
)


def export_recording_all_formats(
    base_path: str,
    data_dict: dict[str, Any],
    formats: list | None = None,
) -> dict[str, bool]:
    """Export recording in multiple formats.

    Delegates to the shared implementation, falling back to the
    engine-local telemetry helpers for JSON/CSV when available.
    """
    try:
        from .telemetry import export_telemetry_csv, export_telemetry_json
    except ImportError:
        # No local telemetry module – use shared implementation directly
        return _shared_export_all(base_path, data_dict, formats)

    import numpy as np

    if formats is None:
        formats = ["json", "csv", "mat", "hdf5"]
    base_path_obj = Path(base_path)
    results: dict[str, bool] = {}

    for fmt in formats:
        try:
            output_path = base_path_obj.with_suffix(f".{fmt}")

            if fmt == "json":
                success = export_telemetry_json(str(output_path), data_dict)
            elif fmt == "csv":
                success = export_telemetry_csv(str(output_path), data_dict)
            elif fmt == "mat":
                success = export_to_matlab(str(output_path), data_dict)
            elif fmt in ("hdf5", "h5"):
                output_path = base_path_obj.with_suffix(".h5")
                success = export_to_hdf5(str(output_path), data_dict)
            elif fmt == "c3d":
                times = data_dict.get("times", np.array([]))
                positions = data_dict.get("joint_positions", np.array([]))
                num_joints = 0
                if positions.size > 0:
                    if positions.ndim > 1:
                        num_joints = positions.shape[1]
                    else:
                        num_joints = 1
                        positions = positions.reshape(-1, 1)
                joint_names = data_dict.get(
                    "joint_names",
                    [f"Joint{i}" for i in range(num_joints)],
                )
                forces = data_dict.get("ground_reaction_forces")
                success = export_to_c3d(
                    str(output_path),
                    times,
                    positions,
                    joint_names,
                    forces=forces,
                )
            else:
                success = False

            results[fmt] = success

        except (ValueError, TypeError, RuntimeError):
            results[fmt] = False

    return results


def create_matlab_script(
    output_path: str,
    mat_file: str,
    script_type: str = "plot",
) -> None:
    """Create a MATLAB script to load and visualize exported data.

    Args:
        output_path: Output .m script path
        mat_file: Path to .mat file (relative or absolute)
        script_type: Type of script ('plot', 'analyze', 'animate')
    """
    mat_file = Path(mat_file).name

    if script_type == "plot":
        script = f"""% MATLAB Script to plot golf swing data
% Auto-generated by Golf Swing Analysis Suite

% Load data
data = load('{mat_file}');
t = data.times;

figure('Name', 'Golf Swing Analysis', 'Position', [100, 100, 1200, 800]);

subplot(2, 2, 1);
plot(t, rad2deg(data.joint_positions));
xlabel('Time (s)'); ylabel('Joint Angles (deg)');
title('Joint Angles'); grid on; legend('show');

subplot(2, 2, 2);
plot(t, rad2deg(data.joint_velocities));
xlabel('Time (s)'); ylabel('Joint Velocities (deg/s)');
title('Joint Velocities'); grid on;

subplot(2, 2, 3);
plot(t, data.joint_torques);
xlabel('Time (s)'); ylabel('Torques (Nm)'); title('Applied Torques'); grid on;

if isfield(data, 'club_head_speed')
    subplot(2, 2, 4);
    plot(t, data.club_head_speed);
    xlabel('Time (s)'); ylabel('Club Head Speed (mph)');
    title('Club Head Speed'); grid on;
    [peak_speed, peak_idx] = max(data.club_head_speed);
    hold on;
    plot(t(peak_idx), peak_speed, 'ro', 'MarkerSize', 10, 'LineWidth', 2);
    text(t(peak_idx), peak_speed, ...
        sprintf('  Peak: %.1f mph', peak_speed), ...
        'VerticalAlignment', 'bottom');
    hold off;
end

sgtitle('Golf Swing Biomechanical Analysis');
"""

    elif script_type == "analyze":
        script = f"""% MATLAB Script to analyze golf swing data
% Auto-generated by Golf Swing Analysis Suite

data = load('{mat_file}');
t = data.times;

fprintf('=== Golf Swing Analysis ===\\n\\n');
fprintf('Duration: %.2f s\\n', t(end) - t(1));
fprintf('Number of samples: %d\\n', length(t));
fprintf('Sample rate: %.1f Hz\\n', 1/mean(diff(t)));
fprintf('\\n');

if isfield(data, 'club_head_speed')
    [peak_speed, peak_idx] = max(data.club_head_speed);
    fprintf('Peak club head speed: %.1f mph at t=%.3f s\\n', peak_speed, t(peak_idx));
    fprintf('\\n');
end

fprintf('Range of Motion (degrees):\\n');
joint_angles_deg = rad2deg(data.joint_positions);
for i = 1:size(joint_angles_deg, 2)
    rom = max(joint_angles_deg(:, i)) - min(joint_angles_deg(:, i));
    fprintf('  Joint %d: %.1f deg\\n', i, rom);
end
fprintf('\\n');

if isfield(data, 'kinetic_energy') && isfield(data, 'potential_energy')
    max_ke = max(data.kinetic_energy);
    max_pe = max(data.potential_energy);
    fprintf('Maximum kinetic energy: %.2f J\\n', max_ke);
    fprintf('Maximum potential energy: %.2f J\\n', max_pe);
end
"""

    else:  # animate
        script = f"""% MATLAB Script to animate golf swing
% Auto-generated by Golf Swing Analysis Suite

data = load('{mat_file}');
t = data.times;
positions = data.joint_positions;

figure('Name', 'Golf Swing Animation', 'Position', [100, 100, 800, 600]);

for i = 1:length(t)
    clf;
    plot(positions(i, :), 'o-', 'LineWidth', 2, 'MarkerSize', 8);
    xlabel('Joint Index'); ylabel('Angle (rad)');
    title(sprintf('Time: %.3f s', t(i)));
    grid on;
    ylim([min(positions(:)), max(positions(:))]);
    drawnow;
    pause(0.016);
end
"""

    with open(output_path, "w") as f:
        f.write(script)
