function map = get_torque_to_polynomial_base()
%GET_TORQUE_TO_POLYNOMIAL_BASE Canonical torque-column -> polynomial-base map.
%
%   MAP = GET_TORQUE_TO_POLYNOMIAL_BASE() returns a containers.Map with
%   string keys (torque-column aliases) and string values (polynomial input
%   base names). The ordering matches the Python registry at
%   src/shared/python/motion_matching/control_names.py
%   (TORQUE_TO_POLYNOMIAL_BASE). Single source of truth for issue #4042.
%
%   Use KEYS(MAP) to retrieve the canonical ordered joint list — note that
%   containers.Map sorts keys; for ordered iteration prefer the cell array
%   returned by joint-name helpers.

    keys = { ...
        'LScapLogs_ActuatorTorqueX', 'LScapLogs_ActuatorTorqueY', ...
        'RScapLogs_ActuatorTorqueX', 'RScapLogs_ActuatorTorqueY', ...
        'LSLogs_ActuatorTorqueX',    'LSLogs_ActuatorTorqueY',    'LSLogs_ActuatorTorqueZ', ...
        'RSLogs_ActuatorTorqueX',    'RSLogs_ActuatorTorqueY',    'RSLogs_ActuatorTorqueZ', ...
        'SpineLogs_ActuatorTorqueX', 'SpineLogs_ActuatorTorqueY', ...
        'HipLogs_TranslationForceXInput', 'HipLogs_TranslationForceYInput', 'HipLogs_TranslationForceZInput', ...
        'HipLogs_HipTorqueXInput',  'HipLogs_HipTorqueYInput',  'HipLogs_HipTorqueZInput', ...
        'LScapTorqueXInput',        'LScapTorqueYInput', ...
        'RScapTorqueXInput',        'RScapTorqueYInput', ...
        'LSTorqueXInput',           'LSTorqueYInput',           'LSTorqueZInput', ...
        'RSTorqueXInput',           'RSTorqueYInput',           'RSTorqueZInput', ...
        'HipTorqueXInput',          'HipTorqueYInput',          'HipTorqueZInput' ...
    };

    values = { ...
        'LScapInputX', 'LScapInputY', ...
        'RScapInputX', 'RScapInputY', ...
        'LSInputX',    'LSInputY',    'LSInputZ', ...
        'RSInputX',    'RSInputY',    'RSInputZ', ...
        'SpineInputX', 'SpineInputY', ...
        'TranslationInputX', 'TranslationInputY', 'TranslationInputZ', ...
        'HipInputX',  'HipInputY',  'HipInputZ', ...
        'LScapInputX', 'LScapInputY', ...
        'RScapInputX', 'RScapInputY', ...
        'LSInputX',    'LSInputY',    'LSInputZ', ...
        'RSInputX',    'RSInputY',    'RSInputZ', ...
        'HipInputX',   'HipInputY',   'HipInputZ' ...
    };

    map = containers.Map(keys, values);
end
