function digest = manifest_sha256()
%MANIFEST_SHA256 sha256 of the canonical control-name manifest.
%
%   DIGEST = MANIFEST_SHA256() returns the lowercase-hex sha256 over the
%   same JSON-serialized payload used by
%   src/shared/python/motion_matching/control_names.manifest_sha256().
%
%   Computed on demand from the registry contents: any drift between the
%   MATLAB and Python definitions changes this digest, and the cross-tool
%   fixture test will fail. The expected current value is locked in
%   tests/fixtures/control_names_matlab.json.

    keys = { ...
        'LScapLogs_ActuatorTorqueX', 'LScapLogs_ActuatorTorqueY', ...
        'RScapLogs_ActuatorTorqueX', 'RScapLogs_ActuatorTorqueY', ...
        'LSLogs_ActuatorTorqueX',    'LSLogs_ActuatorTorqueY',    'LSLogs_ActuatorTorqueZ', ...
        'RSLogs_ActuatorTorqueX',    'RSLogs_ActuatorTorqueY',    'RSLogs_ActuatorTorqueZ', ...
        'SpineLogs_ActuatorTorqueX', 'SpineLogs_ActuatorTorqueY', ...
        'HipLogs_TranslationForceXInput', 'HipLogs_TranslationForceYInput', 'HipLogs_TranslationForceZInput', ...
        'HipLogs_HipTorqueXInput',  'HipLogs_HipTorqueYInput',  'HipLogs_HipTorqueZInput', ...
        'LScapTorqueXInput',        'LScapTorqueYInput', ...
        'RScapTorqueXInput',        'RScapTorqueYInput', ...
        'LSTorqueXInput',           'LSTorqueYInput',           'LSTorqueZInput', ...
        'RSTorqueXInput',           'RSTorqueYInput',           'RSTorqueZInput', ...
        'HipTorqueXInput',          'HipTorqueYInput',          'HipTorqueZInput' ...
    };
    values = { ...
        'LScapInputX', 'LScapInputY', 'RScapInputX', 'RScapInputY', ...
        'LSInputX',    'LSInputY',    'LSInputZ', ...
        'RSInputX',    'RSInputY',    'RSInputZ', ...
        'SpineInputX', 'SpineInputY', ...
        'TranslationInputX', 'TranslationInputY', 'TranslationInputZ', ...
        'HipInputX',  'HipInputY',  'HipInputZ', ...
        'LScapInputX', 'LScapInputY', 'RScapInputX', 'RScapInputY', ...
        'LSInputX',    'LSInputY',    'LSInputZ', ...
        'RSInputX',    'RSInputY',    'RSInputZ', ...
        'HipInputX',   'HipInputY',   'HipInputZ' ...
    };
    letters = control_names.get_coefficient_letters();

    % Build the same compact JSON Python emits.
    pairs = cell(1, numel(keys));
    for ii = 1:numel(keys)
        pairs{ii} = ['["' keys{ii} '","' values{ii} '"]'];
    end
    letters_json = ['["' strjoin(letters, '","') '"]'];
    payload = ['{"torque_to_polynomial_base":[' strjoin(pairs, ',') ...
               '],"coefficient_letters":' letters_json ...
               ',"n_coeffs_per_joint":7}'];

    md = java.security.MessageDigest.getInstance('SHA-256');
    bytes = md.digest(uint8(payload));
    digest = lower(reshape(dec2hex(typecast(bytes, 'uint8'), 2).', 1, []));
end
