"""Guard Tools child-copy headers against missing upstream counterparts."""

from __future__ import annotations

import os
import shutil
import subprocess  # nosec B404 - fixed git invocation, no shell
from pathlib import Path

import pytest

pytestmark = [pytest.mark.unit, pytest.mark.headless_safe]

_REPO_ROOT = Path(__file__).resolve().parents[3]
_SHARED_ROOT = _REPO_ROOT / "src" / "shared" / "python"
_HEADER = "# WARNING: DO NOT EDIT THIS FILE DIRECTLY."
_ISSUE_7249_SHARED_PATHS = {
    Path("ai/gui/assistant_panel.py"),
    Path("ai/gui/assistant_widgets.py"),
    Path("ai/tool_registry.py"),
    Path("compatibility.py"),
}
_ISSUE_7249_SHARED_DIRS = (Path("sidekick/agent"),)


def _candidate_tools_repos() -> list[tuple[Path, str]]:
    candidates: list[tuple[Path, str]] = []
    vendor_repo = _REPO_ROOT / "vendor" / "ud-tools"
    if (vendor_repo / ".git").exists():
        candidates.append((vendor_repo, "HEAD"))
    candidates.extend(
        (parent / "Tools", "origin/main")
        for parent in _REPO_ROOT.parents
        if (parent / "Tools" / ".git").exists()
    )
    return candidates


def _tools_shared_paths() -> set[str] | None:
    git_bin = shutil.which("git")
    if git_bin is None:
        return None
    for repo, ref in _candidate_tools_repos():
        result = subprocess.run(  # nosec B603 - fixed args, no shell
            [
                git_bin,
                "-C",
                str(repo),
                "ls-tree",
                "-r",
                "--name-only",
                ref,
                "src/shared/python",
            ],
            check=False,
            capture_output=True,
            text=True,
            timeout=30,
        )
        if result.returncode != 0:
            continue
        prefix = "src/shared/python/"
        paths = {
            line.removeprefix(prefix)
            for line in result.stdout.splitlines()
            if line.startswith(prefix)
        }
        if paths:
            return paths
    return None


def _is_tools_child_copy(path: Path) -> bool:
    try:
        first_line = path.read_text(encoding="utf-8").splitlines()[0]
    except (IndexError, OSError, UnicodeDecodeError):
        return False
    return first_line == _HEADER


def _run_git(*args: str) -> subprocess.CompletedProcess[str] | None:
    """Run a read-only Git command from the repository root."""
    git_bin = shutil.which("git")
    if git_bin is None:
        return None
    return subprocess.run(  # nosec B603 - fixed executable, no shell
        [git_bin, *args],
        cwd=str(_REPO_ROOT),
        check=False,
        capture_output=True,
        text=True,
        timeout=30,
    )


def _merge_base_with_main() -> str | None:
    """Return the branch merge base used for PR ownership enforcement."""
    result = _run_git("merge-base", "HEAD", "origin/main")
    if result is None or result.returncode != 0:
        return None
    merge_base = result.stdout.strip()
    return merge_base or None


def _changed_shared_python_paths(base: str) -> list[Path]:
    """Return non-deleted shared Python paths changed since ``base``."""
    result = _run_git(
        "diff",
        "--name-only",
        "--diff-filter=ACMRT",
        f"{base}...HEAD",
        "--",
        "src/shared/python",
    )
    assert result is not None and result.returncode == 0, (
        "Unable to inspect shared-file changes for child-copy enforcement"
    )
    prefix = "src/shared/python/"
    return [
        Path(line.removeprefix(prefix))
        for line in result.stdout.splitlines()
        if line.startswith(prefix) and line.endswith(".py")
    ]


def _base_revision_is_tools_child_copy(base: str, relative: Path) -> bool:
    """Return whether ``relative`` carried the child-copy header at ``base``."""
    source_path = f"src/shared/python/{relative.as_posix()}"
    result = _run_git("show", f"{base}:{source_path}")
    if result is None or result.returncode != 0:
        return False
    first_line = result.stdout.partition("\n")[0]
    return first_line == _HEADER


def test_tools_child_copy_headers_have_tools_counterparts() -> None:
    """Headered #7249 sync files must map to existing Tools files."""
    tools_paths = _tools_shared_paths()
    if tools_paths is None:
        pytest.skip("Tools checkout is unavailable for child-copy counterpart check")

    missing: list[str] = []
    for path in sorted(_SHARED_ROOT.rglob("*.py")):
        relative = path.relative_to(_SHARED_ROOT)
        in_scope = relative in _ISSUE_7249_SHARED_PATHS or any(
            relative.is_relative_to(root) for root in _ISSUE_7249_SHARED_DIRS
        )
        if not in_scope or not _is_tools_child_copy(path):
            continue
        if relative.as_posix() not in tools_paths:
            missing.append(relative.as_posix())

    assert not missing, (
        "Shared Python files with the Tools child-copy header must have a "
        "same-relative-path counterpart in Tools. Move canonical code to Tools "
        "before marking it as a synchronized child copy.\n\n"
        "Missing counterparts:\n  " + "\n  ".join(missing)
    )


def test_current_branch_does_not_edit_tools_child_copies() -> None:
    """PRs must change canonical Tools source, not existing UD child copies."""
    base = _merge_base_with_main()
    if base is None:
        assert not os.environ.get("CI"), (
            "origin/main is required in CI for child-copy diff enforcement"
        )
        pytest.skip("origin/main is unavailable for child-copy diff enforcement")

    offenders = [
        relative.as_posix()
        for relative in _changed_shared_python_paths(base)
        if _base_revision_is_tools_child_copy(base, relative)
        or _is_tools_child_copy(_SHARED_ROOT / relative)
    ]

    assert not offenders, (
        "This branch directly modifies Tools-owned child copies in "
        "UpstreamDrift. Make each change in D-sorganization/Tools, merge or "
        "pin that canonical revision, and update only vendor/ud-tools here. "
        "Deleting a migrated child copy remains allowed.\n\n"
        "Direct child-copy edits:\n  " + "\n  ".join(offenders)
    )
