"""Guard Tools child-copy headers against missing upstream counterparts."""

from __future__ import annotations

import shutil
import subprocess  # nosec B404 - fixed git invocation, no shell
from pathlib import Path

import pytest

pytestmark = [pytest.mark.unit, pytest.mark.headless_safe]

_REPO_ROOT = Path(__file__).resolve().parents[3]
_SHARED_ROOT = _REPO_ROOT / "src" / "shared" / "python"
_HEADER = "# WARNING: DO NOT EDIT THIS FILE DIRECTLY."
_ISSUE_7249_SHARED_PATHS = {
    Path("ai/gui/assistant_panel.py"),
    Path("ai/gui/assistant_widgets.py"),
    Path("ai/tool_registry.py"),
    Path("compatibility.py"),
}
_ISSUE_7249_SHARED_DIRS = (Path("sidekick/agent"),)


def _candidate_tools_repos() -> list[tuple[Path, str]]:
    candidates: list[tuple[Path, str]] = []
    vendor_repo = _REPO_ROOT / "vendor" / "ud-tools"
    if (vendor_repo / ".git").exists():
        candidates.append((vendor_repo, "HEAD"))
    candidates.extend(
        (parent / "Tools", "origin/main")
        for parent in _REPO_ROOT.parents
        if (parent / "Tools" / ".git").exists()
    )
    return candidates


def _tools_shared_paths() -> set[str] | None:
    git_bin = shutil.which("git")
    if git_bin is None:
        return None
    for repo, ref in _candidate_tools_repos():
        result = subprocess.run(  # nosec B603 - fixed args, no shell
            [
                git_bin,
                "-C",
                str(repo),
                "ls-tree",
                "-r",
                "--name-only",
                ref,
                "src/shared/python",
            ],
            check=False,
            capture_output=True,
            text=True,
            timeout=30,
        )
        if result.returncode != 0:
            continue
        prefix = "src/shared/python/"
        paths = {
            line.removeprefix(prefix)
            for line in result.stdout.splitlines()
            if line.startswith(prefix)
        }
        if paths:
            return paths
    return None


def _is_tools_child_copy(path: Path) -> bool:
    try:
        first_line = path.read_text(encoding="utf-8").splitlines()[0]
    except (IndexError, OSError, UnicodeDecodeError):
        return False
    return first_line == _HEADER


def test_tools_child_copy_headers_have_tools_counterparts() -> None:
    """Headered #7249 sync files must map to existing Tools files."""
    tools_paths = _tools_shared_paths()
    if tools_paths is None:
        pytest.skip("Tools checkout is unavailable for child-copy counterpart check")

    missing: list[str] = []
    for path in sorted(_SHARED_ROOT.rglob("*.py")):
        relative = path.relative_to(_SHARED_ROOT)
        in_scope = relative in _ISSUE_7249_SHARED_PATHS or any(
            relative.is_relative_to(root) for root in _ISSUE_7249_SHARED_DIRS
        )
        if not in_scope or not _is_tools_child_copy(path):
            continue
        if relative.as_posix() not in tools_paths:
            missing.append(relative.as_posix())

    assert not missing, (
        "Shared Python files with the Tools child-copy header must have a "
        "same-relative-path counterpart in Tools. Move canonical code to Tools "
        "before marking it as a synchronized child copy.\n\n"
        "Missing counterparts:\n  " + "\n  ".join(missing)
    )
