"""Club-only matching contracts (epic #10602)."""

from __future__ import annotations

from .acceptance import (
    ClubOnlyAcceptanceVerdict,
    ClubOnlyResidualReport,
    ClubOnlyStatuses,
    evaluate_club_only_acceptance,
    normalized_orientation_error,
    normalized_position_error,
)
from .adapters import club_target_to_observation, observation_to_club_target
from .ambiguity import (
    AmbiguityStatus,
    AmbiguityVerdict,
    CandidateScore,
    assess_ambiguity,
)
from .constrained_ik import (
    ConstrainedIkRequest,
    ConstrainedIkResult,
    IkBackendCapabilities,
    IkFailureReason,
    IkSolverKind,
    UnsupportedConstraintError,
    assert_backend_supports,
    capabilities_for,
    generate_posture_branches,
    run_constrained_ik_seeds,
)
from .hand_geometry import (
    GolferHandedness,
    ModelHandFrameOffsets,
    resolve_hand_frame_offsets,
)
from .hub_accounting import HubMode, account_external_hub_work, hub_variant_id
from .match_errors import ClubMatchErrorReport, separate_plane_and_3d_errors
from .match_matrix import (
    MATCH_SCHEMA,
    PENDULUM_MATCH_MODELS,
    MatchMatrixOutcome,
    PendulumMatchMatrix,
    build_pendulum_match_matrix,
)
from .match_matrix import evidence_payload as pendulum_match_evidence_payload
from .observation import (
    OBSERVATION_SCHEMA,
    ClubObservation,
    ClubObservationKinematics,
    ClubObservationProvenance,
    ComponentMask,
    ComponentStatus,
    DerivationMetadata,
    ObservationEvent,
    ResampleRecord,
    UncertaintyMetadata,
    build_calibrated_observation_fixture,
    interpolate_observation,
    load_observation_fixture_pack,
    orientation_residual_so3,
    scored_component_subset,
)
from .pendulum_match import (
    PendulumMatchRequest,
    PendulumMatchResult,
    map_seed_to_pendulum_q0,
    match_club_pendulum,
    reject_reconstruction_as_club_evidence,
)
from .priors import PRIOR_SCHEMA, GolfPlausibilityPriors, PriorAssumption
from .profiles import (
    PROFILE_SCHEMA,
    ClubOnlyProfile,
    ObjectiveRule,
    ObservationProfile,
    PhysicalProfile,
    PlausibilityProfile,
    build_roster_profiles,
    evidence_payload,
    get_club_only_profile,
)
from .replay_package import (
    REPLAY_SCHEMA,
    ClubPendulumReplayPackage,
    build_replay_package,
)
from .retrieval import (
    LibraryEntry,
    ObservableClubDescriptor,
    RigidPlacement,
    build_observable_descriptor,
    retrieve_starting_seeds,
)
from .seeds import (
    SEED_SCHEMA,
    CandidateSeed,
    SeedCache,
    StartingGuessReport,
    build_starting_guess_report,
    geometry_content_hash,
    profile_content_hash,
)
from .seeds import evidence_payload as starting_guess_evidence_payload
from .workbook_identity import (
    ALIAS_SHEETS,
    CANONICAL_TRIAL_SHEETS,
    CLUB_DATA_SHA256,
    EVENT_AUTHORITY,
    FRAME_AUTHORITY,
    IDENTITY_SCHEMA,
    NATIVE_SAMPLE_RATE_HZ,
    ORIENTATION_AXIS_POLICY,
    UNIT_AUTHORITY,
    WIFFLE_PROV1_SHA256,
    ClubWorkbookIdentity,
    TrialRecord,
    WorkbookManifest,
    build_club_workbook_identity,
    count_numeric_samples,
    read_sheet_event_samples,
    verify_workbook_hash,
)

__all__ = [
    "ALIAS_SHEETS",
    "AmbiguityStatus",
    "AmbiguityVerdict",
    "CANONICAL_TRIAL_SHEETS",
    "CLUB_DATA_SHA256",
    "CandidateScore",
    "CandidateSeed",
    "ClubMatchErrorReport",
    "ClubOnlyAcceptanceVerdict",
    "ClubOnlyProfile",
    "ClubOnlyResidualReport",
    "ClubOnlyStatuses",
    "ClubObservation",
    "ClubObservationKinematics",
    "ClubObservationProvenance",
    "ClubPendulumReplayPackage",
    "ClubWorkbookIdentity",
    "ComponentMask",
    "ComponentStatus",
    "ConstrainedIkRequest",
    "ConstrainedIkResult",
    "DerivationMetadata",
    "EVENT_AUTHORITY",
    "FRAME_AUTHORITY",
    "GolferHandedness",
    "GolfPlausibilityPriors",
    "HubMode",
    "IDENTITY_SCHEMA",
    "IkBackendCapabilities",
    "IkFailureReason",
    "IkSolverKind",
    "LibraryEntry",
    "MATCH_SCHEMA",
    "MatchMatrixOutcome",
    "ModelHandFrameOffsets",
    "NATIVE_SAMPLE_RATE_HZ",
    "OBSERVATION_SCHEMA",
    "ORIENTATION_AXIS_POLICY",
    "ObjectiveRule",
    "ObservableClubDescriptor",
    "ObservationEvent",
    "ObservationProfile",
    "PENDULUM_MATCH_MODELS",
    "PRIOR_SCHEMA",
    "PROFILE_SCHEMA",
    "PendulumMatchMatrix",
    "PendulumMatchRequest",
    "PendulumMatchResult",
    "PhysicalProfile",
    "PlausibilityProfile",
    "PriorAssumption",
    "REPLAY_SCHEMA",
    "ResampleRecord",
    "RigidPlacement",
    "SEED_SCHEMA",
    "SeedCache",
    "StartingGuessReport",
    "TrialRecord",
    "UNIT_AUTHORITY",
    "UncertaintyMetadata",
    "UnsupportedConstraintError",
    "WIFFLE_PROV1_SHA256",
    "WorkbookManifest",
    "account_external_hub_work",
    "assert_backend_supports",
    "assess_ambiguity",
    "build_calibrated_observation_fixture",
    "build_club_workbook_identity",
    "build_observable_descriptor",
    "build_pendulum_match_matrix",
    "build_replay_package",
    "build_roster_profiles",
    "build_starting_guess_report",
    "capabilities_for",
    "club_target_to_observation",
    "count_numeric_samples",
    "evaluate_club_only_acceptance",
    "evidence_payload",
    "generate_posture_branches",
    "geometry_content_hash",
    "get_club_only_profile",
    "hub_variant_id",
    "interpolate_observation",
    "load_observation_fixture_pack",
    "map_seed_to_pendulum_q0",
    "match_club_pendulum",
    "normalized_orientation_error",
    "normalized_position_error",
    "observation_to_club_target",
    "orientation_residual_so3",
    "pendulum_match_evidence_payload",
    "profile_content_hash",
    "read_sheet_event_samples",
    "reject_reconstruction_as_club_evidence",
    "resolve_hand_frame_offsets",
    "retrieve_starting_seeds",
    "run_constrained_ik_seeds",
    "scored_component_subset",
    "separate_plane_and_3d_errors",
    "starting_guess_evidence_payload",
    "verify_workbook_hash",
]
