# WARNING: DO NOT EDIT THIS FILE DIRECTLY.
# This file is a child copy that shadows or shares code with the Tools repository.
# Canonical changes must be made in the Tools repository under src/shared/python/
# and synchronized back to UpstreamDrift. Direct edits here risk being lost.

"""Toast notification system for Golf Modeling Suite.

Provides non-blocking, auto-dismissing notifications that appear
at the bottom-right of the application window.

Usage:
    from src.shared.python.ui.toast import ToastManager, ToastType

    # Create manager attached to main window
    toast_manager = ToastManager(main_window)

    # Show notifications
    toast_manager.show_success("Operation completed!")
    toast_manager.show_error("Something went wrong")
    toast_manager.show_warning("Check your settings")
    toast_manager.show_info("Did you know...")
"""

from enum import Enum, auto
from typing import TYPE_CHECKING, Any
import weakref

from PyQt6.QtCore import QEvent, QObject, QPropertyAnimation, Qt, QTimer
from PyQt6.QtGui import QColor, QFont, QPainter, QPainterPath
from PyQt6.QtWidgets import (
    QGraphicsOpacityEffect,
    QHBoxLayout,
    QLabel,
    QWidget,
)

if TYPE_CHECKING:
    from PyQt6.QtWidgets import QMainWindow

# Import theme colors if available
try:
    from src.shared.python.theme import (  # type: ignore[attr-defined]
        Colors,
        Sizes,
        Weights,
        get_qfont,
    )

    THEME_AVAILABLE = True
except ImportError:
    THEME_AVAILABLE = False


class ToastType(Enum):
    """Types of toast notifications."""

    SUCCESS = auto()
    ERROR = auto()
    WARNING = auto()
    INFO = auto()


class Toast(QWidget):
    """Individual toast notification widget.

    A rounded, styled notification that fades in, stays visible,
    then fades out automatically.
    """

    # Toast dimensions
    MIN_WIDTH = 280
    MAX_WIDTH = 400
    PADDING = 16
    BORDER_RADIUS = 10

    # Animation durations (ms)
    FADE_IN_DURATION = 200
    FADE_OUT_DURATION = 300

    TYPE_NAMES: dict[ToastType, str] = {
        ToastType.SUCCESS: "Success",
        ToastType.ERROR: "Error",
        ToastType.WARNING: "Warning",
        ToastType.INFO: "Info",
    }

    def __init__(
        self,
        message: str,
        toast_type: ToastType = ToastType.INFO,
        duration: int = 4000,
        parent: QWidget | None = None,
    ) -> None:
        """Create a toast notification.

        Args:
            message: Text to display
            toast_type: Type of notification (affects color/icon)
            duration: How long to show (ms), 0 for persistent
            parent: Parent widget
        """
        if message is None:
            raise ValueError("message must be provided")
        super().__init__(parent)
        self.message = message
        self.toast_type = toast_type
        self.duration = duration
        self._is_dismissing: bool = False
        self._remaining_time: int | None = None
        self._hidden_by_deactivate: bool = False

        # Set up widget - frameless tool window without WindowStaysOnTopHint
        # so toasts do not float above other desktop applications
        self.setWindowFlags(Qt.WindowType.FramelessWindowHint | Qt.WindowType.Tool)
        self.setAttribute(Qt.WidgetAttribute.WA_TranslucentBackground)
        self.setAttribute(Qt.WidgetAttribute.WA_ShowWithoutActivating)

        # Indicate clickability
        self.setCursor(Qt.CursorShape.PointingHandCursor)

        # Create opacity effect for fade animations
        self.opacity_effect = QGraphicsOpacityEffect(self)
        self.opacity_effect.setOpacity(0.0)
        self.setGraphicsEffect(self.opacity_effect)

        # Animations
        self._fade_in_anim: QPropertyAnimation | None = None
        self._fade_out_anim: QPropertyAnimation | None = None
        self._dismiss_timer: QTimer | None = None

        # Set up layout
        self._setup_ui()

    def _setup_ui(self) -> None:
        """Set up the toast UI with leading icon and accessible type label."""
        layout = QHBoxLayout(self)
        layout.setContentsMargins(
            self.PADDING, self.PADDING, self.PADDING, self.PADDING
        )
        layout.setSpacing(10)

        # Leading icon label
        self.icon_label = QLabel(self._get_icon(), self)
        self.icon_label.setStyleSheet("color: #FFFFFF; background: transparent;")
        if THEME_AVAILABLE:
            icon_font = get_qfont(size=Sizes.MD, weight=Weights.BOLD)
        else:
            icon_font = QFont("Segoe UI", 11)
            icon_font.setWeight(QFont.Weight.Bold)
        self.icon_label.setFont(icon_font)
        self.icon_label.setAlignment(
            Qt.AlignmentFlag.AlignTop | Qt.AlignmentFlag.AlignLeft
        )

        type_word = self.TYPE_NAMES.get(self.toast_type, "Notification")
        self.icon_label.setAccessibleName(f"{type_word} icon")
        layout.addWidget(self.icon_label)

        # Message label
        self.label = QLabel(self.message, self)
        self.label.setWordWrap(True)
        # Account for icon width and spacing in min/max bounds
        self.label.setMinimumWidth(self.MIN_WIDTH - 2 * self.PADDING - 34)
        self.label.setMaximumWidth(self.MAX_WIDTH - 2 * self.PADDING - 34)

        # Style based on theme availability
        if THEME_AVAILABLE:
            font = get_qfont(size=Sizes.SM, weight=Weights.MEDIUM)
        else:
            font = QFont("Segoe UI", 9)
            font.setWeight(QFont.Weight.Medium)
        self.label.setFont(font)
        self.label.setStyleSheet("color: #FFFFFF; background: transparent;")

        layout.addWidget(self.label)

        # Screen reader accessibility (WCAG 1.4.1 non-color encoding)
        accessible_text = f"{type_word}: {self.message}"
        self.setAccessibleName(accessible_text)
        self.label.setAccessibleName(accessible_text)

        # Adjust size to content
        self.adjustSize()

    def _get_background_color(self) -> QColor:
        """Get background color based on toast type."""
        if THEME_AVAILABLE:
            colors = {
                ToastType.SUCCESS: Colors.SUCCESS,
                ToastType.ERROR: Colors.ERROR,
                ToastType.WARNING: Colors.WARNING,
                ToastType.INFO: Colors.BG_ELEVATED,
            }
        else:
            colors = {
                ToastType.SUCCESS: "#30D158",
                ToastType.ERROR: "#FF375F",
                ToastType.WARNING: "#FF9F0A",
                ToastType.INFO: "#2D2D2D",
            }
        return QColor(colors.get(self.toast_type, colors[ToastType.INFO]))

    def _get_icon(self) -> str:
        """Get icon character for toast type."""
        icons = {
            ToastType.SUCCESS: "\u2713",  # Checkmark
            ToastType.ERROR: "\u2717",  # X mark
            ToastType.WARNING: "\u26a0",  # Warning triangle
            ToastType.INFO: "\u2139",  # Info circle
        }
        return icons.get(self.toast_type, "")

    def paintEvent(self, event: Any) -> None:
        """Custom paint for rounded background."""
        painter = QPainter(self)
        painter.setRenderHint(QPainter.RenderHint.Antialiasing)

        # Draw rounded rectangle background
        path = QPainterPath()
        path.addRoundedRect(
            0.0,
            0.0,
            float(self.width()),
            float(self.height()),
            self.BORDER_RADIUS,
            self.BORDER_RADIUS,
        )

        painter.fillPath(path, self._get_background_color())
        painter.end()

    def mousePressEvent(self, event: Any) -> None:
        """Dismiss the toast when clicked."""
        self.dismiss()
        if hasattr(event, "accept"):
            event.accept()

    def enterEvent(self, event: Any) -> None:
        """Pause auto-dismiss timer on mouse hover."""
        super().enterEvent(event)
        if self._dismiss_timer is not None and self._dismiss_timer.isActive():
            rem = self._dismiss_timer.remainingTime()
            if rem > 0:
                self._remaining_time = rem
            self._dismiss_timer.stop()

    def leaveEvent(self, event: Any) -> None:
        """Resume auto-dismiss timer on mouse leave."""
        super().leaveEvent(event)
        if (
            self._remaining_time is not None
            and self._remaining_time > 0
            and not self._is_dismissing
        ):
            if self._dismiss_timer is None:
                self._dismiss_timer = QTimer(self)
                self._dismiss_timer.setSingleShot(True)
                self._dismiss_timer.timeout.connect(self.dismiss)
            self._dismiss_timer.start(max(200, self._remaining_time))
            self._remaining_time = None

    def show_animated(self) -> None:
        """Show the toast with fade-in animation."""
        self.show()

        # Fade in
        self._fade_in_anim = QPropertyAnimation(self.opacity_effect, b"opacity")
        self._fade_in_anim.setDuration(self.FADE_IN_DURATION)
        self._fade_in_anim.setStartValue(0.0)
        self._fade_in_anim.setEndValue(1.0)
        self._fade_in_anim.start()

        # Set up auto-dismiss if duration > 0
        if self.duration > 0:
            self._dismiss_timer = QTimer(self)
            self._dismiss_timer.setSingleShot(True)
            self._dismiss_timer.timeout.connect(self.dismiss)
            self._dismiss_timer.start(self.duration)

    def dismiss(self) -> None:
        """Dismiss the toast with fade-out animation."""
        self._is_dismissing = True
        self._remaining_time = None
        if self._dismiss_timer:
            self._dismiss_timer.stop()
            self._dismiss_timer = None

        # Stop any running fade-in animation
        if self._fade_in_anim:
            self._fade_in_anim.stop()
            self._fade_in_anim = None

        self._fade_out_anim = QPropertyAnimation(self.opacity_effect, b"opacity")
        self._fade_out_anim.setDuration(self.FADE_OUT_DURATION)
        self._fade_out_anim.setStartValue(1.0)
        self._fade_out_anim.setEndValue(0.0)
        self._fade_out_anim.finished.connect(self._on_fade_out_finished)
        self._fade_out_anim.start()

    def _on_fade_out_finished(self) -> None:
        """Handle fade-out completion."""
        # Clean up animation references
        if self._fade_out_anim:
            self._fade_out_anim.stop()
            self._fade_out_anim = None
        self.hide()
        self.deleteLater()


class _ToastEventFilter(QObject):
    """Internal event filter installed on the parent window."""

    def __init__(self, manager: "ToastManager") -> None:
        super().__init__()
        self._manager = manager

    def eventFilter(self, watched: Any, event: Any) -> bool:
        return self._manager.eventFilter(watched, event)


class ToastManager:
    """Manages toast notifications for an application window.

    Handles positioning, stacking, and lifecycle of toast notifications.
    """

    # Spacing between toasts
    TOAST_SPACING = 10
    MARGIN_RIGHT = 20
    MARGIN_BOTTOM = 20
    MAX_VISIBLE_TOASTS = 4

    def __init__(self, parent: Any) -> None:
        """Create a toast manager.

        Args:
            parent: Window or widget to attach toasts to
        """
        if parent is None:
            raise ValueError("parent must be provided")

        self.parent = parent
        self.active_toasts: list[Toast] = []
        self.max_visible_toasts: int = self.MAX_VISIBLE_TOASTS

        self._event_filter = _ToastEventFilter(self)
        if hasattr(parent, "installEventFilter") and callable(
            parent.installEventFilter
        ):
            try:
                parent.installEventFilter(self._event_filter)
            except (AttributeError, RuntimeError, TypeError):
                pass

    def eventFilter(self, watched: Any, event: Any) -> bool:
        """Handle parent window movement, resizing, and activation state changes."""
        if watched is self.parent and event is not None:
            try:
                event_type = event.type()
                if event_type in (QEvent.Type.Move, QEvent.Type.Resize):
                    self.reposition_all()
                elif event_type in (QEvent.Type.WindowDeactivate, QEvent.Type.Hide):
                    for toast in self.active_toasts:
                        if toast.isVisible():
                            toast._hidden_by_deactivate = True
                            toast.hide()
                elif event_type in (QEvent.Type.WindowActivate, QEvent.Type.Show):
                    if hasattr(self.parent, "isVisible") and self.parent.isVisible():
                        self.reposition_all()
                        for toast in self.active_toasts:
                            if getattr(toast, "_hidden_by_deactivate", False):
                                toast._hidden_by_deactivate = False
                                toast.show()
                elif event_type == QEvent.Type.Close:
                    self.dismiss_all()
            except (AttributeError, RuntimeError):
                pass
        return False

    def reposition_all(self) -> None:
        """Reposition all active toasts relative to the parent window."""
        try:
            if (
                hasattr(self.parent, "isWindow")
                and not self.parent.isWindow()
                and hasattr(self.parent, "mapToGlobal")
            ):
                global_tl = self.parent.mapToGlobal(self.parent.rect().topLeft())
                right = global_tl.x() + self.parent.width() - 1
                bottom = global_tl.y() + self.parent.height() - 1
            else:
                parent_rect = self.parent.geometry()
                right = parent_rect.right()
                bottom = parent_rect.bottom()
        except (AttributeError, RuntimeError):
            return

        current_y_offset = self.MARGIN_BOTTOM
        for toast in self.active_toasts:
            if not toast.isVisible() and getattr(toast, "_is_dismissing", False):
                continue
            x = right - toast.width() - self.MARGIN_RIGHT
            y = bottom - toast.height() - current_y_offset
            toast.move(x, y)
            current_y_offset += toast.height() + self.TOAST_SPACING

    def _calculate_position(self, toast: Toast) -> tuple[int, int]:
        """Calculate position for a new toast.

        Args:
            toast: Toast to position

        Returns:
            Tuple of (x, y) coordinates
        """
        if toast is None:
            raise ValueError("toast must be provided")
        parent_rect = self.parent.geometry()

        # Start from bottom-right
        x = parent_rect.right() - toast.width() - self.MARGIN_RIGHT
        y = parent_rect.bottom() - toast.height() - self.MARGIN_BOTTOM

        # Stack above existing toasts
        for existing in self.active_toasts:
            if existing.isVisible() or getattr(
                existing, "_hidden_by_deactivate", False
            ):
                y -= existing.height() + self.TOAST_SPACING

        return x, y

    def _show_toast(self, message: str, toast_type: ToastType, duration: int) -> Toast:
        """Create and show a toast notification.

        Args:
            message: Text to display
            toast_type: Type of notification
            duration: Display duration in ms

        Returns:
            The created Toast widget
        """
        if message is None:
            raise ValueError("message must be provided")

        # Cap visible toasts (~4); dismiss oldest when limit is reached
        while len(self.active_toasts) >= self.max_visible_toasts:
            oldest = self.active_toasts.pop(0)
            oldest.dismiss()

        toast = Toast(message, toast_type, duration, parent=None)

        # Position the toast
        x, y = self._calculate_position(toast)
        toast.move(x, y)

        # Track the toast
        self.active_toasts.append(toast)

        # Reposition active toasts to ensure proper spacing
        self.reposition_all()

        # Clean up when dismissed
        toast_ref = weakref.ref(toast)

        def on_destroyed() -> None:
            """Remove the toast from the active list when it is destroyed."""
            t = toast_ref()
            if t is not None and t in self.active_toasts:
                self.active_toasts.remove(t)
                self.reposition_all()

        toast.destroyed.connect(on_destroyed)

        # Show with animation
        toast.show_animated()

        return toast

    def show_success(self, message: str, duration: int = 3000) -> Toast:
        """Show a success notification.

        Args:
            message: Success message
            duration: Display duration in ms

        Returns:
            The created Toast
        """
        return self._show_toast(message, ToastType.SUCCESS, duration)

    def show_error(self, message: str, duration: int = 5000) -> Toast:
        """Show an error notification.

        Args:
            message: Error message
            duration: Display duration in ms (longer for errors)

        Returns:
            The created Toast
        """
        return self._show_toast(message, ToastType.ERROR, duration)

    def show_warning(self, message: str, duration: int = 4000) -> Toast:
        """Show a warning notification.

        Args:
            message: Warning message
            duration: Display duration in ms

        Returns:
            The created Toast
        """
        return self._show_toast(message, ToastType.WARNING, duration)

    def show_info(self, message: str, duration: int = 3500) -> Toast:
        """Show an info notification.

        Args:
            message: Info message
            duration: Display duration in ms

        Returns:
            The created Toast
        """
        return self._show_toast(message, ToastType.INFO, duration)

    def dismiss_all(self) -> None:
        """Dismiss all active toasts."""
        for toast in self.active_toasts[:]:
            toast.dismiss()
        self.active_toasts.clear()


__all__ = ["Toast", "ToastManager", "ToastType"]
