function base = control_column_to_polynomial_base(columnName)
%CONTROL_COLUMN_TO_POLYNOMIAL_BASE  Map a manifest control column to a model base.
%
%   base = frame_search.control_column_to_polynomial_base(columnName)
%   returns the GolfSwing3D_Kinetic polynomial-input base variable name
%   (e.g. "LSInputX") for a manifest applied-control column name (e.g.
%   "LSLogs_ActuatorTorqueX"). The mapping mirrors the inverse table inside
%   run_frame_by_frame_torque_search/torqueColumnToPolynomialBase, but is
%   exposed as a package-level helper so candidate evaluation can build
%   workspace overrides without going through the runner.
%
%   Returns "" when the column has no known mapping. Callers must error
%   with an actionable message in that case (do not silently swallow).
%
%   Pure helper, no Simulink calls. Unit-testable.

    arguments
        columnName (1,1) string
    end

    mapping = struct( ...
        'LScapLogs_ActuatorTorqueX', 'LScapInputX', ...
        'LScapLogs_ActuatorTorqueY', 'LScapInputY', ...
        'RScapLogs_ActuatorTorqueX', 'RScapInputX', ...
        'RScapLogs_ActuatorTorqueY', 'RScapInputY', ...
        'LSLogs_ActuatorTorqueX', 'LSInputX', ...
        'LSLogs_ActuatorTorqueY', 'LSInputY', ...
        'LSLogs_ActuatorTorqueZ', 'LSInputZ', ...
        'RSLogs_ActuatorTorqueX', 'RSInputX', ...
        'RSLogs_ActuatorTorqueY', 'RSInputY', ...
        'RSLogs_ActuatorTorqueZ', 'RSInputZ', ...
        'SpineLogs_ActuatorTorqueX', 'SpineInputX', ...
        'SpineLogs_ActuatorTorqueY', 'SpineInputY', ...
        'HipLogs_TranslationForceXInput', 'TranslationInputX', ...
        'HipLogs_TranslationForceYInput', 'TranslationInputY', ...
        'HipLogs_TranslationForceZInput', 'TranslationInputZ', ...
        'HipLogs_HipTorqueXInput', 'HipInputX', ...
        'HipLogs_HipTorqueYInput', 'HipInputY', ...
        'HipLogs_HipTorqueZInput', 'HipInputZ');

    validName = matlab.lang.makeValidName(char(columnName));
    if isfield(mapping, validName)
        base = string(mapping.(validName));
    else
        base = "";
    end
end
