"""Render publication figures for the archived WSCG two-hand wrench audit."""

from __future__ import annotations

import json
from pathlib import Path

import matplotlib

matplotlib.use("Agg")
import matplotlib.pyplot as plt
import numpy as np

REPO_ROOT = Path(__file__).resolve().parents[3]
OUTPUT_ROOT = REPO_ROOT / "docs" / "research" / "proximal_distal_energy_transfer"
DATA_DIR = OUTPUT_ROOT / "data"
FIG_DIR = OUTPUT_ROOT / "figures"
COLORS = {
    "base": "#172B4D",
    "ztcf": "#007C91",
    "delta": "#B23A48",
    "force": "#D97706",
    "torque": "#7C3AED",
    "lead": "#006D77",
    "trail": "#BB3E03",
    "net": "#334155",
}


def _style() -> None:
    """Use portable core fonts so repeated vector panels stay phone-sized."""
    plt.rcParams.update(
        {
            "pdf.use14corefonts": True,
            "svg.hashsalt": "upstreamdrift-two-hand-wrench-audit-v2",
            "axes.unicode_minus": False,
            "path.simplify": True,
            "path.simplify_threshold": 1.0,
        }
    )


def _load() -> tuple[dict, dict[str, np.ndarray]]:
    with (DATA_DIR / "two_hand_wscg_analysis.json").open(encoding="utf-8") as stream:
        record = json.load(stream)
    return record, dict(np.load(DATA_DIR / "two_hand_wscg_analysis.npz"))


def _save(fig: plt.Figure, stem: str) -> None:
    fig.tight_layout()
    fig.savefig(
        FIG_DIR / f"{stem}.pdf",
        bbox_inches="tight",
        metadata={"CreationDate": None, "ModDate": None},
    )
    svg_path = FIG_DIR / f"{stem}.svg"
    fig.savefig(svg_path, bbox_inches="tight", metadata={"Date": None})
    svg_path.write_text(
        "\n".join(
            line.rstrip() for line in svg_path.read_text(encoding="utf-8").splitlines()
        )
        + "\n",
        encoding="utf-8",
    )
    plt.close(fig)


def _shade_negative(ax: plt.Axes, time: np.ndarray, values: np.ndarray) -> None:
    ax.fill_between(
        time,
        ax.get_ylim()[0],
        ax.get_ylim()[1],
        where=values < 0.0,
        color="#CBD5E1",
        alpha=0.35,
        zorder=-10,
        label="Negative Equivalent Couple",
    )


def fig_couple_decomposition(record: dict, arrays: dict[str, np.ndarray]) -> None:
    """Separate force-generated and applied-free-torque contributions."""
    fig, axes = plt.subplots(3, 1, figsize=(10.5, 8.2), sharex=True, sharey=True)
    labels = {"base": "BASE", "ztcf": "Pointwise ZTCF", "delta": "DELTA"}
    for ax, name in zip(axes, ("base", "ztcf", "delta"), strict=True):
        time = arrays[f"{name}__time"]
        couple = arrays[f"{name}__equivalent_couple"]
        ax.plot(time, couple, color=COLORS[name], lw=2.0, label="Equivalent Couple")
        ax.plot(
            time,
            arrays[f"{name}__force_moment"],
            color=COLORS["force"],
            lw=1.5,
            label="Contact-Force Moment",
        )
        ax.plot(
            time,
            arrays[f"{name}__free_torque"],
            color=COLORS["torque"],
            lw=1.3,
            ls="--",
            label="Applied Free Torque",
        )
        ax.axhline(0.0, color="black", lw=0.8)
        late = record["cases"][name]["crossings"]["late"]["time_s"]
        ax.axvline(late, color="black", lw=0.9, ls=":")
        ax.text(0.006, 0.88, labels[name], transform=ax.transAxes, fontweight="bold")
        _shade_negative(ax, time, couple)
        ax.grid(alpha=0.2)
    axes[1].set_ylabel("Midpoint Couple About Model +z [N m]")
    axes[-1].set_xlabel("Source-Trace Time [s]")
    axes[0].legend(ncol=3, fontsize=8, loc="upper right")
    fig.suptitle("The Negative ZTCF Couple Is Generated by Contact Forces")
    _save(fig, "fig_two_hand_couple_decomposition")


def fig_local_forces(arrays: dict[str, np.ndarray]) -> None:
    """Show axial and normal components for BASE and pointwise ZTCF."""
    fig, axes = plt.subplots(2, 2, figsize=(11.0, 7.2), sharex=True)
    for row, name in enumerate(("base", "ztcf")):
        time = arrays[f"{name}__time"]
        for column, component in enumerate(("axial", "normal")):
            ax = axes[row, column]
            ax.plot(
                time,
                arrays[f"{name}__lead_{component}"],
                color=COLORS["lead"],
                label="Lead Hand",
            )
            ax.plot(
                time,
                arrays[f"{name}__trail_{component}"],
                color=COLORS["trail"],
                label="Trail Hand",
            )
            ax.axhline(0.0, color="black", lw=0.8)
            ax.grid(alpha=0.2)
            ax.set_title(
                f"{'BASE' if name == 'base' else 'Pointwise ZTCF'} — "
                f"{component.title()}"
            )
    axes[0, 0].set_ylabel("Local Hand Force [N]")
    axes[1, 0].set_ylabel("Local Hand Force [N]")
    axes[1, 0].set_xlabel("Source-Trace Time [s]")
    axes[1, 1].set_xlabel("Source-Trace Time [s]")
    axes[0, 0].legend(fontsize=8)
    fig.suptitle("Opposing Local Hand Forces Persist in Pointwise ZTCF")
    _save(fig, "fig_two_hand_local_force_components")


def fig_force_cancellation(arrays: dict[str, np.ndarray]) -> None:
    """Contrast force resultant with the antisymmetric contact mode."""
    fig, axes = plt.subplots(2, 1, figsize=(10.5, 6.8), sharex=True)
    for name, style in (("base", "-"), ("ztcf", "--")):
        time = arrays[f"{name}__time"]
        lead = arrays[f"{name}__lead_force"]
        trail = arrays[f"{name}__trail_force"]
        net = np.linalg.norm(arrays[f"{name}__resultant"], axis=1)
        opposed = np.linalg.norm(0.5 * (lead - trail), axis=1)
        label = "BASE" if name == "base" else "Pointwise ZTCF"
        axes[0].plot(
            time, net, ls=style, color=COLORS["net"], label=f"{label} Resultant"
        )
        axes[0].plot(
            time,
            opposed,
            ls=style,
            color=COLORS[name],
            label=f"{label} Opposed Mode",
        )
        axes[1].plot(
            time,
            arrays[f"{name}__equivalent_couple"],
            ls=style,
            color=COLORS[name],
            label=label,
        )
    axes[0].set_ylabel("Force Magnitude [N]")
    axes[1].set_ylabel("Equivalent Couple [N m]")
    axes[1].set_xlabel("Source-Trace Time [s]")
    axes[1].axhline(0.0, color="black", lw=0.8)
    for ax in axes:
        ax.grid(alpha=0.2)
        ax.legend(fontsize=8, ncol=2)
    fig.suptitle("A Large Opposed-Force Mode Can Coexist With a Modest Resultant")
    _save(fig, "fig_two_hand_force_cancellation")


def fig_pose_force_montage(arrays: dict[str, np.ndarray]) -> None:
    """Render six 3-D grip poses with hand-force vectors."""
    time = arrays["base__time"]
    selected_times = (0.00, 0.10, 0.18, 0.215, 0.270, 0.280)
    indices = [int(np.argmin(np.abs(time - selected))) for selected in selected_times]
    fig = plt.figure(figsize=(11.0, 7.4))
    for panel, index in enumerate(indices, start=1):
        ax = fig.add_subplot(2, 3, panel, projection="3d")
        lead = arrays["base__lead_position"][index]
        trail = arrays["base__trail_position"][index]
        midpoint = arrays["base__midpoint"][index]
        lead_force = arrays["base__lead_force"][index]
        trail_force = arrays["base__trail_force"][index]
        force_scale = 0.00011
        ax.plot(
            [lead[0], trail[0]],
            [lead[1], trail[1]],
            [lead[2], trail[2]],
            color="black",
            lw=4,
        )
        for point, force, color in (
            (lead, lead_force, COLORS["lead"]),
            (trail, trail_force, COLORS["trail"]),
        ):
            ax.quiver(
                *point,
                *(force * force_scale),
                color=color,
                arrow_length_ratio=0.16,
                linewidth=1.5,
            )
        couple = arrays["base__equivalent_couple"][index]
        ax.scatter(*midpoint, color=COLORS["net"], s=16)
        ax.set_title(f"t = {time[index]:.3f} s; Couple = {couple:.1f} N m", fontsize=9)
        center = midpoint
        radius = 0.09
        ax.set_xlim(center[0] - radius, center[0] + radius)
        ax.set_ylim(center[1] - radius, center[1] + radius)
        ax.set_zlim(center[2] - radius, center[2] + radius)
        ax.set_xticks([])
        ax.set_yticks([])
        ax.set_zticks([])
        ax.set_box_aspect((1, 1, 1))
        ax.view_init(elev=19, azim=-52)
    fig.suptitle("Three-Dimensional View of the Archived Two-Hand Force System")
    _save(fig, "fig_two_hand_force_pose_montage")


def fig_geometry_sweep(record: dict, arrays: dict[str, np.ndarray]) -> None:
    """Show spacing and relative-orientation dependence at peak negative ZTCF."""
    fig, axes = plt.subplots(1, 2, figsize=(11.0, 4.5))
    scale = arrays["sweep__spacing_scale"]
    spacing = arrays["sweep__spacing_force_moment_nm"]
    axes[0].plot(scale, spacing, color=COLORS["ztcf"], lw=2)
    axes[0].axhline(0.0, color="black", lw=0.8)
    axes[0].axvline(1.0, color="black", lw=0.8, ls=":")
    axes[0].set_xlabel("Grip-Separation Scale")
    axes[0].set_ylabel("Contact-Force Moment [N m]")
    axes[0].set_title("Linear Dependence on Contact Separation")
    angle = arrays["sweep__orientation_deg"]
    axes[1].plot(
        angle,
        arrays["sweep__orientation_force_moment_nm"],
        color=COLORS["force"],
        lw=2,
        label="Rotate Contacts Only",
    )
    axes[1].plot(
        angle,
        arrays["sweep__co_rotated_force_moment_nm"],
        color=COLORS["ztcf"],
        lw=1.4,
        ls="--",
        label="Rigidly Co-Rotate Contacts and Forces",
    )
    axes[1].axhline(0.0, color="black", lw=0.8)
    axes[1].set_xlabel("In-Plane Orientation Offset [deg]")
    axes[1].set_ylabel("Contact-Force Moment [N m]")
    axes[1].set_title("Relative Orientation, Not Global Pose, Controls Sign")
    axes[1].legend(fontsize=8)
    for ax in axes:
        ax.grid(alpha=0.2)
    source_time = record["geometry_sweep"]["source_time_s"]
    fig.suptitle(
        f"Geometric Counterfactuals at Peak Negative ZTCF (t = {source_time:.4f} s)"
    )
    _save(fig, "fig_two_hand_geometry_sweep")


def fig_power_decomposition(arrays: dict[str, np.ndarray]) -> None:
    """Separate rigid wrench power from relative-contact deformation power."""
    time = arrays["ztcf__time"]
    fig, axes = plt.subplots(2, 1, figsize=(10.5, 6.8), sharex=True)
    axes[0].plot(
        time,
        arrays["ztcf__contact_force_power"],
        color=COLORS["ztcf"],
        lw=1.8,
        label="Direct Contact-Force Power",
    )
    axes[0].plot(
        time,
        arrays["ztcf__rigid_force_power"],
        color=COLORS["force"],
        lw=1.2,
        ls="--",
        label="Rigid Wrench Reduction",
    )
    axes[0].plot(
        time,
        arrays["ztcf__deformation_power"],
        color=COLORS["torque"],
        lw=1.2,
        label="Relative-Contact Remainder",
    )
    axes[0].set_ylabel("Power [W]")
    axes[0].legend(fontsize=8, ncol=3)
    axes[1].plot(
        time,
        arrays["ztcf__equivalent_couple"],
        color=COLORS["ztcf"],
        label="Equivalent Couple",
    )
    speed_axis = axes[1].twinx()
    speed_axis.plot(
        time,
        arrays["ztcf__clubhead_speed_mph"],
        color=COLORS["net"],
        ls="--",
        label="Clubhead Speed",
    )
    axes[1].axhline(0.0, color="black", lw=0.8)
    axes[1].set_ylabel("Equivalent Couple [N m]")
    speed_axis.set_ylabel("Clubhead Speed [mph]")
    axes[1].set_xlabel("Source-Trace Time [s]")
    handles = axes[1].lines[:1] + speed_axis.lines
    axes[1].legend(handles, [line.get_label() for line in handles], fontsize=8)
    for ax in axes:
        ax.grid(alpha=0.2)
    fig.suptitle("Negative Couple Sign Does Not Alone Determine Energy-Transfer Sign")
    _save(fig, "fig_two_hand_power_decomposition")


def fig_reversal_sensitivity(record: dict) -> None:
    """Display crossing times and their downsampling sensitivity."""
    fig, axes = plt.subplots(1, 2, figsize=(11.0, 4.4))
    names = ("base", "ztcf", "delta")
    labels = ("BASE", "Pointwise ZTCF", "DELTA")
    times = [record["cases"][name]["crossings"]["late"]["time_s"] for name in names]
    axes[0].bar(
        labels, np.asarray(times) * 1000.0, color=[COLORS[name] for name in names]
    )
    axes[0].set_ylabel("Late Reversal Time [ms]")
    axes[0].set_title("BASE and ZTCF Reverse Within 0.81 ms")
    for name, label in zip(names, labels, strict=True):
        sensitivity = record["cases"][name]["late_crossing_resampling"]["estimates"]
        steps = np.array([row["effective_step_s"] for row in sensitivity]) * 1000.0
        reference = record["cases"][name]["crossings"]["late"]["time_s"]
        error = (
            np.array([row["late_crossing_s"] for row in sensitivity]) - reference
        ) * 1e6
        axes[1].scatter(steps, error, s=18, alpha=0.75, label=label, color=COLORS[name])
    axes[1].axhline(0.0, color="black", lw=0.8)
    axes[1].set_xlabel("Effective Sample Step [ms]")
    axes[1].set_ylabel("Crossing-Time Shift [microseconds]")
    axes[1].set_title("Interpolation Is Stable Under 20-Fold Downsampling")
    axes[1].legend(fontsize=8)
    for ax in axes:
        ax.grid(alpha=0.2, axis="y")
    fig.suptitle("Late Equivalent-Couple Reversal Timing")
    _save(fig, "fig_two_hand_reversal_sensitivity")


def fig_reference_transport() -> None:
    """Clarify that wrench equivalence, not the moment value, is invariant."""
    fig, axes = plt.subplots(1, 2, figsize=(10.5, 4.5))
    positions = np.array([[-0.8, 0.0], [0.8, 0.0]])
    forces = np.array([[0.4, 1.2], [-0.1, -0.5]])
    resultant = forces.sum(axis=0)
    references = (np.array([0.0, 0.0]), np.array([0.55, -0.35]))
    for ax, reference, label in zip(
        axes, references, ("Reference A", "Reference B"), strict=True
    ):
        ax.plot(positions[:, 0], positions[:, 1], color="black", lw=4)
        for point, force, color in zip(
            positions, forces, (COLORS["lead"], COLORS["trail"]), strict=True
        ):
            ax.arrow(
                *point, *force, color=color, width=0.015, length_includes_head=True
            )
        ax.scatter(*reference, color=COLORS["net"], s=38, zorder=5)
        ax.arrow(
            *reference,
            *resultant,
            color=COLORS["force"],
            width=0.012,
            length_includes_head=True,
        )
        offsets = positions - reference
        moment = np.sum(offsets[:, 0] * forces[:, 1] - offsets[:, 1] * forces[:, 0])
        ax.text(
            0.04, 0.93, f"{label}: M = {moment:.2f}", transform=ax.transAxes, va="top"
        )
        ax.set_xlim(-1.2, 1.5)
        ax.set_ylim(-0.8, 1.7)
        ax.set_aspect("equal")
        ax.grid(alpha=0.2)
        ax.set_xlabel("x")
        ax.set_ylabel("y")
    fig.suptitle("Reference Transport Changes the Moment but Preserves the Wrench")
    _save(fig, "fig_two_hand_reference_transport")


def main() -> None:
    """Render every two-hand audit figure as PDF and SVG."""
    _style()
    FIG_DIR.mkdir(parents=True, exist_ok=True)
    record, arrays = _load()
    fig_couple_decomposition(record, arrays)
    fig_local_forces(arrays)
    fig_force_cancellation(arrays)
    fig_pose_force_montage(arrays)
    fig_geometry_sweep(record, arrays)
    fig_power_decomposition(arrays)
    fig_reversal_sensitivity(record)
    fig_reference_transport()


if __name__ == "__main__":
    main()
