function tab_handles = tab1_model_setup(parent_tab, app_handles)
% TAB1_MODEL_SETUP - Initialize Model Setup Tab
%
% This tab will provide model configuration and Simscape simulation
% interface. Currently implemented as a placeholder.
%
% Inputs:
%   parent_tab   - Handle to the tab UI container
%   app_handles  - Main application handles structure
%
% Returns:
%   tab_handles  - Handles structure for this tab

%% Initialize Tab Handles
tab_handles = struct();
tab_handles.parent = parent_tab;

%% Create UI Layout
% Main container
main_panel = uipanel('Parent', parent_tab, ...
    'Units', 'normalized', ...
    'Position', [0, 0, 1, 1], ...
    'BorderType', 'none', ...
    'BackgroundColor', [0.94, 0.94, 0.94]);

% Title panel
title_panel = uipanel('Parent', main_panel, ...
    'Units', 'normalized', ...
    'Position', [0.1, 0.7, 0.8, 0.2], ...
    'BackgroundColor', [0.9, 0.95, 1], ...
    'Title', 'Tab 1: Model Setup & Simulation', ...
    'FontSize', 14, ...
    'FontWeight', 'bold');

% Info text
uicontrol('Parent', title_panel, ...
    'Style', 'text', ...
    'String', {'This tab will provide:', '', ...
    '• Model parameter configuration', ...
    '• Initial conditions setup', ...
    '• Simscape Multibody simulation', ...
    '• Live 3D animation preview', ...
    '• Data export to Tab 2 for ZTCF analysis'}, ...
    'FontSize', 11, ...
    'Units', 'normalized', ...
    'Position', [0.05, 0.05, 0.9, 0.9], ...
    'BackgroundColor', [0.9, 0.95, 1], ...
    'HorizontalAlignment', 'left');

% Status panel
status_panel = uipanel('Parent', main_panel, ...
    'Units', 'normalized', ...
    'Position', [0.1, 0.4, 0.8, 0.25], ...
    'BackgroundColor', [1, 1, 0.9], ...
    'Title', 'Implementation Status', ...
    'FontSize', 12, ...
    'FontWeight', 'bold');

uicontrol('Parent', status_panel, ...
    'Style', 'text', ...
    'String', {'STATUS: Placeholder - To Be Implemented', '', ...
    'This tab is part of Phase 3 of the tabbed GUI implementation.', ...
    '', ...
    'For now, use your existing simulation scripts to generate', ...
    'data, then proceed directly to Tab 2 or Tab 3.'}, ...
    'FontSize', 10, ...
    'Units', 'normalized', ...
    'Position', [0.05, 0.05, 0.9, 0.9], ...
    'BackgroundColor', [1, 1, 0.9], ...
    'HorizontalAlignment', 'left');

% Placeholder controls panel
controls_panel = uipanel('Parent', main_panel, ...
    'Units', 'normalized', ...
    'Position', [0.1, 0.1, 0.8, 0.25], ...
    'BackgroundColor', [0.95, 0.95, 0.95], ...
    'Title', 'Quick Actions', ...
    'FontSize', 11, ...
    'FontWeight', 'bold');

% Placeholder buttons
uicontrol('Parent', controls_panel, ...
    'Style', 'pushbutton', ...
    'String', 'Load Model Parameters...', ...
    'FontSize', 10, ...
    'Units', 'normalized', ...
    'Position', [0.1, 0.55, 0.35, 0.30], ...
    'Enable', 'off', ...
    'TooltipString', 'To be implemented');

uicontrol('Parent', controls_panel, ...
    'Style', 'pushbutton', ...
    'String', 'Run Simulation', ...
    'FontSize', 10, ...
    'FontWeight', 'bold', ...
    'Units', 'normalized', ...
    'Position', [0.55, 0.55, 0.35, 0.30], ...
    'Enable', 'off', ...
    'TooltipString', 'To be implemented');

uicontrol('Parent', controls_panel, ...
    'Style', 'text', ...
    'String', 'These controls will be implemented in Phase 3', ...
    'FontSize', 9, ...
    'Units', 'normalized', ...
    'Position', [0.1, 0.05, 0.8, 0.40], ...
    'BackgroundColor', [0.95, 0.95, 0.95], ...
    'HorizontalAlignment', 'center');

% Store panels
tab_handles.main_panel = main_panel;

%% Set up Refresh and Cleanup Callbacks
tab_handles.refresh_callback = @() refresh_tab1(app_handles, tab_handles);
tab_handles.cleanup_callback = @() cleanup_tab1(tab_handles);

fprintf('Tab 1 (Model Setup) initialized as placeholder\n');

end

%% Callback Functions

function refresh_tab1(~, ~)
% Refresh tab with latest data
% fprintf('Tab 1: Refreshing...\n');
end

function cleanup_tab1(~)
% Cleanup when tab or app is closed
% fprintf('Tab 1: Cleaning up...\n');
end
