# WARNING: DO NOT EDIT THIS FILE DIRECTLY.
# This file is a child copy that shadows or shares code with the Tools repository.
# Canonical changes must be made in the Tools repository under src/shared/python/
# and synchronized back to UpstreamDrift. Direct edits here risk being lost.

# ARCHITECTURE_DEBT:
# This module historically exceeds standard length metrics and accumulates excessive domain responsibility.
# It requires domain-aware structural extraction to isolate its internal classes appropriately.

"""Collision Geometry Generator.

Advanced mesh simplification specifically optimized for collision detection.
Supports multiple methods:
- VHACD (Volumetric Hierarchical Approximate Convex Decomposition)
- Primitive fitting (box, sphere, cylinder, capsule)
- Mesh decimation with quality metrics
- Hybrid approaches

Example:
    generator = CollisionGeometryGenerator()
    result = generator.generate(
        visual_mesh,
        method="auto",
        target_complexity="balanced",
    )
"""

from __future__ import annotations

import logging
from pathlib import Path
from typing import Any

from ._cg_convex_hull import generate_convex_hull, generate_vhacd, is_roughly_convex
from ._cg_decimation import generate_decimated, generate_hybrid
from ._cg_metrics import (
    compute_hausdorff_distance,
    compute_volume_preservation,
    count_triangles,
)
from ._cg_primitive_fitting import generate_primitives, primitives_would_fit
from ._cg_types import (
    CollisionGeometryResult,
    ComplexityLevel,
    PrimitiveFit,
    SimplificationMethod,
    VHACDParameters,
)

logger = logging.getLogger(__name__)


class CollisionGeometryGenerator:
    COMPLEXITY_PRESETS = {
        ComplexityLevel.MINIMAL: {
            "max_primitives": 4,
            "max_triangles": 100,
            "max_hulls": 4,
        },
        ComplexityLevel.BALANCED: {
            "max_primitives": 16,
            "max_triangles": 500,
            "max_hulls": 16,
        },
        ComplexityLevel.ACCURATE: {
            "max_primitives": 64,
            "max_triangles": 2000,
            "max_hulls": 64,
        },
    }

    def __init__(self) -> None:
        self._trimesh_available = self._check_trimesh()
        self._vhacd_available = self._check_vhacd()

    @staticmethod
    def _check_trimesh() -> bool:
        try:
            import trimesh  # noqa: F401

            return True
        except ImportError:
            logger.warning("trimesh not available - mesh processing limited")
            return False

    @staticmethod
    def _check_vhacd() -> bool:
        try:
            import trimesh

            if hasattr(trimesh.interfaces, "vhacd"):
                return True
        except ImportError:
            pass

        try:
            import pybullet  # noqa: F401

            return True
        except ImportError:
            pass

        logger.warning("VHACD not available - using fallback decomposition")
        return False

    def generate(  # noqa: C901
        self,
        visual_mesh: Any,
        method: str | SimplificationMethod = "auto",
        target_complexity: str | ComplexityLevel = "balanced",
        max_primitives: int | None = None,
        max_triangles: int | None = None,
        max_hulls: int | None = None,
        vhacd_params: VHACDParameters | None = None,
    ) -> CollisionGeometryResult:
        if not (method is not None):
            raise ValueError("method must be provided")
        if isinstance(method, str):
            method = SimplificationMethod[method.upper()]
        if isinstance(target_complexity, str):
            target_complexity = ComplexityLevel[target_complexity.upper()]

        preset = self.COMPLEXITY_PRESETS[target_complexity]
        max_primitives = max_primitives or preset["max_primitives"]
        max_triangles = max_triangles or preset["max_triangles"]
        max_hulls = max_hulls or preset["max_hulls"]

        mesh = self._load_mesh(visual_mesh)
        if mesh is None:
            return CollisionGeometryResult(
                success=False,
                method_used=method,
                components=[],
                original_triangles=0,
                final_triangles=0,
                reduction_ratio=1.0,
                volume_preservation=0.0,
                hausdorff_distance=float("inf"),
                errors=["Failed to load mesh"],
            )

        original_triangles = len(mesh.faces) if hasattr(mesh, "faces") else 0
        original_volume = mesh.volume if hasattr(mesh, "volume") else 0.0

        if method == SimplificationMethod.AUTO:
            method = self._select_best_method(mesh, max_primitives, max_triangles)

        try:
            if method == SimplificationMethod.VHACD:
                result = generate_vhacd(mesh, max_hulls, vhacd_params)
            elif method == SimplificationMethod.PRIMITIVES:
                result = generate_primitives(mesh, max_primitives)
            elif method == SimplificationMethod.DECIMATION:
                result = generate_decimated(mesh, max_triangles)
            elif method == SimplificationMethod.CONVEX_HULL:
                result = generate_convex_hull(mesh)
            elif method == SimplificationMethod.HYBRID:
                result = generate_hybrid(mesh, max_primitives, max_triangles)
            else:
                result = generate_decimated(mesh, max_triangles)

        except (ValueError, TypeError, RuntimeError, OSError) as e:
            logger.error(f"Collision generation failed: {e}")
            return CollisionGeometryResult(
                success=False,
                method_used=method,
                components=[],
                original_triangles=original_triangles,
                final_triangles=0,
                reduction_ratio=1.0,
                volume_preservation=0.0,
                hausdorff_distance=float("inf"),
                errors=[str(e)],
            )

        final_triangles = count_triangles(result.components)
        reduction_ratio = 1.0 - (final_triangles / max(original_triangles, 1))
        volume_preservation = compute_volume_preservation(
            mesh, result.components, original_volume
        )
        hausdorff = compute_hausdorff_distance(mesh, result.components)

        return CollisionGeometryResult(
            success=True,
            method_used=method,
            components=result.components,
            original_triangles=original_triangles,
            final_triangles=final_triangles,
            reduction_ratio=reduction_ratio,
            volume_preservation=volume_preservation,
            hausdorff_distance=hausdorff,
            primitive_fits=result.primitive_fits,
            warnings=result.warnings,
        )

    def _load_mesh(self, mesh_or_path: Any) -> Any:
        if not self._trimesh_available:
            return None

        import trimesh

        if isinstance(mesh_or_path, str | Path):
            try:
                return trimesh.load(str(mesh_or_path))
            except (ValueError, KeyError, TypeError) as e:
                logger.error(f"Failed to load mesh: {e}")
                return None

        return mesh_or_path

    def _select_best_method(
        self,
        mesh: Any,
        max_primitives: int,
        max_triangles: int,
    ) -> SimplificationMethod:
        if not (max_primitives is not None):
            raise ValueError("max_primitives must be provided")
        n_faces = len(mesh.faces) if hasattr(mesh, "faces") else 0

        if n_faces < 100:
            return SimplificationMethod.CONVEX_HULL

        if is_roughly_convex(mesh):
            return SimplificationMethod.CONVEX_HULL

        if primitives_would_fit(mesh, max_primitives):
            return SimplificationMethod.PRIMITIVES

        if self._vhacd_available and n_faces > 500:
            return SimplificationMethod.VHACD

        return SimplificationMethod.DECIMATION


__all__ = [
    "CollisionGeometryGenerator",
    "CollisionGeometryResult",
    "ComplexityLevel",
    "PrimitiveFit",
    "SimplificationMethod",
    "VHACDParameters",
]
