"""Neural motion matching support package (epic #10603).

NM-00 (#10615) owns the fail-closed dataset/checkpoint/training-claim audit.
NM-01 (#10616) freezes learning tasks, the model roster and the benefit
experiment. Later NM children extend this package; do not invent parallel
trainers here.
"""

from __future__ import annotations

from .audit import (
    AUDIT_SCHEMA,
    ArtifactAuditReceipt,
    ParquetInspectResult,
    audit_neural_artifacts,
    inspect_parquet_bounded,
)
from .claims import classify_training_claim
from .coverage import NeuralCoverageCell, generate_neural_coverage_matrix
from .experiment import (
    BASELINE_METHODS,
    EXPERIMENT_SCHEMA,
    LATENCY_PHASES,
    NESTED_EPISODE_STAGES,
    BenefitExperimentReceipt,
    BenefitExperimentSpec,
    BenchmarkCaseKind,
    ComputeBudgetCaps,
    PromotionGates,
    break_even_queries,
    classical_baseline_latency_s,
    default_benefit_experiment,
    freeze_benefit_experiment,
    pilot_training_config,
)
from .roster import (
    NeuralModelRoster,
    NeuralRosterEntry,
    RosterStage,
    build_neural_model_roster,
    resolve_roster_entry,
)
from .tasks import (
    ConditioningSpec,
    ForwardDynamicsTask,
    InverseDynamicsTask,
    InverseLabelPolicy,
    LearningTaskKind,
    MaskedTrajectoryTask,
    TaskDimensions,
    build_default_learning_tasks,
    dimensions_from_model,
    labels_from_canonical_fit,
    provider_engine_name,
    refinement_fit_options,
    training_config_for_task,
)
from .matrix import (
    CHECKPOINT_SCHEMA,
    MATRIX_SCHEMA,
    ModelCheckpointCard,
    ModelCheckpointStatus,
    NativeReplayReceipt,
    NeuralCheckpointMatrix,
    ThreeSeedEvidence,
    assert_model_checkpoint_compatible,
    build_checkpoint_matrix,
)
from .benchmark import (
    AcceptedMatchMetrics,
    BenchmarkMethod,
    BreakEvenReceipt,
    DataEfficiencyCurve,
    LatencySummary,
    ModelBenchmarkCard,
    PromotionDecision,
    PromotionGateResult,
    TimingBreakdown,
    compute_break_even,
    evaluate_data_efficiency,
    evaluate_promotion_gate,
    measure_synchronous_latency,
    run_model_comparative_benchmark,
    synchronize_device,
)
from .types import (
    ArtifactIdentity,
    ArtifactKind,
    ArtifactRole,
    ClaimStatus,
    Disposition,
)

__all__ = [
    "AcceptedMatchMetrics",
    "ArtifactAuditReceipt",
    "ArtifactIdentity",
    "ArtifactKind",
    "ArtifactRole",
    "AUDIT_SCHEMA",
    "BASELINE_METHODS",
    "BenchmarkCaseKind",
    "BenchmarkMethod",
    "BenefitExperimentReceipt",
    "BenefitExperimentSpec",
    "BreakEvenReceipt",
    "CHECKPOINT_SCHEMA",
    "ClaimStatus",
    "ComputeBudgetCaps",
    "ConditioningSpec",
    "DataEfficiencyCurve",
    "Disposition",
    "EXPERIMENT_SCHEMA",
    "ForwardDynamicsTask",
    "InverseDynamicsTask",
    "InverseLabelPolicy",
    "LATENCY_PHASES",
    "LatencySummary",
    "LearningTaskKind",
    "MaskedTrajectoryTask",
    "MATRIX_SCHEMA",
    "ModelBenchmarkCard",
    "ModelCheckpointCard",
    "ModelCheckpointStatus",
    "NativeReplayReceipt",
    "NESTED_EPISODE_STAGES",
    "NeuralCheckpointMatrix",
    "NeuralCoverageCell",
    "NeuralModelRoster",
    "NeuralRosterEntry",
    "ParquetInspectResult",
    "PromotionDecision",
    "PromotionGateResult",
    "PromotionGates",
    "RosterStage",
    "TaskDimensions",
    "ThreeSeedEvidence",
    "TimingBreakdown",
    "assert_model_checkpoint_compatible",
    "audit_neural_artifacts",
    "break_even_queries",
    "build_checkpoint_matrix",
    "build_default_learning_tasks",
    "build_neural_model_roster",
    "classical_baseline_latency_s",
    "classify_training_claim",
    "compute_break_even",
    "default_benefit_experiment",
    "dimensions_from_model",
    "evaluate_data_efficiency",
    "evaluate_promotion_gate",
    "freeze_benefit_experiment",
    "generate_neural_coverage_matrix",
    "inspect_parquet_bounded",
    "labels_from_canonical_fit",
    "measure_synchronous_latency",
    "pilot_training_config",
    "provider_engine_name",
    "refinement_fit_options",
    "resolve_roster_entry",
    "run_model_comparative_benchmark",
    "synchronize_device",
    "training_config_for_task",
]
