# WARNING: DO NOT EDIT THIS FILE DIRECTLY.
# This file is a child copy that shadows or shares code with the Tools repository.
# Canonical changes must be made in the Tools repository under src/shared/python/
# and synchronized back to UpstreamDrift. Direct edits here risk being lost.

"""API standardization modules for calc_backend.

Provides:
- StandardResponse: consistent response wrapper across all endpoints
- ErrorCode and ErrorDetail: standardized error handling
- ResponseMetadata: request tracking and observability
- StandardResponseBuilder: convenient builder for success/error responses
"""

from .standard_response import (
    ErrorCode,
    ErrorDetail,
    ResponseMetadata,
    StandardResponse,
    StandardResponseBuilder,
)

__all__ = [
    "StandardResponse",
    "ErrorCode",
    "ErrorDetail",
    "ResponseMetadata",
    "StandardResponseBuilder",
]
