"""Canonical-core estimation primitives and synthetic-data utilities."""

from __future__ import annotations

from src.shared.python.estimation.drift_anchored_matcher import (
    DriftAnchoredMatchResult,
    MatchOptions,
    SampleLabel,
    WindowRecord,
    match_kinematics,
)
from src.shared.python.estimation.drift_prediction import (
    ControlBand,
    DriftLinearization,
    UncertainPrediction,
    drift_dominance_index,
    integrate_step,
    linearize_drift,
    predict_step,
    reachable_acceleration_interval,
    uncertain_control_prediction,
)
from src.shared.python.estimation.identifiability import (
    IdentifiabilityGateOptions,
    IdentifiabilityGateReport,
    IdentifiabilityReport,
    ParameterSpec,
    UnidentifiableParametersError,
    finite_difference_jacobian as identifiability_finite_difference_jacobian,
    gate_shared_parameters,
    probe_identifiability,
    sweep_parameter,
)
from src.shared.python.estimation.local_torque_window import (
    LocalWindowSolution,
    WindowObservation,
    WindowOptions,
    solve_local_window,
)
from src.shared.python.estimation.map_estimator import (
    NON_FINITE_RESIDUAL_SENTINEL,
    CubicHermiteSplineTrajectory,
    MapEstimatorOptions,
    MapEstimatorProblem,
    MapEstimatorResult,
    NonFiniteResidualError,
    SharedParameterBlock,
    SharedParameterSpec,
    SplineTrajectoryEvaluation,
    solve_single_trial_map,
)
from src.shared.python.estimation.matching_quality import (
    MatchQualityReport,
    QualityThresholds,
    SuspectInterval,
    report_to_dict,
    summarize_match_quality,
)
from src.shared.python.estimation.moving_horizon import (
    MovingHorizonEstimator,
    MovingHorizonOptions,
    MovingHorizonProblem,
    MovingHorizonResult,
)
from src.shared.python.estimation.multi_trial import (
    MultiTrialDecisionLayout,
    MultiTrialMapProblem,
    MultiTrialMapResult,
    MultiTrialObservation,
    shared_parameter_covariance,
    solve_multi_trial_map,
    stack_shared_parameter_jacobians,
)
from src.shared.python.estimation.residuals import (
    ResidualFunction,
    RneaFunction,
    anthropometric_prior_residual,
    autodiff_jacobian,
    dynamics_residual,
    finite_difference_jacobian,
    project_pinhole,
    reprojection_residual,
    reprojection_residual_from_points,
    residual_jacobian,
    smoothness_residual,
)
from src.shared.python.estimation.synthetic_ground_truth import (
    ForwardModel,
    GroundTruthRigResult,
    NoiseModel,
    ObservationPolicy,
    ProjectionRecord,
    SkeletonRigForwardModel,
    SyntheticCamera,
    SyntheticObservationRig,
    project_world_point,
)

__all__ = [
    "ControlBand",
    "CubicHermiteSplineTrajectory",
    "DriftAnchoredMatchResult",
    "DriftLinearization",
    "ForwardModel",
    "GroundTruthRigResult",
    "IdentifiabilityGateOptions",
    "IdentifiabilityGateReport",
    "IdentifiabilityReport",
    "LocalWindowSolution",
    "MapEstimatorOptions",
    "MapEstimatorProblem",
    "MapEstimatorResult",
    "MatchOptions",
    "MatchQualityReport",
    "MovingHorizonEstimator",
    "MovingHorizonOptions",
    "MovingHorizonProblem",
    "MovingHorizonResult",
    "MultiTrialDecisionLayout",
    "MultiTrialMapProblem",
    "MultiTrialMapResult",
    "MultiTrialObservation",
    "NON_FINITE_RESIDUAL_SENTINEL",
    "NoiseModel",
    "NonFiniteResidualError",
    "ObservationPolicy",
    "ParameterSpec",
    "ProjectionRecord",
    "QualityThresholds",
    "ResidualFunction",
    "RneaFunction",
    "SampleLabel",
    "SharedParameterBlock",
    "SharedParameterSpec",
    "SkeletonRigForwardModel",
    "SplineTrajectoryEvaluation",
    "SuspectInterval",
    "SyntheticCamera",
    "SyntheticObservationRig",
    "UncertainPrediction",
    "UnidentifiableParametersError",
    "WindowObservation",
    "WindowOptions",
    "WindowRecord",
    "anthropometric_prior_residual",
    "autodiff_jacobian",
    "drift_dominance_index",
    "dynamics_residual",
    "finite_difference_jacobian",
    "gate_shared_parameters",
    "identifiability_finite_difference_jacobian",
    "integrate_step",
    "linearize_drift",
    "match_kinematics",
    "predict_step",
    "probe_identifiability",
    "project_pinhole",
    "project_world_point",
    "reachable_acceleration_interval",
    "report_to_dict",
    "reprojection_residual",
    "reprojection_residual_from_points",
    "residual_jacobian",
    "shared_parameter_covariance",
    "smoothness_residual",
    "solve_local_window",
    "solve_multi_trial_map",
    "solve_single_trial_map",
    "stack_shared_parameter_jacobians",
    "summarize_match_quality",
    "sweep_parameter",
    "uncertain_control_prediction",
]
