function names = gs3dx_ik_target_names()
%GS3DX_IK_TARGET_NAMES Canonical 14 position target names for GS3DX IK (#10979).
%   NAMES = GS3DX_IK_TARGET_NAMES() returns the authoritative 14x1 cell array of
%   character vectors representing the kinematic position target names in
%   the exact authoritative order used across IK setup and diagnostics.

    names = { ...
        'pelvis'; ...
        'hip_L'; ...
        'hip_R'; ...
        'knee_L'; ...
        'knee_R'; ...
        'ankle_L'; ...
        'ankle_R'; ...
        'shoulder_L'; ...
        'shoulder_R'; ...
        'elbow_L'; ...
        'elbow_R'; ...
        'wrist_L'; ...
        'wrist_R'; ...
        'club_head'};
end
