function gs3dx_bushing_to_6dof(sys)
%GS3DX_BUSHING_TO_6DOF  Swap the hip's Bushing Joint for a 6-DOF Joint.
%
%   GS3DX_BUSHING_TO_6DOF(SYS) edits the loaded hip subsystem SYS (the
%   inline 'Hip Kinetically Driven' of a GS3DX top model) with
%   GS3DX_QUATERNION_SWAP: 'Hip Joint' becomes a 6-DOF Joint whose rotation
%   is one quaternion primitive, so the hip cannot reach gimbal lock
%   (#10956).  Translation (Px, Py, Pz) is unchanged: its settings are
%   copied from the Bushing and its ports keep their converters.  Every
%   Goto and bus signal keeps its meaning.  The caller saves.
%
%   Bushing ports: LConn [B fx fy fz tx ty tz];
%                  RConn [F, (p v a f) x 3, (q w b t) x 3, ft tt].
%   6-DOF ports:   LConn [B fx fy fz t]; RConn [F, (p v a f) x 3, Q w b, ft tt].

    arguments
        sys (1,:) char
    end
    joint = [sys '/Hip Joint'];
    translation = {};
    for name = reshape(fieldnames(get_param(joint, 'DialogParameters')), 1, [])
        if ~isempty(regexp(name{1}, '^P[xyz]', 'once'))
            translation(end+1:end+2) = {name{1}, get_param(joint, name{1})}; %#ok<AGROW>
        end
    end
    spec = struct( ...
        'joint', joint, ...
        'old_lib', 'sm_lib/Joints/Bushing Joint', ...
        'new_lib', 'sm_lib/Joints/6-DOF Joint', ...
        'prefix', 'Sph', ...
        'ports', [7 27], ...
        'new_ports', [5 18], ...
        'keep_left', [(1:4).', (1:4).'], ...
        'keep_right', [(1:13).', (1:13).'; 26 17; 27 18], ...
        'rot_left', [5 6 7], ...
        'rot_right', [14 15 16 17; 18 19 20 21; 22 23 24 25], ...
        'new_torque', 5, ...
        'new_qwb', [14 15 16], ...
        'new_params', {translation});
    gs3dx_quaternion_swap(sys, spec);
end
