function gs3dx_gimbal_to_spherical(mdl)
%GS3DX_GIMBAL_TO_SPHERICAL  Swap a KD subsystem's Gimbal Joint for a Spherical Joint.
%
%   GS3DX_GIMBAL_TO_SPHERICAL(MDL) edits the loaded kinetically driven
%   subsystem MDL (a copy of GS3DX_KDS_Gimbal) with GS3DX_QUATERNION_SWAP so
%   that 'Kinetically Driven' is a quaternion-based Spherical Joint while
%   the subsystem interface (ports, mask, every bus element) stays the same
%   (#10955).  The mask's per-axis target priorities must then agree, since
%   a Spherical Joint has one position and one velocity target; the mask
%   initialization is rewritten to enforce that.  The caller saves.
%
%   Gimbal ports: LConn [B tx ty tz]; RConn [F, (q w b t) x 3, fc tc ft tt].
%   Spherical ports: LConn [B t]; RConn [F Q w b fc tc ft tt].

    arguments
        mdl (1,:) char
    end
    spec = struct( ...
        'joint', [mdl '/Kinetically Driven'], ...
        'old_lib', 'sm_lib/Joints/Gimbal Joint', ...
        'new_lib', 'sm_lib/Joints/Spherical Joint', ...
        'prefix', '', ...
        'ports', [4 17], ...
        'new_ports', [2 8], ...
        'keep_left', [1 1], ...
        'keep_right', [1 1; 14 5; 15 6; 16 7; 17 8], ...
        'rot_left', [2 3 4], ...
        'rot_right', [2 3 4 5; 6 7 8 9; 10 11 12 13], ...
        'new_torque', 2, ...
        'new_qwb', [2 3 4], ...
        'new_params', {{}});
    gs3dx_quaternion_swap(mdl, spec);

    mask = Simulink.Mask.get(mdl);
    mask.Initialization = strjoin({ ...
        '% Spherical joint target binding (#10955): one priority for all axes.', ...
        'sphericalJoint = [gcb ''/Kinetically Driven''];', ...
        'for jointQuantity = {''Position'', ''Velocity''}', ...
        '  jointPriority = cellfun(@(a) get_param(gcb, [a jointQuantity{1} ''TargetPriority'']), ...', ...
        '    {''Rx'', ''Ry'', ''Rz''}, ''UniformOutput'', false);', ...
        '  assert(numel(unique(jointPriority)) == 1, ''Spherical joint needs one %s target priority'', jointQuantity{1});', ...
        '  if strcmp(jointPriority{1}, ''None'')', ...
        '    set_param(sphericalJoint, [jointQuantity{1} ''TargetSpecify''], ''off'');', ...
        '  else', ...
        '    set_param(sphericalJoint, [jointQuantity{1} ''TargetSpecify''], ''on'', ...', ...
        '      [jointQuantity{1} ''TargetPriority''], jointPriority{1});', ...
        '  end', ...
        'end'}, newline);
end
