function [points, info] = gs3dx_capture_marker_overlay(cap, frames)
%GS3DX_CAPTURE_MARKER_OVERLAY All measured channels in the model address frame.
% Invalid C3D samples remain NaN. The shared waist transform establishes the
% origin; raw marker tracks are never interpolated for this overlay.
    arguments
        cap (1,1) struct
        frames (1,:) double
    end
    assert(isfield(cap,'points') && isfield(cap,'labels') && isfield(cap,'missing_mask'), ...
        'gs3dx:marker_overlay','Capture must contain points, labels and residual validity mask');
    assert(isnumeric(cap.points) && isreal(cap.points) && size(cap.points,1)==3 && ...
        size(cap.points,2)==numel(cap.labels) && ...
        isequal(size(cap.missing_mask,1),1) && size(cap.missing_mask,2)==size(cap.points,2) && ...
        size(cap.missing_mask,3)==size(cap.points,3), ...
        'gs3dx:marker_overlay','Capture marker dimensions must agree');
    assert(~isempty(frames) && all(isfinite(frames) & frames>=1 & ...
        frames==fix(frames) & frames<=size(cap.points,3)), ...
        'gs3dx:marker_overlay','Overlay frames must be valid capture indices');
    tf=gs3dx_capture_address_transform(cap);
    raw=cap.points(:,:,frames);
    points=reshape(tf.local(reshape(raw,3,[])),size(raw));
    missing=cap.missing_mask(:,:,frames) | any(~isfinite(raw),1);
    points(repmat(missing,3,1,1))=NaN;
    info=struct('labels',string(cap.labels),'channel_count',numel(cap.labels), ...
        'visible_counts',reshape(sum(~missing,2),1,[]), ...
        'frames',frames,'source','measured_capture_channels','gap_filled',false);
end
