# WARNING: DO NOT EDIT THIS FILE DIRECTLY.
# This file is a child copy that shadows or shares code with the Tools repository.
# Canonical changes must be made in the Tools repository under src/shared/python/
# and synchronized back to UpstreamDrift. Direct edits here risk being lost.

"""Pydantic models for standardized API request/response schemas.

This package provides validated, documented models for all calculator APIs,
ensuring consistent input validation and output format across all endpoints.
"""

from __future__ import annotations

from .pressure_drop import (
    PressureDropRequest,
    PressureDropResponse,
)

__all__ = [
    "PressureDropRequest",
    "PressureDropResponse",
]
