"""Workspace project/session metadata and result browsing APIs."""

from __future__ import annotations

from .artifact_handoff import (
    ArtifactKind,
    ArtifactReference,
    SUPPORTED_FRAMES,
    SUPPORTED_HANDOFF_SCHEMA_VERSIONS,
    SUPPORTED_KINDS,
    SUPPORTED_SCHEMAS,
    VALID_STATUSES,
    WorkspaceHandoff,
    compute_file_sha256,
    convert_artifact,
    register_artifact_adapter,
)
from .capture_inspection_handoff import (
    CaptureInspectionHandoff,
    CropSpec,
    EstimatorType,
    FreeMoCapJobAdapter,
    JobStatus,
    ObservationSet2D,
    OpticalMarkerTarget,
    PreparedVideoInspection,
    TrimSpec,
)
from .model_match_handoff import (
    ClubSpec,
    EngineQualification,
    FitJobRequest,
    FitJobResult,
    FitStage,
    InitialPoseSpec,
    MatchingRoute,
    ModelMatchHandoffCoordinator,
    ModelSpec,
    SubjectSpec,
    get_engine_qualification,
    is_backend_available,
    list_available_backends,
    resolve_matching_route,
)
from .historical_research import (
    ResearchAuditPin,
    build_historical_research_package,
    export_historical_research_package,
    historical_research_schema_bytes,
)
from .necromatcher import NecromatcherLibrary, default_necromatcher_library
from .necromatcher_efforts import AuthoredEffortProfile, EFFORT_SCHEMA
from .necromatcher_native import NativeFitBinding, load_native_fit_binding
from .necromatcher_constraints import repair_native_motion
from .necromatcher_video import export_fit_video
from .necromatcher_video_jobs import NativeVideoSession
from .necromatcher_placement import author_ground_placement
from .necromatcher_replay import ReplayOptions, replay_authored_profile
from .necromatcher_review import CaptureReview
from .necromatcher_shaft_evidence import BoundShaftEvidence, bind_shaft_axis_evidence
from .necromatcher_projection import project_fit_frame
from .necromatcher_projection_process import NativeFitProjectionProcess
from .necromatcher_fit_jobs import NativeRefitOptions, start_native_refit
from .necromatcher_refits import NativeRefitSession, refit_plan
from .project_store import (
    DatasetMetadata,
    ProjectMetadata,
    RunMetadata,
    SessionMetadata,
    SessionProjectStore,
    SubjectMetadata,
)
from .results_browser import ResultArtifact, ResultFilter, ResultsBrowser
from .estimation_workspace import (
    EstimationJobResult,
    EstimationJobStatus,
    EstimationObservationPayload,
    EstimationParameterPrior,
    EstimationRequest,
    EstimationWorkspaceCoordinator,
)
from .comparison_indicator_workspace import (
    BiomechanicalLoadChannels,
    ComparisonIndicatorWorkspaceCoordinator,
    ComparisonRunArtifact,
    ComparisonWorkspaceResult,
    CompatibilityValidationResult,
    CrossEngineComparisonAdapter,
    IncompatibleArtifactError,
    IndicatorWorkspaceResult,
    MissingChannelError,
    ModelFidelityLevel,
    validate_run_compatibility,
)
from .results_workspace import (
    ActionAvailability,
    ComparisonResult,
    HandoffDispatchPayload,
    MissingAssetDiagnosticError,
    ResultArtifactItem,
    ResultCategory,
    ResultsWorkspaceCoordinator,
    UnitMismatchDiagnosticError,
    WorkspaceActionType,
)
from .shot_course_workspace import (
    BunkerFidelityTier,
    BunkerRunRecord,
    IncompatibleGroundFlightRecordError,
    PuttingFixture,
    SceneNonPhysicsError,
    ShotCourseMode,
    ShotCourseRun,
    ShotCourseWorkspaceCoordinator,
    SimulatorDeliveryRequest,
    TerrainConfig,
    TerrainMutationInvalidationError,
    UnsupportedSimulatorDestinationError,
)
from .trajectory_handoff import (
    ExtractionAdapterError,
    FrameUnitMismatchError,
    InvalidTrajectoryHashError,
    ShotTrajectoryHandoffCoordinator,
    UnsupportedEngineSourceError,
)
from .workflow_coordinator import (
    StepProjection,
    StepStatus,
    WorkflowCoordinator,
    WorkflowMode,
    WorkflowProjection,
    WorkflowStepId,
)

from .optimization_training_workspace import (
    DuplicateJobSubmissionError,
    IncompatibleBackendError,
    InvalidOptimizationConfigError,
    ModelCompatibilityError,
    OptimizationJobConfig,
    OptimizationObjective,
    OptimizationResult,
    OptimizationTrainingWorkspaceCoordinator,
    TrainingJobConfig,
    WorkspaceJob,
    WorkspaceJobKind,
    WorkspaceJobState,
)
from .global_utilities import (
    AssistantContextSnapshot,
    CANONICAL_UTILITY_IDS,
    DESKTOP_ONLY_ACTIONS,
    GlobalWorkspaceUtilitiesCoordinator,
    NativeActionUnavailableError,
    OnboardingPreferences,
    PlatformExecutionEnvironment,
    UnknownUtilityError,
    WorkspaceContextualHelp,
)
from .installed_journeys import (
    ComparisonJourneyResult,
    DependencyUnavailableError,
    EstimationComparisonJourneyResult,
    FitJourneyResult,
    InstalledWorkspaceJourneysCoordinator,
    InvalidArtifactSchemaError,
    JourneyExecutionResult,
    JourneyPhase,
    OptimizationJourneyResult,
    RecoveryStatus,
    UtilityNavigationResult,
    UtilityNavigationTarget,
)
from .feature_preservation_audit import (
    AuditCounts,
    AuditFailureError,
    AuditReport,
    AuditSectionResult,
    AuditStatus,
    FeaturePreservationAuditor,
)

from .necromatcher_fit_records import build_native_fit_payload

__all__ = [
    "BoundShaftEvidence",
    "bind_shaft_axis_evidence",
    "build_native_fit_payload",
    "NativeFitBinding",
    "author_ground_placement",
    "repair_native_motion",
    "export_fit_video",
    "NativeVideoSession",
    "ReplayOptions",
    "replay_authored_profile",
    "load_native_fit_binding",
    "AuthoredEffortProfile",
    "EFFORT_SCHEMA",
    "NecromatcherLibrary",
    "CaptureReview",
    "default_necromatcher_library",
    "ActionAvailability",
    "ArtifactKind",
    "ArtifactReference",
    "AssistantContextSnapshot",
    "AuditCounts",
    "AuditFailureError",
    "AuditReport",
    "AuditSectionResult",
    "AuditStatus",
    "BiomechanicalLoadChannels",
    "BunkerFidelityTier",
    "BunkerRunRecord",
    "CANONICAL_UTILITY_IDS",
    "CaptureInspectionHandoff",
    "ClubSpec",
    "ComparisonIndicatorWorkspaceCoordinator",
    "ComparisonJourneyResult",
    "ComparisonResult",
    "ComparisonRunArtifact",
    "ComparisonWorkspaceResult",
    "CompatibilityValidationResult",
    "CropSpec",
    "CrossEngineComparisonAdapter",
    "DESKTOP_ONLY_ACTIONS",
    "DatasetMetadata",
    "DependencyUnavailableError",
    "DuplicateJobSubmissionError",
    "EngineQualification",
    "EstimationJobResult",
    "EstimationJobStatus",
    "EstimationComparisonJourneyResult",
    "EstimationObservationPayload",
    "EstimationParameterPrior",
    "EstimationRequest",
    "EstimationWorkspaceCoordinator",
    "EstimatorType",
    "ExtractionAdapterError",
    "FeaturePreservationAuditor",
    "FitJobRequest",
    "FitJobResult",
    "FitJourneyResult",
    "FitStage",
    "FrameUnitMismatchError",
    "FreeMoCapJobAdapter",
    "GlobalWorkspaceUtilitiesCoordinator",
    "HandoffDispatchPayload",
    "IncompatibleArtifactError",
    "IncompatibleBackendError",
    "IncompatibleGroundFlightRecordError",
    "IndicatorWorkspaceResult",
    "InitialPoseSpec",
    "InstalledWorkspaceJourneysCoordinator",
    "InvalidArtifactSchemaError",
    "InvalidOptimizationConfigError",
    "InvalidTrajectoryHashError",
    "JobStatus",
    "JourneyExecutionResult",
    "JourneyPhase",
    "MatchingRoute",
    "MissingAssetDiagnosticError",
    "MissingChannelError",
    "ModelCompatibilityError",
    "ModelFidelityLevel",
    "ModelMatchHandoffCoordinator",
    "ModelSpec",
    "NativeActionUnavailableError",
    "ObservationSet2D",
    "OnboardingPreferences",
    "OpticalMarkerTarget",
    "OptimizationJobConfig",
    "OptimizationJourneyResult",
    "OptimizationObjective",
    "OptimizationResult",
    "OptimizationTrainingWorkspaceCoordinator",
    "PlatformExecutionEnvironment",
    "PreparedVideoInspection",
    "ProjectMetadata",
    "PuttingFixture",
    "RecoveryStatus",
    "ResultArtifact",
    "ResultArtifactItem",
    "ResultCategory",
    "ResultFilter",
    "ResultsBrowser",
    "ResultsWorkspaceCoordinator",
    "RunMetadata",
    "SUPPORTED_FRAMES",
    "SUPPORTED_HANDOFF_SCHEMA_VERSIONS",
    "SUPPORTED_KINDS",
    "SUPPORTED_SCHEMAS",
    "SceneNonPhysicsError",
    "SessionMetadata",
    "SessionProjectStore",
    "ShotCourseMode",
    "ShotCourseRun",
    "ShotCourseWorkspaceCoordinator",
    "ShotTrajectoryHandoffCoordinator",
    "SimulatorDeliveryRequest",
    "StepProjection",
    "StepStatus",
    "SubjectMetadata",
    "SubjectSpec",
    "TerrainConfig",
    "TerrainMutationInvalidationError",
    "TrainingJobConfig",
    "TrimSpec",
    "UnitMismatchDiagnosticError",
    "UnknownUtilityError",
    "UnsupportedEngineSourceError",
    "UnsupportedSimulatorDestinationError",
    "UtilityNavigationResult",
    "UtilityNavigationTarget",
    "UtilityViewState",
    "VALID_STATUSES",
    "WorkflowCoordinator",
    "WorkflowMode",
    "WorkflowProjection",
    "WorkflowStepId",
    "WorkspaceActionType",
    "WorkspaceContextualHelp",
    "WorkspaceHandoff",
    "WorkspaceJob",
    "WorkspaceJobKind",
    "WorkspaceJobState",
    "ResearchAuditPin",
    "build_historical_research_package",
    "export_historical_research_package",
    "historical_research_schema_bytes",
    "compute_file_sha256",
    "convert_artifact",
    "get_engine_qualification",
    "is_backend_available",
    "list_available_backends",
    "register_artifact_adapter",
    "project_fit_frame",
    "NativeFitProjectionProcess",
    "NativeRefitOptions",
    "NativeRefitSession",
    "refit_plan",
    "resolve_matching_route",
    "start_native_refit",
    "validate_run_compatibility",
]
