cd(matlabdrive);
cd '2DModel/Scripts/_Comparison Scripts';
% PauseTime=1;

SCRIPT_701_QUIVER_Comparison_NetForceEquivalentCouple;
SCRIPT_702_QUIVER_Comparison_NetForce;
SCRIPT_703_QUIVER_Comparison_EquivalentCouple;
SCRIPT_704_PLOT_Comparison_ForceAlongHandPath;
SCRIPT_705_PLOT_Comparison_LinearWork;
SCRIPT_706_PLOT_Comparison_AngularWork;
SCRIPT_707_PLOT_Comparison_TotalWork;
SCRIPT_708_PLOT_Comparison_LinearPower;
SCRIPT_709_PLOT_Comparison_AngularPower;
SCRIPT_710_PLOT_Comparison_TotalPower;
SCRIPT_711_PLOT_Comparison_LinearWorkClubOnly;
SCRIPT_712_PLOT_Comparison_AngularWorkClubOnly;
SCRIPT_713_PLOT_Comparison_TotalWorkClubOnly;
SCRIPT_714_PLOT_Comparison_LinearPowerClubOnly;
SCRIPT_715_PLOT_Comparison_AngularPowerClubOnly;
SCRIPT_716_PLOT_Comparison_TotalPowerClubOnly;
SCRIPT_717_QUIVER_Comparison_LHRHForce;
SCRIPT_718_QUIVER_Comparison_LHRHLinearImpulse;
SCRIPT_719_QUIVER_Comparison_LHRHAngularImpulse;
SCRIPT_720_QUIVER_Comparison_LHRHMomentofForce;
SCRIPT_721_QUIVER_Comparison_TotalMomentofForceEquivalentCouple;
SCRIPT_722_QUIVER_Comparison_LHRHSumofMoments;
SCRIPT_723_QUIVER_Comparison_TotalSumofMoments;
SCRIPT_724_QUIVER_Comparison_TotalLinearImpulse;
SCRIPT_725_QUIVER_Comparison_TotalAngularImpulse;
SCRIPT_726_PLOT_Comparison_ZTCFFractionalWork;
SCRIPT_727_PLOT_Comparison_DELTAFractionalWork;
SCRIPT_728_PLOT_Comparison_ZTCFFractionalPower;
SCRIPT_729_PLOT_Comparison_DeltaFractionalPower;
SCRIPT_730_QUIVER_Comparison_NetForceandCoupleShaftsAdded;
SCRIPT_748_PLOT_Comparison_LocalHandForces;
SCRIPT_749_PLOT_Comparison_LocalHandForcesXOnly;
SCRIPT_750_PLOT_Comparison_LocalHandForcesYOnly;
SCRIPT_751_QUIVER_Comparison_LHRHMOF_BASEvsZTCFvsDELTA;
SCRIPT_752_QUIVER_Comparison_LHRHMOF_DELTAvsZTCF;

% clear PauseTime;


