# WARNING: DO NOT EDIT THIS FILE DIRECTLY.
# This file is a child copy that shadows or shares code with the Tools repository.
# Canonical changes must be made in the Tools repository under src/shared/python/
# and synchronized back to UpstreamDrift. Direct edits here risk being lost.

# ruff: noqa: E501
"""Shared WebSocket router factory for AI chat streaming.

Creates a FastAPI APIRouter with the standard chat WebSocket protocol
that any application can mount. The router delegates to a
``ChatServiceBase`` subclass provided via ``app.state.chat_service``.

Protocol (identical for all consumers):
    Client -> Server:
        {"action": "send", "message": "...", "app_context": "gasification"}
        {"action": "history"}
        {"action": "new_session"}

    Server -> Client:
        {"type": "session_info", "session_id": "..."}
        {"type": "chunk", "content": "..."}
        {"type": "complete", "session_id": "..."}
        {"type": "history", "messages": [...]}
        {"type": "error", "detail": "..."}

Usage::

    from chat.router_factory import create_chat_router

    router = create_chat_router()
    app.include_router(router, prefix="/api")

This module has ZERO application-specific imports.
"""

from __future__ import annotations

import contextlib
import importlib
import importlib.util
import logging
import sys

# ``datetime.UTC`` was added in 3.11; project still supports 3.10.
# Use the compat shim that exposes the same symbol on 3.10.
from src.api.utils.datetime_compat import UTC
from pathlib import Path
from typing import Any

from fastapi import APIRouter, Request, WebSocket, WebSocketDisconnect
from pydantic import ValidationError

from .terminal_contracts import TerminalAgentSessionRequest, TerminalRegistryError
from .terminal_runtime import TerminalRuntimeError

logger = logging.getLogger(__name__)

_INTERNAL_ERROR_DETAIL = "Internal server error"
_CONNECTION_ERROR_DETAIL = "Connection error"

# Load ai.exceptions directly to avoid triggering ai/__init__.py (which may
# contain broken absolute imports in some deployment contexts).  Falls back to
# a never-raised sentinel so the except-tuple is always syntactically valid.
try:
    if "ai.exceptions" not in sys.modules:
        _exc_file = Path(__file__).parent.parent / "ai" / "exceptions.py"
        _spec = importlib.util.spec_from_file_location("ai.exceptions", _exc_file)
        if _spec and _spec.loader:
            _mod = importlib.util.module_from_spec(_spec)
            sys.modules["ai.exceptions"] = _mod
            _spec.loader.exec_module(_mod)
    AIProviderError: type[Exception] = sys.modules["ai.exceptions"].AIProviderError
except Exception:  # noqa: BLE001
    # Graceful degradation: sentinel class that is never instantiated.
    class AIProviderError(Exception):  # type: ignore[no-redef]
        """Sentinel used when ai.exceptions is unavailable."""


def create_chat_router(
    prefix: str = "",
    authorize_fn: Any = None,
) -> APIRouter:
    """Create a chat WebSocket + REST router.

    Args:
        prefix: Optional URL prefix for routes.
        authorize_fn: Optional async callable ``(WebSocket) -> bool``
            that returns False to reject the connection. If None, all
            connections are accepted.

    Returns:
        Configured FastAPI APIRouter.
    """
    router = APIRouter(prefix=prefix)

    @router.websocket("/ws/chat/{session_id}")
    async def chat_stream(  # noqa: C901
        websocket: WebSocket,
        session_id: str = "new",
    ) -> None:
        """Stream AI chat over WebSocket."""
        # Optional authorization hook
        if authorize_fn is not None and not await authorize_fn(websocket):
            return

        await websocket.accept()

        chat_service = websocket.app.state.chat_service

        # Resolve or create session
        if session_id == "new":
            session = chat_service.get_or_create_session(None)
            session_id = session.session_id
        else:
            session = chat_service.get_or_create_session(session_id)
            session_id = session.session_id

        await websocket.send_json({"type": "session_info", "session_id": session_id})

        try:
            while True:
                msg = await websocket.receive_json()
                action = msg.get("action")

                if action == "send":
                    user_message = msg.get("message", "").strip()
                    if not user_message:
                        await websocket.send_json(
                            {"type": "error", "detail": "Empty message"}
                        )
                        continue

                    app_context = msg.get("app_context") or msg.get("engine_context")

                    try:
                        chat_service.add_user_message(
                            session_id, user_message, app_context
                        )
                    except ValueError as e:
                        await websocket.send_json({"type": "error", "detail": str(e)})
                        continue

                    # Stream response chunks
                    try:
                        async for chunk in chat_service.stream_response(session_id):
                            if isinstance(chunk, dict):
                                await websocket.send_json(chunk)
                            else:
                                await websocket.send_json(
                                    {"type": "chunk", "content": str(chunk)}
                                )

                        await websocket.send_json(
                            {"type": "complete", "session_id": session_id}
                        )
                    except Exception:  # noqa: BLE001
                        logger.exception("Error during streaming response")
                        await websocket.send_json(
                            {"type": "error", "detail": _INTERNAL_ERROR_DETAIL}
                        )

                elif action == "history":
                    messages = chat_service.get_session_history(session_id)
                    await websocket.send_json({"type": "history", "messages": messages})

                elif action == "new_session":
                    session = chat_service.get_or_create_session(None)
                    session_id = session.session_id
                    await websocket.send_json(
                        {"type": "session_created", "session_id": session_id}
                    )

                elif action == "terminal_start":
                    await _handle_terminal_start(websocket, msg)

                elif action == "terminal_input":
                    await _handle_terminal_input(websocket, msg)

                elif action == "terminal_resize":
                    await _handle_terminal_resize(websocket, msg)

                elif action == "terminal_stop":
                    await _handle_terminal_stop(websocket, msg)

                elif action == "terminal_events":
                    await _handle_terminal_events(websocket, msg)

                elif action == "condense":
                    try:
                        await chat_service.condense_session(session_id)
                        await websocket.send_json(
                            {
                                "type": "history",
                                "messages": chat_service.get_session_history(
                                    session_id
                                ),
                            }
                        )
                    except (
                        AIProviderError,
                        ValueError,
                        ConnectionError,
                        TimeoutError,
                    ) as exc:
                        logger.warning(
                            "Condense failed for session=%s: %s", session_id, exc
                        )
                        await websocket.send_json({"type": "error", "detail": str(exc)})
                    except Exception:
                        logger.exception(
                            "Unexpected error condensing session=%s", session_id
                        )
                        await websocket.send_json(
                            {"type": "error", "detail": "Internal server error"}
                        )
                        # Do not re-raise inside WS handler since it would close the
                        # connection abruptly, but DO log full traceback so monitoring
                        # sees it.

                elif action == "skill_invoke":
                    skill_id = msg.get("skill_id")
                    if not skill_id:
                        await websocket.send_json(
                            {"type": "error", "detail": "Missing skill_id"}
                        )
                        continue
                    try:
                        await chat_service.execute_skill(session_id, skill_id)
                        await websocket.send_json(
                            {
                                "type": "history",
                                "messages": chat_service.get_session_history(
                                    session_id
                                ),
                            }
                        )
                    except (
                        AIProviderError,
                        ValueError,
                        ConnectionError,
                        TimeoutError,
                    ) as exc:
                        logger.warning(
                            "Skill invoke failed for session=%s skill=%s: %s",
                            session_id,
                            skill_id,
                            exc,
                        )
                        await websocket.send_json({"type": "error", "detail": str(exc)})
                    except Exception:
                        logger.exception(
                            "Unexpected error invoking skill=%s session=%s",
                            skill_id,
                            session_id,
                        )
                        await websocket.send_json(
                            {"type": "error", "detail": "Internal server error"}
                        )
                        # Do not re-raise inside WS handler since it would close the
                        # connection abruptly, but DO log full traceback so monitoring
                        # sees it.

                elif action == "request_review":
                    provider = msg.get("provider")
                    if not provider:
                        await websocket.send_json(
                            {"type": "error", "detail": "Missing provider"}
                        )
                        continue
                    try:
                        new_session_id = await chat_service.request_review(
                            session_id, provider
                        )
                        await websocket.send_json(
                            {
                                "type": "review_started",
                                "new_session_id": new_session_id,
                            }
                        )
                    except (
                        AIProviderError,
                        ValueError,
                        ConnectionError,
                        TimeoutError,
                    ) as exc:
                        logger.warning(
                            "Review request failed for session=%s provider=%s: %s",
                            session_id,
                            provider,
                            exc,
                        )
                        await websocket.send_json({"type": "error", "detail": str(exc)})
                    except Exception:
                        logger.exception(
                            "Unexpected error requesting review session=%s provider=%s",
                            session_id,
                            provider,
                        )
                        await websocket.send_json(
                            {"type": "error", "detail": "Internal server error"}
                        )
                        # Do not re-raise inside WS handler since it would close the
                        # connection abruptly, but DO log full traceback so monitoring
                        # sees it.

                elif action == "refresh_models":
                    try:
                        models = await chat_service.refresh_models()
                        from datetime import datetime

                        await websocket.send_json(
                            {
                                "type": "model_list",
                                "models": models,
                                "refreshed_at": datetime.now(UTC).isoformat(),
                            }
                        )
                    except NotImplementedError as exc:
                        logger.warning("refresh_models not implemented: %s", exc)
                        await websocket.send_json(
                            {
                                "type": "error",
                                "detail": (
                                    "refresh_models not supported by this service"
                                ),
                            }
                        )
                    except (
                        AIProviderError,
                        ValueError,
                        ConnectionError,
                        TimeoutError,
                    ) as exc:
                        logger.warning("Refresh models failed: %s", exc)
                        await websocket.send_json({"type": "error", "detail": str(exc)})
                    except Exception:
                        logger.exception("Unexpected error refreshing models")
                        await websocket.send_json(
                            {"type": "error", "detail": "Internal server error"}
                        )

                elif action == "index_codebase":
                    # Tools issue #2751: the dock widget sends this action
                    # without a root_path (it expects the server to use the
                    # process cwd).  Fall back to os.getcwd() so the action
                    # works out of the box.
                    import os as _os

                    root_path = msg.get("root_path") or _os.getcwd()
                    try:
                        status = await chat_service.index_codebase(root_path)
                        await websocket.send_json({"type": "index_status", **status})
                    except NotImplementedError as exc:
                        logger.warning("index_codebase not implemented: %s", exc)
                        await websocket.send_json(
                            {
                                "type": "error",
                                "detail": (
                                    "index_codebase not supported by this service"
                                ),
                            }
                        )
                    except (
                        AIProviderError,
                        ValueError,
                        ConnectionError,
                        TimeoutError,
                    ) as exc:
                        logger.warning(
                            "Indexing failed for root=%s: %s", root_path, exc
                        )
                        await websocket.send_json({"type": "error", "detail": str(exc)})
                    except Exception:
                        logger.exception("Unexpected error indexing root=%s", root_path)
                        await websocket.send_json(
                            {"type": "error", "detail": "Internal server error"}
                        )

                else:
                    await websocket.send_json(
                        {
                            "type": "error",
                            "detail": f"Unknown action: {action}",
                        }
                    )

        except WebSocketDisconnect:
            logger.debug("Chat WebSocket disconnected")
        except (ConnectionError, TimeoutError, OSError):
            logger.exception("Chat WebSocket connection error")
            with contextlib.suppress(ConnectionError, TimeoutError, OSError):
                await websocket.send_json(
                    {"type": "error", "detail": _CONNECTION_ERROR_DETAIL}
                )

    # ── REST fallback endpoints ──────────────────────────────────────

    @router.get("/chat/sessions")
    async def list_sessions(request: Request) -> list[dict[str, Any]]:
        """List all active chat sessions."""
        return request.app.state.chat_service.list_sessions()  # type: ignore[no-any-return]

    @router.get("/chat/sessions/{session_id}/history")
    async def get_history(request: Request, session_id: str) -> dict[str, Any]:
        """Get message history for a session."""
        if not session_id or not session_id.strip():
            return {"session_id": session_id, "messages": []}
        messages = request.app.state.chat_service.get_session_history(session_id)
        return {"session_id": session_id, "messages": messages}

    return router


def _terminal_runtime(websocket: WebSocket) -> Any:
    runtime = getattr(websocket.app.state, "terminal_runtime", None)
    if runtime is None:
        raise TerminalRuntimeError("Terminal runtime is not configured")
    return runtime


async def _handle_terminal_start(websocket: WebSocket, msg: dict[str, Any]) -> None:
    try:
        request = TerminalAgentSessionRequest(
            app_context=msg.get("app_context") or "unknown",
            project_root=msg.get("project_root", ""),
            shell_id=msg.get("shell_id", ""),
            provider_id=msg.get("provider_id", ""),
            session_id=msg.get("terminal_session_id"),
            provider_args=msg.get("provider_args") or [],
        )
        info = _terminal_runtime(websocket).start(request)
    except (ValidationError, TerminalRegistryError, TerminalRuntimeError) as exc:
        await websocket.send_json({"type": "error", "detail": str(exc)})
        return
    await websocket.send_json(
        {"type": "terminal_session", "session": info.model_dump(mode="json")}
    )


async def _handle_terminal_input(websocket: WebSocket, msg: dict[str, Any]) -> None:
    terminal_session_id = msg.get("terminal_session_id", "")
    text = msg.get("text", "")
    try:
        _terminal_runtime(websocket).write(terminal_session_id, text)
    except TerminalRuntimeError as exc:
        await websocket.send_json({"type": "error", "detail": str(exc)})
        return
    await websocket.send_json({"type": "terminal_ack", "action": "terminal_input"})


async def _handle_terminal_resize(websocket: WebSocket, msg: dict[str, Any]) -> None:
    terminal_session_id = msg.get("terminal_session_id", "")
    try:
        _terminal_runtime(websocket).resize(
            terminal_session_id,
            columns=int(msg.get("columns", 0)),
            rows=int(msg.get("rows", 0)),
        )
    except (TypeError, ValueError, TerminalRuntimeError) as exc:
        await websocket.send_json({"type": "error", "detail": str(exc)})
        return
    await websocket.send_json({"type": "terminal_ack", "action": "terminal_resize"})


async def _handle_terminal_stop(websocket: WebSocket, msg: dict[str, Any]) -> None:
    terminal_session_id = msg.get("terminal_session_id", "")
    try:
        info = _terminal_runtime(websocket).stop(terminal_session_id)
    except TerminalRuntimeError as exc:
        await websocket.send_json({"type": "error", "detail": str(exc)})
        return
    await websocket.send_json(
        {"type": "terminal_session", "session": info.model_dump(mode="json")}
    )


async def _handle_terminal_events(websocket: WebSocket, msg: dict[str, Any]) -> None:
    terminal_session_id = msg.get("terminal_session_id", "")
    try:
        events = _terminal_runtime(websocket).drain_events(terminal_session_id)
    except TerminalRuntimeError as exc:
        await websocket.send_json({"type": "error", "detail": str(exc)})
        return
    await websocket.send_json(
        {
            "type": "terminal_events",
            "events": [event.model_dump(mode="json") for event in events],
        }
    )
