"""Alembic environment configuration for UpstreamDrift database migrations.

This module configures Alembic to run migrations using the project's SQLAlchemy
models (defined in src/api/auth/models.py). Both online (live DB) and offline
(SQL script generation) modes are supported.

Issue #2078: Add database migration tooling.
"""

import os
from logging.config import fileConfig

from alembic import context
from sqlalchemy import engine_from_config, pool

# Import Base from auth models so Alembic can detect schema changes
# when generating autogenerate migrations.
from src.api.auth.models import Base

# The Alembic Config object, which provides access to the values in alembic.ini.
config = context.config

# Override the SQLAlchemy URL from the environment variable if present.
database_url = os.getenv("DATABASE_URL")
if database_url:
    config.set_main_option("sqlalchemy.url", database_url)

# Interpret the config file for Python logging.
# Pass disable_existing_loggers=False so that pytest caplog handlers and other
# loggers already configured by the test runner (or application startup) are
# not silenced when Alembic runs migrations inside the test suite.
if config.config_file_name is not None:
    fileConfig(config.config_file_name, disable_existing_loggers=False)

# Metadata object for autogenerate support (detects new/removed tables and columns).
target_metadata = Base.metadata


def run_migrations_offline() -> None:
    """Run migrations in 'offline' mode.

    In offline mode, the context is configured with just a URL.  Migrations are
    emitted as SQL to stdout (or a --sql file). No actual database connection is
    made, making this useful for generating migration scripts to review or apply
    manually.
    """
    url = config.get_main_option("sqlalchemy.url")
    context.configure(
        url=url,
        target_metadata=target_metadata,
        literal_binds=True,
        dialect_opts={"paramstyle": "named"},
        # Render CHECK constraints in autogenerated migrations
        render_as_batch=True,  # Required for SQLite ALTER TABLE emulation
        compare_type=True,
    )

    with context.begin_transaction():
        context.run_migrations()


def run_migrations_online() -> None:
    """Run migrations in 'online' mode.

    In online mode, an Engine is created and associated with the migration
    context so that migrations run directly against the target database.
    SQLite's StaticPool is used in tests; other databases use the default pool.
    """
    connectable = engine_from_config(
        config.get_section(config.config_ini_section, {}),
        prefix="sqlalchemy.",
        poolclass=pool.NullPool,
    )

    with connectable.connect() as connection:
        context.configure(
            connection=connection,
            target_metadata=target_metadata,
            render_as_batch=True,  # Required for SQLite ALTER TABLE emulation
            compare_type=True,
        )

        with context.begin_transaction():
            context.run_migrations()


if context.is_offline_mode():
    run_migrations_offline()
else:
    run_migrations_online()
