"""Alembic environment configuration for UpstreamDrift database migrations.

This module configures Alembic to run migrations using the project's SQLAlchemy
models (defined in src/api/auth/models.py). Both online (live DB) and offline
(SQL script generation) modes are supported.

Issue #2078: Add database migration tooling.
"""

import os
from logging.config import fileConfig
from typing import Any

from alembic import context
from sqlalchemy import engine_from_config, pool

# The Alembic Config object, which provides access to the values in alembic.ini.
config = context.config

# Override the SQLAlchemy URL from the environment variable if present.
database_url = os.getenv("DATABASE_URL")
if database_url:
    config.set_main_option("sqlalchemy.url", database_url)

# Interpret the config file for Python logging.
# Pass disable_existing_loggers=False so that pytest caplog handlers and other
# loggers already configured by the test runner (or application startup) are
# not silenced when Alembic runs migrations inside the test suite.
if config.config_file_name is not None:
    fileConfig(config.config_file_name, disable_existing_loggers=False)


def _load_target_metadata() -> Any:
    """Import the auth models' metadata, with an actionable error on failure.

    Offline mode (``alembic upgrade --sql``) only emits SQL and does not need
    autogenerate metadata, so we skip the app import chain there — a broken
    auth module no longer blocks offline SQL generation (issue #7168). A failure
    in online mode is wrapped in a ``RuntimeError`` that names the dependency.
    """
    if context.is_offline_mode():
        return None
    try:
        from src.api.auth.models import Base
    except Exception as exc:  # noqa: BLE001 - surface an actionable message
        raise RuntimeError(
            "Alembic could not import src.api.auth.models.Base, which provides "
            "the schema metadata for online migrations. Ensure the application "
            "package is importable (PYTHONPATH/install), or run offline with "
            "`alembic upgrade --sql` which does not require the app import. "
            f"Original error: {type(exc).__name__}: {exc}"
        ) from exc
    return Base.metadata


# Metadata object for autogenerate support (None in offline mode by design).
target_metadata = _load_target_metadata()


def run_migrations_offline() -> None:
    """Run migrations in 'offline' mode.

    In offline mode, the context is configured with just a URL.  Migrations are
    emitted as SQL to stdout (or a --sql file). No actual database connection is
    made, making this useful for generating migration scripts to review or apply
    manually.
    """
    url = config.get_main_option("sqlalchemy.url")
    context.configure(
        url=url,
        target_metadata=target_metadata,
        literal_binds=True,
        dialect_opts={"paramstyle": "named"},
        # Render CHECK constraints in autogenerated migrations
        render_as_batch=True,  # Required for SQLite ALTER TABLE emulation
        compare_type=True,
    )

    with context.begin_transaction():
        context.run_migrations()


def run_migrations_online() -> None:
    """Run migrations in 'online' mode.

    In online mode, an Engine is created and associated with the migration
    context so that migrations run directly against the target database.
    SQLite's StaticPool is used in tests; other databases use the default pool.
    """
    connectable = engine_from_config(
        config.get_section(config.config_ini_section, {}),
        prefix="sqlalchemy.",
        poolclass=pool.NullPool,
    )

    with connectable.connect() as connection:
        context.configure(
            connection=connection,
            target_metadata=target_metadata,
            render_as_batch=True,  # Required for SQLite ALTER TABLE emulation
            compare_type=True,
        )

        with context.begin_transaction():
            context.run_migrations()


if context.is_offline_mode():
    run_migrations_offline()
else:
    run_migrations_online()
