# WARNING: DO NOT EDIT THIS FILE DIRECTLY.
# This file is a child copy that shadows or shares code with the Tools repository.
# Canonical changes must be made in the Tools repository under src/shared/python/
# and synchronized back to UpstreamDrift. Direct edits here risk being lost.

"""Bio/Lab - Biomechanics data readers and laboratory tools.

Modules:
    c3d_reader: C3D motion capture file reader with event and metadata parsing
"""

from .c3d_reader import C3DDataReader, C3DEvent, C3DMetadata

__all__ = [
    "C3DDataReader",
    "C3DEvent",
    "C3DMetadata",
]
