# WARNING: DO NOT EDIT THIS FILE DIRECTLY.
# This file is a child copy that shadows or shares code with the Tools repository.
# Canonical changes must be made in the Tools repository under src/shared/python/
# and synchronized back to UpstreamDrift. Direct edits here risk being lost.

"""Equipment symbol rendering with extensible registry pattern.

Design: Equipment types register themselves via @register_equipment decorator.
New types can be added without modifying the core engine.
"""

from __future__ import annotations  # noqa: E402, F404

import math  # noqa: E402
from collections.abc import Callable  # noqa: E402
from typing import Any  # noqa: E402

from programmatic_pid.geometry import to_float  # noqa: E402

# ---------------------------------------------------------------------------
# Registry
# ---------------------------------------------------------------------------

EquipmentRenderer = Callable  # (msp, x, y, w, h, layer) -> None
EQUIPMENT_RENDERERS: dict[str, EquipmentRenderer] = {}


def register_equipment(type_name: str) -> Callable:
    """Decorator to register an equipment rendering function.

    Usage::

        @register_equipment("my_custom_type")
        def render_my_custom_type(msp, x, y, w, h, layer):
            ...
    """

    def decorator(func: EquipmentRenderer) -> EquipmentRenderer:
        EQUIPMENT_RENDERERS[type_name.lower()] = func
        return func

    return decorator


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------


def equipment_dims(eq: dict[str, Any]) -> tuple[float, float]:
    return (
        to_float(eq.get("w", eq.get("width", 0.0))),
        to_float(eq.get("h", eq.get("height", 0.0))),
    )


def equipment_center(eq: dict[str, Any]) -> tuple[float, float]:
    x = to_float(eq.get("x", 0.0))
    y = to_float(eq.get("y", 0.0))
    w, h = equipment_dims(eq)
    return x + w / 2, y + h / 2


def equipment_side_anchors(eq: dict[str, Any]) -> dict[str, tuple[float, float]]:
    x = to_float(eq.get("x", 0.0))
    y = to_float(eq.get("y", 0.0))
    w, h = equipment_dims(eq)
    return {
        "left": (x, y + h / 2),
        "right": (x + w, y + h / 2),
        "top": (x + w / 2, y + h),
        "bottom": (x + w / 2, y),
    }


def equipment_anchor(
    eq: dict[str, Any], side: str | None, offset: float = 0.0
) -> tuple[float, float]:
    if eq is None:
        raise ValueError("eq must be provided")
    x = to_float(eq.get("x", 0.0))
    y = to_float(eq.get("y", 0.0))
    w, h = equipment_dims(eq)
    side = str(side or "right").lower()
    offset = to_float(offset, 0.0)
    if side == "left":
        return x, y + h / 2 + offset
    if side == "top":
        return x + w / 2 + offset, y + h
    if side == "bottom":
        return x + w / 2 + offset, y
    return x + w, y + h / 2 + offset


def nearest_equipment_anchor(
    eq: dict[str, Any], source: tuple[float, float]
) -> tuple[float, float]:
    if eq is None:
        raise ValueError("eq must be provided")
    sx, sy = to_float(source[0]), to_float(source[1])
    anchors = equipment_side_anchors(eq).values()
    return min(anchors, key=lambda p: (p[0] - sx) ** 2 + (p[1] - sy) ** 2)


# ---------------------------------------------------------------------------
# Built-in equipment symbol renderers
# ---------------------------------------------------------------------------


def _add_box(msp: Any, x: float, y: float, w: float, h: float, layer: str) -> None:
    pts = [(x, y), (x + w, y), (x + w, y + h), (x, y + h)]
    msp.add_lwpolyline(pts, close=True, dxfattribs={"layer": layer})


@register_equipment("box")
@register_equipment("vessel")
@register_equipment("dryer")
@register_equipment("combustor")
@register_equipment("auger")
def render_box(msp: Any, x: float, y: float, w: float, h: float, layer: str) -> None:
    """Default rectangular equipment symbol."""
    _add_box(msp, x, y, w, h, layer)


@register_equipment("hopper")
def render_hopper(msp: Any, x: float, y: float, w: float, h: float, layer: str) -> None:
    if x is None:
        raise ValueError("x must be provided")
    bot_w = w * 0.72
    cx = x + w / 2
    pts = [(x, y + h), (x + w, y + h), (cx + bot_w / 2, y), (cx - bot_w / 2, y)]
    msp.add_lwpolyline(pts, close=True, dxfattribs={"layer": layer})


@register_equipment("fan")
def render_fan(msp: Any, x: float, y: float, w: float, h: float, layer: str) -> None:
    if x is None:
        raise ValueError("x must be provided")
    cx, cy = x + w / 2, y + h / 2
    r = max(min(w, h) * 0.42, 0.5)
    msp.add_circle((cx, cy), radius=r, dxfattribs={"layer": layer})
    blade = [
        (cx - r * 0.25, cy),
        (cx + r * 0.45, cy + r * 0.20),
        (cx + r * 0.45, cy - r * 0.20),
    ]
    msp.add_lwpolyline(blade, close=True, dxfattribs={"layer": layer})


@register_equipment("rotary_valve")
def render_rotary_valve(
    msp: Any, x: float, y: float, w: float, h: float, layer: str
) -> None:
    if x is None:
        raise ValueError("x must be provided")
    cx, cy = x + w / 2, y + h / 2
    r = max(min(w, h) * 0.35, 0.5)
    msp.add_circle((cx, cy), radius=r, dxfattribs={"layer": layer})
    msp.add_line(
        (cx - r * 0.85, cy - r * 0.85),
        (cx + r * 0.85, cy + r * 0.85),
        dxfattribs={"layer": layer},
    )
    msp.add_line(
        (cx - r * 0.85, cy + r * 0.85),
        (cx + r * 0.85, cy - r * 0.85),
        dxfattribs={"layer": layer},
    )


@register_equipment("burner")
def render_burner(msp: Any, x: float, y: float, w: float, h: float, layer: str) -> None:
    if x is None:
        raise ValueError("x must be provided")
    _add_box(msp, x, y, w, h, layer)
    cx = x + w / 2
    flame = [
        (cx, y + h * 0.76),
        (cx + w * 0.10, y + h * 0.48),
        (cx, y + h * 0.22),
        (cx - w * 0.10, y + h * 0.48),
    ]
    msp.add_lwpolyline(flame, close=True, dxfattribs={"layer": layer})


@register_equipment("bin")
def render_bin(msp: Any, x: float, y: float, w: float, h: float, layer: str) -> None:
    if x is None:
        raise ValueError("x must be provided")
    _add_box(msp, x, y, w, h, layer)
    msp.add_line((x, y + h), (x + w, y + h), dxfattribs={"layer": layer})
    msp.add_line(
        (x + w * 0.1, y + h + h * 0.12),
        (x + w * 0.9, y + h + h * 0.12),
        dxfattribs={"layer": layer},
    )


# ---------------------------------------------------------------------------
# Valve symbols (NEW — filling a major gap in the original project)
# ---------------------------------------------------------------------------


@register_equipment("gate_valve")
def render_gate_valve(
    msp: Any, x: float, y: float, w: float, h: float, layer: str
) -> None:
    """ISA-5.1 gate valve: two opposing triangles meeting at a vertical line."""
    if x is None:
        raise ValueError("x must be provided")
    cx, cy = x + w / 2, y + h / 2
    hw, hh = w * 0.4, h * 0.4
    # Left triangle (pointing right)
    msp.add_lwpolyline(
        [(cx - hw, cy + hh), (cx, cy), (cx - hw, cy - hh)],
        close=True,
        dxfattribs={"layer": layer},
    )
    # Right triangle (pointing left)
    msp.add_lwpolyline(
        [(cx + hw, cy + hh), (cx, cy), (cx + hw, cy - hh)],
        close=True,
        dxfattribs={"layer": layer},
    )
    # Stem
    msp.add_line((cx, cy), (cx, cy + hh * 1.3), dxfattribs={"layer": layer})


@register_equipment("globe_valve")
def render_globe_valve(
    msp: Any, x: float, y: float, w: float, h: float, layer: str
) -> None:
    """ISA-5.1 globe valve: like gate valve but with a circle at center."""
    if x is None:
        raise ValueError("x must be provided")
    cx, cy = x + w / 2, y + h / 2
    hw, hh = w * 0.4, h * 0.4
    r = min(hw, hh) * 0.35
    msp.add_lwpolyline(
        [(cx - hw, cy + hh), (cx, cy), (cx - hw, cy - hh)],
        close=True,
        dxfattribs={"layer": layer},
    )
    msp.add_lwpolyline(
        [(cx + hw, cy + hh), (cx, cy), (cx + hw, cy - hh)],
        close=True,
        dxfattribs={"layer": layer},
    )
    msp.add_circle((cx, cy), radius=r, dxfattribs={"layer": layer})
    msp.add_line((cx, cy + r), (cx, cy + hh * 1.3), dxfattribs={"layer": layer})


@register_equipment("ball_valve")
def render_ball_valve(
    msp: Any, x: float, y: float, w: float, h: float, layer: str
) -> None:
    """Ball valve: two triangles with a filled circle."""
    if x is None:
        raise ValueError("x must be provided")
    cx, cy = x + w / 2, y + h / 2
    hw, hh = w * 0.4, h * 0.4
    r = min(hw, hh) * 0.45
    msp.add_lwpolyline(
        [(cx - hw, cy + hh), (cx, cy), (cx - hw, cy - hh)],
        close=True,
        dxfattribs={"layer": layer},
    )
    msp.add_lwpolyline(
        [(cx + hw, cy + hh), (cx, cy), (cx + hw, cy - hh)],
        close=True,
        dxfattribs={"layer": layer},
    )
    msp.add_circle((cx, cy), radius=r, dxfattribs={"layer": layer})


@register_equipment("check_valve")
def render_check_valve(
    msp: Any, x: float, y: float, w: float, h: float, layer: str
) -> None:
    """Check valve: single triangle pointing into a vertical bar."""
    if x is None:
        raise ValueError("x must be provided")
    cx, cy = x + w / 2, y + h / 2
    hw, hh = w * 0.4, h * 0.4
    # Triangle pointing right
    msp.add_lwpolyline(
        [(cx - hw, cy + hh), (cx + hw * 0.3, cy), (cx - hw, cy - hh)],
        close=True,
        dxfattribs={"layer": layer},
    )
    # Vertical bar (stop)
    msp.add_line(
        (cx + hw * 0.3, cy + hh),
        (cx + hw * 0.3, cy - hh),
        dxfattribs={"layer": layer},
    )


@register_equipment("control_valve")
def render_control_valve(
    msp: Any, x: float, y: float, w: float, h: float, layer: str
) -> None:
    """ISA-5.1 control valve: gate valve body with diaphragm actuator."""
    if x is None:
        raise ValueError("x must be provided")
    cx, cy = x + w / 2, y + h / 2
    hw, hh = w * 0.35, h * 0.3
    # Valve body (two triangles)
    msp.add_lwpolyline(
        [(cx - hw, cy + hh), (cx, cy), (cx - hw, cy - hh)],
        close=True,
        dxfattribs={"layer": layer},
    )
    msp.add_lwpolyline(
        [(cx + hw, cy + hh), (cx, cy), (cx + hw, cy - hh)],
        close=True,
        dxfattribs={"layer": layer},
    )
    # Stem
    stem_top = cy + hh * 2.0
    msp.add_line((cx, cy), (cx, stem_top), dxfattribs={"layer": layer})
    # Actuator (circle or half-circle at top)
    act_r = hw * 0.6
    msp.add_circle((cx, stem_top + act_r), radius=act_r, dxfattribs={"layer": layer})


@register_equipment("relief_valve")
@register_equipment("psv")
def render_relief_valve(
    msp: Any, x: float, y: float, w: float, h: float, layer: str
) -> None:
    """Pressure safety / relief valve: triangle with a bent vent line."""
    if x is None:
        raise ValueError("x must be provided")
    cx, cy = x + w / 2, y + h / 2
    hw, hh = w * 0.4, h * 0.35
    # Body triangle (pointing up)
    msp.add_lwpolyline(
        [(cx - hw, cy - hh), (cx, cy + hh), (cx + hw, cy - hh)],
        close=True,
        dxfattribs={"layer": layer},
    )
    # Vent arm (angled exhaust line)
    msp.add_line(
        (cx, cy + hh), (cx + hw * 0.8, cy + hh * 1.8), dxfattribs={"layer": layer}
    )


@register_equipment("rupture_disk")
def render_rupture_disk(
    msp: Any, x: float, y: float, w: float, h: float, layer: str
) -> None:
    """Rupture disk: two arcs forming a lens shape."""
    if x is None:
        raise ValueError("x must be provided")
    cx, cy = x + w / 2, y + h / 2
    r = min(w, h) * 0.4
    # Two vertical lines representing the disk
    msp.add_line((cx, cy - r), (cx, cy + r), dxfattribs={"layer": layer})
    # Curved lines on each side
    msp.add_lwpolyline(
        [(cx - r * 0.3, cy + r), (cx, cy), (cx - r * 0.3, cy - r)],
        dxfattribs={"layer": layer},
    )
    msp.add_lwpolyline(
        [(cx + r * 0.3, cy + r), (cx, cy), (cx + r * 0.3, cy - r)],
        dxfattribs={"layer": layer},
    )


# ---------------------------------------------------------------------------
# Additional process equipment symbols
# ---------------------------------------------------------------------------


@register_equipment("heat_exchanger")
def render_heat_exchanger(
    msp: Any, x: float, y: float, w: float, h: float, layer: str
) -> None:
    """Shell-and-tube heat exchanger: circle with internal lines."""
    if x is None:
        raise ValueError("x must be provided")
    cx, cy = x + w / 2, y + h / 2
    r = min(w, h) * 0.42
    msp.add_circle((cx, cy), radius=r, dxfattribs={"layer": layer})
    # Horizontal tube bundle lines
    for frac in (-0.3, 0.0, 0.3):
        fy = cy + r * frac
        half = math.sqrt(max(r * r - (r * frac) ** 2, 0))
        msp.add_line(
            (cx - half * 0.9, fy), (cx + half * 0.9, fy), dxfattribs={"layer": layer}
        )


@register_equipment("pump")
def render_pump(msp: Any, x: float, y: float, w: float, h: float, layer: str) -> None:
    """Centrifugal pump: circle with discharge nozzle triangle."""
    if x is None:
        raise ValueError("x must be provided")
    cx, cy = x + w / 2, y + h / 2
    r = min(w, h) * 0.38
    msp.add_circle((cx, cy), radius=r, dxfattribs={"layer": layer})
    # Discharge triangle (pointing right)
    msp.add_lwpolyline(
        [(cx + r, cy + r * 0.5), (cx + r + w * 0.2, cy), (cx + r, cy - r * 0.5)],
        close=True,
        dxfattribs={"layer": layer},
    )


@register_equipment("tank")
def render_tank(msp: Any, x: float, y: float, w: float, h: float, layer: str) -> None:
    """Flat-bottom storage tank with roof line."""
    if x is None:
        raise ValueError("x must be provided")
    _add_box(msp, x, y, w, h, layer)
    # Roof line (slight peak)
    msp.add_lwpolyline(
        [(x, y + h), (x + w / 2, y + h + h * 0.08), (x + w, y + h)],
        dxfattribs={"layer": layer},
    )


# ---------------------------------------------------------------------------
# Dispatch
# ---------------------------------------------------------------------------


def draw_equipment_symbol(msp: Any, eq: dict[str, Any], layer: str) -> None:
    """Draw the appropriate symbol for an equipment item.

    Uses the registry first; falls back to vertical_retort special case,
    then to a plain box.
    """
    if eq is None:
        raise ValueError("eq must be provided")
    x = to_float(eq.get("x", 0.0))
    y = to_float(eq.get("y", 0.0))
    w, h = equipment_dims(eq)
    eq_type = str(eq.get("type", "")).lower()
    subtype = str(eq.get("subtype", "")).lower()

    renderer = EQUIPMENT_RENDERERS.get(eq_type) or EQUIPMENT_RENDERERS.get(subtype)
    if renderer is not None:
        renderer(msp, x, y, w, h, layer)
        # Handle vertical_retort zone lines on top of any renderer
        if eq_type == "vertical_retort" or subtype == "vertical_retort":
            for zone in eq.get("zones", []):
                zy = y + h * to_float(zone.get("y_frac", 0.0))
                msp.add_line(
                    (x + 0.6, zy), (x + w - 0.6, zy), dxfattribs={"layer": layer}
                )
        return

    # Default: box with optional vertical_retort zones
    _add_box(msp, x, y, w, h, layer)
    if eq_type == "vertical_retort" or subtype == "vertical_retort":
        for zone in eq.get("zones", []):
            zy = y + h * to_float(zone.get("y_frac", 0.0))
            msp.add_line((x + 0.6, zy), (x + w - 0.6, zy), dxfattribs={"layer": layer})
