"""Shadow Tracker silhouette-to-forward-dynamics package."""

from __future__ import annotations

import importlib
from typing import TYPE_CHECKING, Any

if TYPE_CHECKING:
    from .camera_bridge import (
        from_pipeline_camera,
        to_pipeline_camera,
    )
    from .contracts import (
        CANDIDATE_RESULT_SCHEMA_VERSION,
        CAMERA_TRACK_SCHEMA_VERSION,
        FIT_REQUEST_SCHEMA_VERSION,
        FRAME_OBSERVATION_SCHEMA_VERSION,
        REPLAY_AUDIT_SCHEMA_VERSION,
        RESULT_BUNDLE_SCHEMA_VERSION,
        SHOT_SCHEMA_VERSION,
        SUBJECT_BINDING_SCHEMA_VERSION,
        CANONICAL_ARTICULATED_CONVENTION,
        POINT_LANDMARKS_CONVENTION,
        CameraTrack,
        CandidateResult,
        FitRequest,
        ForwardModel,
        FrameObservation,
        ModelCapabilities,
        RenderRequest,
        RenderResult,
        ReplayAudit,
        ResultBundle,
        RolloutRequest,
        RolloutResult,
        SegmentationRequest,
        SegmentationResult,
        Segmenter,
        ShadowTrackerService,
        Shot,
        SilhouetteRenderer,
        SubjectModelBinding,
    )
    from .articulated_renderer import (
        CANONICAL_ARTICULATED_STATE_FIELDS,
        ArticulatedSilhouetteRenderer,
        state_vector_from_joint_dict,
        state_vector_to_joint_dict,
    )
    from .forward_model import (
        FullBodyForwardModel,
        canonical_to_native_full_body,
        native_to_canonical_full_body,
        rpy_jacobian_body,
        rpy_jacobian_body_inv,
    )
    from .fitting import (
        BaselineComparisonResult,
        ControlFitter,
        FittingOutcome,
        ObjectiveBreakdown,
        OptimizationCheckpoint,
        OptimizationConfig,
        compare_equal_budget_baselines,
    )
    from .evaluation import (
        AblationResult,
        AblationType,
        AmbiguityReport,
        CoverageMetric,
        EvaluationReport,
        GateID,
        GateProfile,
        GateStatus,
        QuantityConfidence,
        ablate_parameter_sensitivity,
        audit_gate_profile,
        classify_evidence_quality,
        compute_empirical_coverage,
        create_evaluated_result_bundle,
        detect_silhouette_ambiguity,
        evaluate_candidate_evidence,
    )
    from .footage_workflows import (
        DeduplicationSplitter,
        DegradationConfig,
        DegradationHarness,
        FilmLineage,
        HistoricalPilotCatalog,
        PilotEntry,
        RightsAuditReport,
        SuitabilityGrade,
        SyncValidationResult,
        audit_asset_rights,
        validate_multiview_synchronization,
        validate_split_isolation,
    )
    from .artifacts import (
        BUNDLE_SCHEMA_VERSION,
        ShadowTrackerBundle,
        load_bundle,
        save_bundle,
    )
    from .service import (
        DefaultShadowTrackerService,
        UnavailableBackendError,
        WorstFrameMetric,
        WorstFrameReport,
    )
    from .engine_matrix import (
        ENGINE_CONFORMANCE_SCHEMA_VERSION,
        RELEASE_QUALIFICATION_SCHEMA_VERSION,
        SCIENTIFIC_REGISTRY_SCHEMA_VERSION,
        EngineCapabilityMatrix,
        EngineQualificationResult,
        EngineQualificationStatus,
        EngineReceipt,
        IndependentReplayAudit,
        PerformanceProfile,
        ReleaseQualificationReport,
        ScientificRegistryEntry,
        audit_engine_conformance,
        audit_full_release_gates,
        generate_release_evidence_inventory,
        get_shadow_tracker_scientific_registry,
        profile_shadow_tracker_performance,
        validate_cross_engine_contact_claims,
        verify_independent_replay,
    )
    from .ingestion import (
        AffineTimingMapping,
        CameraSynchronization,
        DecodeLimits,
        OpenCvVideoDecoder,
        PiecewiseTimingMapping,
        ShotDefinition,
        SourceCatalog,
        SyntheticVideoDecoder,
        VideoDecoderAdapter,
        compute_frame_hash,
        create_shot,
        decode_video_frames,
        detect_telecine_duplicates,
        extract_iso_bmff_pts,
        filter_shot_frames,
        ingest_capture_rig_view,
        ingest_source_asset,
        map_frame_to_observation,
        validate_shot_frames,
    )
    from .initialization import (
        InitialHypothesis,
        InertialParameters,
        MultiviewFitResult,
        SubjectMorphology,
        VisualMorphology,
        estimate_short_window_velocity,
        fit_initial_state_multiview,
        generate_monocular_hypotheses,
    )
    from .mask_records import (
        MaskFrame,
    )
    from .projection import (
        AnalyticSilhouetteRenderer,
        PinholeCameraModel,
        SilhouetteLossResult,
        compute_silhouette_loss,
        project_point_to_pixel,
    )
    from .segmentation import (
        ManualMaskProvider,
        ModelSegmentationProvider,
        OcclusionReport,
        compute_mask_dice,
        compute_mask_iou,
        track_occlusion_and_identity,
    )
    from .source_records import (
        FrameIdentity,
        RightsStatus,
        SourceAsset,
        validate_frame_sequence,
    )

_LAZY_EXPORTS: dict[str, str] = {
    "SourceAsset": ".source_records",
    "FrameIdentity": ".source_records",
    "RightsStatus": ".source_records",
    "validate_frame_sequence": ".source_records",
    "MaskFrame": ".mask_records",
    "to_pipeline_camera": ".camera_bridge",
    "from_pipeline_camera": ".camera_bridge",
    "Shot": ".contracts",
    "FrameObservation": ".contracts",
    "CameraTrack": ".contracts",
    "SubjectModelBinding": ".contracts",
    "FitRequest": ".contracts",
    "ReplayAudit": ".contracts",
    "CandidateResult": ".contracts",
    "ResultBundle": ".contracts",
    "Segmenter": ".contracts",
    "SilhouetteRenderer": ".contracts",
    "ForwardModel": ".contracts",
    "ShadowTrackerService": ".contracts",
    "DefaultShadowTrackerService": ".service",
    "UnavailableBackendError": ".service",
    "WorstFrameReport": ".service",
    "ShadowTrackerBundle": ".artifacts",
    "BUNDLE_SCHEMA_VERSION": ".artifacts",
    "load_bundle": ".artifacts",
    "save_bundle": ".artifacts",
    "SegmentationRequest": ".contracts",
    "SegmentationResult": ".contracts",
    "RenderRequest": ".contracts",
    "RenderResult": ".contracts",
    "ModelCapabilities": ".contracts",
    "RolloutRequest": ".contracts",
    "RolloutResult": ".contracts",
    "SHOT_SCHEMA_VERSION": ".contracts",
    "FRAME_OBSERVATION_SCHEMA_VERSION": ".contracts",
    "CAMERA_TRACK_SCHEMA_VERSION": ".contracts",
    "SUBJECT_BINDING_SCHEMA_VERSION": ".contracts",
    "FIT_REQUEST_SCHEMA_VERSION": ".contracts",
    "REPLAY_AUDIT_SCHEMA_VERSION": ".contracts",
    "CANDIDATE_RESULT_SCHEMA_VERSION": ".contracts",
    "RESULT_BUNDLE_SCHEMA_VERSION": ".contracts",
    "ingest_source_asset": ".ingestion",
    "DecodeLimits": ".ingestion",
    "OpenCvVideoDecoder": ".ingestion",
    "decode_video_frames": ".ingestion",
    "SourceCatalog": ".ingestion",
    "ShotDefinition": ".ingestion",
    "create_shot": ".ingestion",
    "validate_shot_frames": ".ingestion",
    "filter_shot_frames": ".ingestion",
    "detect_telecine_duplicates": ".ingestion",
    "extract_iso_bmff_pts": ".ingestion",
    "AffineTimingMapping": ".ingestion",
    "PiecewiseTimingMapping": ".ingestion",
    "CameraSynchronization": ".ingestion",
    "map_frame_to_observation": ".ingestion",
    "VideoDecoderAdapter": ".ingestion",
    "SyntheticVideoDecoder": ".ingestion",
    "compute_frame_hash": ".ingestion",
    "ingest_capture_rig_view": ".ingestion",
    "compute_mask_iou": ".segmentation",
    "compute_mask_dice": ".segmentation",
    "OcclusionReport": ".segmentation",
    "track_occlusion_and_identity": ".segmentation",
    "ManualMaskProvider": ".segmentation",
    "ModelSegmentationProvider": ".segmentation",
    "PinholeCameraModel": ".projection",
    "project_point_to_pixel": ".projection",
    "AnalyticSilhouetteRenderer": ".projection",
    "SilhouetteLossResult": ".projection",
    "compute_silhouette_loss": ".projection",
    "VisualMorphology": ".initialization",
    "InertialParameters": ".initialization",
    "SubjectMorphology": ".initialization",
    "InitialHypothesis": ".initialization",
    "MultiviewFitResult": ".initialization",
    "estimate_short_window_velocity": ".initialization",
    "generate_monocular_hypotheses": ".initialization",
    "fit_initial_state_multiview": ".initialization",
    "CANONICAL_ARTICULATED_CONVENTION": ".contracts",
    "POINT_LANDMARKS_CONVENTION": ".contracts",
    "ArticulatedSilhouetteRenderer": ".articulated_renderer",
    "CANONICAL_ARTICULATED_STATE_FIELDS": ".articulated_renderer",
    "state_vector_from_joint_dict": ".articulated_renderer",
    "state_vector_to_joint_dict": ".articulated_renderer",
    "FullBodyForwardModel": ".forward_model",
    "canonical_to_native_full_body": ".forward_model",
    "native_to_canonical_full_body": ".forward_model",
    "rpy_jacobian_body": ".forward_model",
    "rpy_jacobian_body_inv": ".forward_model",
    "BaselineComparisonResult": ".fitting",
    "ControlFitter": ".fitting",
    "FittingOutcome": ".fitting",
    "ObjectiveBreakdown": ".fitting",
    "OptimizationCheckpoint": ".fitting",
    "OptimizationConfig": ".fitting",
    "compare_equal_budget_baselines": ".fitting",
    "AblationResult": ".evaluation",
    "AblationType": ".evaluation",
    "AmbiguityReport": ".evaluation",
    "CoverageMetric": ".evaluation",
    "EvaluationReport": ".evaluation",
    "GateID": ".evaluation",
    "GateProfile": ".evaluation",
    "GateStatus": ".evaluation",
    "QuantityConfidence": ".evaluation",
    "ablate_parameter_sensitivity": ".evaluation",
    "audit_gate_profile": ".evaluation",
    "classify_evidence_quality": ".evaluation",
    "compute_empirical_coverage": ".evaluation",
    "create_evaluated_result_bundle": ".evaluation",
    "detect_silhouette_ambiguity": ".evaluation",
    "evaluate_candidate_evidence": ".evaluation",
    "DeduplicationSplitter": ".footage_workflows",
    "DegradationConfig": ".footage_workflows",
    "DegradationHarness": ".footage_workflows",
    "FilmLineage": ".footage_workflows",
    "HistoricalPilotCatalog": ".footage_workflows",
    "PilotEntry": ".footage_workflows",
    "RightsAuditReport": ".footage_workflows",
    "SuitabilityGrade": ".footage_workflows",
    "SyncValidationResult": ".footage_workflows",
    "audit_asset_rights": ".footage_workflows",
    "validate_multiview_synchronization": ".footage_workflows",
    "validate_split_isolation": ".footage_workflows",
    "ENGINE_CONFORMANCE_SCHEMA_VERSION": ".engine_matrix",
    "RELEASE_QUALIFICATION_SCHEMA_VERSION": ".engine_matrix",
    "SCIENTIFIC_REGISTRY_SCHEMA_VERSION": ".engine_matrix",
    "EngineCapabilityMatrix": ".engine_matrix",
    "EngineQualificationResult": ".engine_matrix",
    "EngineQualificationStatus": ".engine_matrix",
    "EngineReceipt": ".engine_matrix",
    "IndependentReplayAudit": ".engine_matrix",
    "PerformanceProfile": ".engine_matrix",
    "ReleaseQualificationReport": ".engine_matrix",
    "ScientificRegistryEntry": ".engine_matrix",
    "audit_engine_conformance": ".engine_matrix",
    "audit_full_release_gates": ".engine_matrix",
    "generate_release_evidence_inventory": ".engine_matrix",
    "get_shadow_tracker_scientific_registry": ".engine_matrix",
    "profile_shadow_tracker_performance": ".engine_matrix",
    "validate_cross_engine_contact_claims": ".engine_matrix",
    "verify_independent_replay": ".engine_matrix",
}

__all__ = [
    "AblationResult",
    "AblationType",
    "AffineTimingMapping",
    "AmbiguityReport",
    "AnalyticSilhouetteRenderer",
    "ArticulatedSilhouetteRenderer",
    "BUNDLE_SCHEMA_VERSION",
    "BaselineComparisonResult",
    "CANDIDATE_RESULT_SCHEMA_VERSION",
    "CAMERA_TRACK_SCHEMA_VERSION",
    "CANONICAL_ARTICULATED_CONVENTION",
    "CANONICAL_ARTICULATED_STATE_FIELDS",
    "CameraSynchronization",
    "CameraTrack",
    "CandidateResult",
    "ControlFitter",
    "CoverageMetric",
    "DecodeLimits",
    "DeduplicationSplitter",
    "DefaultShadowTrackerService",
    "DegradationConfig",
    "DegradationHarness",
    "ENGINE_CONFORMANCE_SCHEMA_VERSION",
    "EngineCapabilityMatrix",
    "EngineQualificationResult",
    "EngineQualificationStatus",
    "EngineReceipt",
    "EvaluationReport",
    "FIT_REQUEST_SCHEMA_VERSION",
    "FRAME_OBSERVATION_SCHEMA_VERSION",
    "FilmLineage",
    "FitRequest",
    "FittingOutcome",
    "ForwardModel",
    "FrameIdentity",
    "FrameObservation",
    "FullBodyForwardModel",
    "GateID",
    "GateProfile",
    "GateStatus",
    "HistoricalPilotCatalog",
    "InitialHypothesis",
    "InertialParameters",
    "IndependentReplayAudit",
    "MaskFrame",
    "ManualMaskProvider",
    "ModelCapabilities",
    "ModelSegmentationProvider",
    "MultiviewFitResult",
    "ObjectiveBreakdown",
    "OcclusionReport",
    "OpenCvVideoDecoder",
    "OptimizationCheckpoint",
    "OptimizationConfig",
    "POINT_LANDMARKS_CONVENTION",
    "PerformanceProfile",
    "PiecewiseTimingMapping",
    "PilotEntry",
    "PinholeCameraModel",
    "QuantityConfidence",
    "RELEASE_QUALIFICATION_SCHEMA_VERSION",
    "ReleaseQualificationReport",
    "RenderRequest",
    "RenderResult",
    "ReplayAudit",
    "RESULT_BUNDLE_SCHEMA_VERSION",
    "REPLAY_AUDIT_SCHEMA_VERSION",
    "ResultBundle",
    "RightsAuditReport",
    "RightsStatus",
    "RolloutRequest",
    "RolloutResult",
    "SCIENTIFIC_REGISTRY_SCHEMA_VERSION",
    "ScientificRegistryEntry",
    "SHOT_SCHEMA_VERSION",
    "SUBJECT_BINDING_SCHEMA_VERSION",
    "SegmentationRequest",
    "SegmentationResult",
    "Segmenter",
    "ShadowTrackerService",
    "ShadowTrackerBundle",
    "Shot",
    "ShotDefinition",
    "SilhouetteLossResult",
    "SilhouetteRenderer",
    "SourceAsset",
    "SourceCatalog",
    "SubjectModelBinding",
    "SubjectMorphology",
    "SuitabilityGrade",
    "SyncValidationResult",
    "SyntheticVideoDecoder",
    "UnavailableBackendError",
    "VideoDecoderAdapter",
    "VisualMorphology",
    "WorstFrameReport",
    "ablate_parameter_sensitivity",
    "audit_asset_rights",
    "audit_engine_conformance",
    "audit_full_release_gates",
    "audit_gate_profile",
    "canonical_to_native_full_body",
    "classify_evidence_quality",
    "compare_equal_budget_baselines",
    "compute_empirical_coverage",
    "compute_frame_hash",
    "compute_mask_dice",
    "compute_mask_iou",
    "compute_silhouette_loss",
    "create_evaluated_result_bundle",
    "create_shot",
    "decode_video_frames",
    "detect_silhouette_ambiguity",
    "detect_telecine_duplicates",
    "estimate_short_window_velocity",
    "evaluate_candidate_evidence",
    "extract_iso_bmff_pts",
    "filter_shot_frames",
    "fit_initial_state_multiview",
    "from_pipeline_camera",
    "generate_monocular_hypotheses",
    "generate_release_evidence_inventory",
    "get_shadow_tracker_scientific_registry",
    "ingest_capture_rig_view",
    "ingest_source_asset",
    "load_bundle",
    "map_frame_to_observation",
    "native_to_canonical_full_body",
    "profile_shadow_tracker_performance",
    "project_point_to_pixel",
    "rpy_jacobian_body",
    "rpy_jacobian_body_inv",
    "save_bundle",
    "state_vector_from_joint_dict",
    "state_vector_to_joint_dict",
    "to_pipeline_camera",
    "track_occlusion_and_identity",
    "validate_cross_engine_contact_claims",
    "validate_frame_sequence",
    "validate_multiview_synchronization",
    "validate_shot_frames",
    "validate_split_isolation",
    "verify_independent_replay",
]


def __getattr__(name: str) -> Any:
    if name in _LAZY_EXPORTS:
        module = importlib.import_module(_LAZY_EXPORTS[name], __package__)
        return getattr(module, name)
    raise AttributeError(f"module {__name__!r} has no attribute {name!r}")


def __dir__() -> list[str]:
    return sorted(list(globals().keys()) + list(_LAZY_EXPORTS.keys()))
