# WARNING: DO NOT EDIT THIS FILE DIRECTLY.
# This file is a child copy that shadows or shares code with the Tools repository.
# Canonical changes must be made in the Tools repository under src/shared/python/
# and synchronized back to UpstreamDrift. Direct edits here risk being lost.

"""Advocate reviewer — emphasises strengths and viability (Tools #2738)."""

from __future__ import annotations

import uuid

from .._llm import ReviewerLLMClient, StubReviewerLLMClient
from ..base import Reviewer
from ..contracts import (
    ReviewerDescriptor,
    ReviewRequest,
    ReviewSubject,
    ReviewVerdict,
)
from ._common import evaluate_to_verdict


class AdvocateReviewer(Reviewer):
    """Reference advocate reviewer.

    Mirrors :class:`CriticReviewer` but with ``role="advocate"`` so the
    LLM prompt can lean toward charitable interpretation.
    """

    def __init__(
        self,
        *,
        llm_client: ReviewerLLMClient,
        agent_id: str | None = None,
        provider: str = "stub",
        model: str = "stub-1",
    ) -> None:
        descriptor = ReviewerDescriptor(
            agent_id=agent_id or f"advocate-{uuid.uuid4().hex[:8]}",
            provider=provider,
            model=model,
            role="advocate",
            expertise_tags=[],
        )
        super().__init__(descriptor=descriptor)
        self._llm = llm_client

    async def review(
        self,
        request: ReviewRequest,
        subject: ReviewSubject,
    ) -> ReviewVerdict:
        return await evaluate_to_verdict(
            llm_client=self._llm,
            descriptor=self.descriptor,
            criteria_set=list(request.criteria_set),
            subject_content=subject.content,
        )


__all__ = ["AdvocateReviewer", "StubReviewerLLMClient"]
