#!/usr/bin/env python3
"""Database migration CLI for UpstreamDrift.

Thin wrapper around the Alembic command-line API that ensures the project's
``src/`` packages are on ``sys.path`` before Alembic runs.  This is the
recommended way to run migrations in the UpstreamDrift project instead of
invoking ``alembic`` directly, because Alembic needs the SQLAlchemy models
(``src.api.auth.models``) to be importable.

Issue #2078: Add database migration tooling.

Usage
-----
    # Apply all pending migrations (upgrade to latest):
    python3 scripts/db_migrate.py upgrade head

    # Show current revision:
    python3 scripts/db_migrate.py current

    # Show migration history:
    python3 scripts/db_migrate.py history

    # Generate a new autogenerated migration after model changes:
    python3 scripts/db_migrate.py revision --autogenerate -m "add foo column"

    # Downgrade one revision:
    python3 scripts/db_migrate.py downgrade -1

    # Verify that models and migrations are in sync (for CI):
    python3 scripts/db_migrate.py check

Notes
-----
- The DATABASE_URL environment variable overrides the SQLite default in
  alembic.ini.  Set it to a PostgreSQL URL for production use.
- Pass ``--help`` to any sub-command for Alembic's own help text.
"""

import argparse
import os
import sys
from pathlib import Path


def _ensure_src_on_path() -> None:
    """Prepend ``src/`` to sys.path so project packages are importable."""
    repo_root = Path(__file__).resolve().parent.parent
    src_path = str(repo_root / "src")
    if src_path not in sys.path:
        sys.path.insert(0, src_path)
    # Also ensure repo root is on path (for ``src.api.*`` absolute imports)
    root_str = str(repo_root)
    if root_str not in sys.path:
        sys.path.insert(0, root_str)


def _get_alembic_config() -> "Config":  # type: ignore[name-defined]  # noqa: F821
    """Build and return an Alembic Config pointed at our alembic.ini."""
    from alembic.config import Config

    repo_root = Path(__file__).resolve().parent.parent
    ini_path = repo_root / "alembic.ini"

    if not ini_path.exists():
        raise FileNotFoundError(
            f"alembic.ini not found at {ini_path}. "
            "Are you running from the repository root?"
        )

    cfg = Config(str(ini_path))

    # Allow DATABASE_URL to override the URL in alembic.ini
    database_url = os.getenv("DATABASE_URL")
    if database_url:
        cfg.set_main_option("sqlalchemy.url", database_url)

    return cfg


def cmd_upgrade(args: argparse.Namespace) -> int:
    """Apply migrations up to *revision* (default: ``head``)."""
    from alembic import command

    cfg = _get_alembic_config()
    command.upgrade(cfg, args.revision)
    return 0


def cmd_downgrade(args: argparse.Namespace) -> int:
    """Revert migrations down to *revision*."""
    from alembic import command

    cfg = _get_alembic_config()
    command.downgrade(cfg, args.revision)
    return 0


def cmd_current(args: argparse.Namespace) -> int:  # noqa: ARG001
    """Show the current database revision."""
    from alembic import command

    cfg = _get_alembic_config()
    command.current(cfg, verbose=True)
    return 0


def cmd_history(args: argparse.Namespace) -> int:  # noqa: ARG001
    """Show the full migration history."""
    from alembic import command

    cfg = _get_alembic_config()
    command.history(cfg, verbose=True)
    return 0


def cmd_revision(args: argparse.Namespace) -> int:
    """Generate a new migration revision file.

    Pass ``--autogenerate`` to detect schema changes from the models
    automatically.
    """
    from alembic import command

    cfg = _get_alembic_config()
    command.revision(
        cfg,
        message=args.message,
        autogenerate=args.autogenerate,
    )
    return 0


def cmd_check(args: argparse.Namespace) -> int:  # noqa: ARG001
    """Verify that the migration scripts match the current SQLAlchemy models.

    This command is intended for use in CI.  It exits with code 1 if there
    are model changes that have not been captured in a migration script.

    Requires Alembic >= 1.9.0 (``alembic check`` sub-command).
    """
    from alembic import command

    try:
        cfg = _get_alembic_config()
        command.check(cfg)
        print("Migration check passed: models and migrations are in sync.")  # noqa: T201
        return 0
    except Exception as exc:  # noqa: BLE001
        print(  # noqa: T201
            f"Migration check FAILED: {exc}\n"
            "Run: python3 scripts/db_migrate.py revision --autogenerate "
            "-m 'describe your change' to generate a new migration."
        )
        return 1


def build_parser() -> argparse.ArgumentParser:
    """Build the argument parser."""
    parser = argparse.ArgumentParser(
        prog="db_migrate",
        description="UpstreamDrift database migration tool (Alembic wrapper).",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog=__doc__,
    )

    sub = parser.add_subparsers(dest="command", required=True)

    # upgrade
    p_up = sub.add_parser("upgrade", help="Apply migrations up to a revision.")
    p_up.add_argument(
        "revision",
        nargs="?",
        default="head",
        help="Target revision (default: head).",
    )
    p_up.set_defaults(func=cmd_upgrade)

    # downgrade
    p_down = sub.add_parser("downgrade", help="Revert migrations to a revision.")
    p_down.add_argument(
        "revision",
        help="Target revision or relative offset, e.g. '-1'.",
    )
    p_down.set_defaults(func=cmd_downgrade)

    # current
    p_cur = sub.add_parser("current", help="Show current database revision.")
    p_cur.set_defaults(func=cmd_current)

    # history
    p_hist = sub.add_parser("history", help="Show migration history.")
    p_hist.set_defaults(func=cmd_history)

    # revision
    p_rev = sub.add_parser("revision", help="Generate a new migration file.")
    p_rev.add_argument("-m", "--message", default=None, help="Migration message.")
    p_rev.add_argument(
        "--autogenerate",
        action="store_true",
        help="Autogenerate from model diff.",
    )
    p_rev.set_defaults(func=cmd_revision)

    # check
    p_chk = sub.add_parser(
        "check",
        help="Check that migrations are in sync with models (for CI).",
    )
    p_chk.set_defaults(func=cmd_check)

    return parser


def main() -> int:
    """Entry point for the migration CLI.

    Returns:
        Process exit code (0 = success).
    """
    _ensure_src_on_path()

    parser = build_parser()
    args = parser.parse_args()
    return args.func(args)


if __name__ == "__main__":
    sys.exit(main())
