"""Generate / validate the monolith refactor register (issue #7131).

The 2026-06-09 A-O audit flagged a large set of oversized source files (>800
LOC) that block the no-monolith standard. Resolution-plan step 1 calls for a
register that lists every such file with its current size, so refactor work has
a single tracked surface. This script is the source of truth for that register:

- ``--check`` (default) verifies ``docs/development/monolith_refactor_register.md``
  lists exactly the set of tracked source files currently over the threshold.
  It fails if a file crosses the threshold without a register entry (a ratchet
  that keeps new monoliths from landing unrecorded) or if a listed file has
  shrunk below the threshold / been removed (so the register cannot rot).
- ``--write`` regenerates the register table from the current tree.

Only tracked ``.py`` and ``.m`` source files under ``src/`` are considered;
tests, vendored code, and generated trees are excluded.
"""

from __future__ import annotations

import argparse
import subprocess
from pathlib import Path

THRESHOLD = 800
SOURCE_SUFFIXES = (".py", ".m")
INCLUDE_ROOT = "src/"
EXCLUDE_SUBSTRINGS = ("/tests/", "/vendor/", "/__pycache__/")

_REPO_ROOT = Path(__file__).resolve().parents[1]
_REGISTER = _REPO_ROOT / "docs" / "development" / "monolith_refactor_register.md"

_TABLE_HEADER = "| LOC | File |\n| ---: | --- |\n"
_BEGIN_MARKER = (
    "<!-- BEGIN monolith-register (generated by scripts/gen_monolith_register.py) -->"
)
_END_MARKER = "<!-- END monolith-register -->"


def _tracked_source_files() -> list[str]:
    result = subprocess.run(  # noqa: S603,S607 - fixed git argv, no shell
        ["git", "ls-files", INCLUDE_ROOT],
        cwd=_REPO_ROOT,
        capture_output=True,
        text=True,
        check=True,
    )
    files = []
    for line in result.stdout.splitlines():
        if not line.endswith(SOURCE_SUFFIXES):
            continue
        normalized = "/" + line
        if any(sub in normalized for sub in EXCLUDE_SUBSTRINGS):
            continue
        files.append(line)
    return files


def _line_count(rel_path: str) -> int:
    path = _REPO_ROOT / rel_path
    with path.open("r", encoding="utf-8", errors="ignore") as handle:
        return sum(1 for _ in handle)


def oversized_files() -> list[tuple[int, str]]:
    """Return ``(loc, path)`` for tracked source files over the threshold.

    Postcondition: sorted by descending LOC then path; every LOC > THRESHOLD.
    """
    rows = [
        (loc, rel)
        for rel in _tracked_source_files()
        if (loc := _line_count(rel)) > THRESHOLD
    ]
    rows.sort(key=lambda row: (-row[0], row[1]))
    return rows


def _render_table(rows: list[tuple[int, str]]) -> str:
    body = "".join(f"| {loc} | `{rel}` |\n" for loc, rel in rows)
    return f"{_BEGIN_MARKER}\n\n{_TABLE_HEADER}{body}\n{_END_MARKER}"


def _listed_files() -> set[str]:
    if not _REGISTER.exists():
        return set()
    text = _REGISTER.read_text(encoding="utf-8")
    listed: set[str] = set()
    for line in text.splitlines():
        line = line.strip()
        if line.startswith("|") and "`" in line:
            start = line.find("`")
            end = line.find("`", start + 1)
            if end > start:
                listed.add(line[start + 1 : end])
    return listed


def check() -> int:
    actual = {rel for _, rel in oversized_files()}
    listed = _listed_files()
    missing = sorted(actual - listed)
    stale = sorted(listed - actual)
    if not missing and not stale:
        print(f"Monolith register is in sync ({len(actual)} files > {THRESHOLD} LOC).")
        return 0
    if missing:
        print("Files over the monolith threshold are missing from the register:")
        for rel in missing:
            print(f"  + {rel}")
    if stale:
        print("Register lists files no longer over the threshold (regenerate):")
        for rel in stale:
            print(f"  - {rel}")
    print(
        "\nRun `python3 scripts/gen_monolith_register.py --write` to update "
        "docs/development/monolith_refactor_register.md."
    )
    return 1


def write() -> int:
    rows = oversized_files()
    table = _render_table(rows)
    intro = (
        "# Monolith refactor register\n\n"
        "Tracking register for the A-O monolith findings (issue #7131). It "
        "lists every tracked `.py`/`.m` source file under `src/` currently over "
        f"**{THRESHOLD} LOC** — the surfaces that block the no-monolith "
        "standard and are prioritized for responsibility-preserving splits.\n\n"
        "The table below is generated and verified by "
        "`scripts/gen_monolith_register.py` (a CI ratchet fails if a new file "
        "crosses the threshold without an entry). Refactor PRs should shrink "
        "entries out of this list one responsibility-preserving extraction at a "
        "time, with characterization tests first.\n\n"
        "Priority order (highest coupling / duplicated logic first): launchers, "
        "engine simulation adapters, and shared motion-pipeline preprocessing.\n\n"
    )
    _REGISTER.parent.mkdir(parents=True, exist_ok=True)
    _REGISTER.write_text(intro + table + "\n", encoding="utf-8")
    print(f"Wrote {_REGISTER} with {len(rows)} entries.")
    return 0


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--write",
        action="store_true",
        help="Regenerate the register instead of checking it.",
    )
    args = parser.parse_args(argv)
    return write() if args.write else check()


if __name__ == "__main__":
    raise SystemExit(main())
