"""Generate the Conda convenience environment from ``pyproject.toml``.

Preconditions:
    The input file exists and contains PEP 621 ``[project]`` metadata.
Postconditions:
    The rendered environment lists the same Python runtime dependencies and
    selected optional dependency groups as ``pyproject.toml``.
"""

from __future__ import annotations

import argparse
from dataclasses import dataclass
from pathlib import Path
from typing import Any

try:
    import tomllib
except ModuleNotFoundError:  # pragma: no cover - Python 3.10 compatibility
    import tomli as tomllib

DEFAULT_EXTRAS = ("dev", "gui-test")
DEFAULT_PYTHON = "3.11"
DEFAULT_CHANNELS = ("conda-forge", "defaults")


@dataclass(frozen=True)
class DependencySpec:
    """Canonical Python dependency declarations loaded from ``pyproject.toml``."""

    runtime: tuple[str, ...]
    extras: dict[str, tuple[str, ...]]


@dataclass(frozen=True)
class EnvironmentSpec:
    """Conda environment representation derived from canonical dependencies."""

    name: str
    python_version: str
    channels: tuple[str, ...]
    pip_dependencies: tuple[str, ...]


def _require_string_list(value: Any, field_name: str) -> tuple[str, ...]:
    if not isinstance(value, list):
        msg = f"{field_name} must be a list of dependency strings"
        raise TypeError(msg)
    if not all(isinstance(item, str) and item.strip() for item in value):
        msg = f"{field_name} must contain only non-empty dependency strings"
        raise TypeError(msg)
    return tuple(value)


def load_dependency_spec(
    pyproject_path: Path,
    *,
    extras: tuple[str, ...] = DEFAULT_EXTRAS,
) -> DependencySpec:
    """Load runtime dependencies and requested extras from a PEP 621 project file."""

    if not pyproject_path.is_file():
        msg = f"pyproject.toml not found: {pyproject_path}"
        raise FileNotFoundError(msg)
    if not all(extra.strip() for extra in extras):
        msg = "extras must contain only non-empty names"
        raise ValueError(msg)

    data = tomllib.loads(pyproject_path.read_text(encoding="utf-8"))
    project = data.get("project")
    if not isinstance(project, dict):
        msg = "pyproject.toml must contain a [project] table"
        raise ValueError(msg)

    runtime = _require_string_list(project.get("dependencies", []), "dependencies")
    optional = project.get("optional-dependencies", {})
    if not isinstance(optional, dict):
        msg = "[project.optional-dependencies] must be a table"
        raise TypeError(msg)

    selected_extras: dict[str, tuple[str, ...]] = {}
    for extra in extras:
        if extra not in optional:
            msg = f"optional dependency extra not found: {extra}"
            raise ValueError(msg)
        selected_extras[extra] = _require_string_list(
            optional[extra],
            f"optional-dependencies.{extra}",
        )

    return DependencySpec(runtime=runtime, extras=selected_extras)


def _dedupe_preserving_order(items: tuple[str, ...]) -> tuple[str, ...]:
    seen: set[str] = set()
    unique: list[str] = []
    for item in items:
        if item in seen:
            continue
        seen.add(item)
        unique.append(item)
    return tuple(unique)


def build_environment(
    spec: DependencySpec,
    *,
    name: str = "upstream-drift",
    python_version: str = DEFAULT_PYTHON,
) -> EnvironmentSpec:
    """Build a deterministic Conda environment from canonical dependencies."""

    if not name.strip():
        msg = "environment name must be non-empty"
        raise ValueError(msg)
    if not python_version.strip():
        msg = "python_version must be non-empty"
        raise ValueError(msg)

    extra_dependencies = tuple(
        dependency
        for dependencies in spec.extras.values()
        for dependency in dependencies
    )
    pip_dependencies = _dedupe_preserving_order(
        spec.runtime + extra_dependencies + ("-e .",)
    )
    return EnvironmentSpec(
        name=name,
        python_version=python_version,
        channels=DEFAULT_CHANNELS,
        pip_dependencies=pip_dependencies,
    )


def render_environment_yml(environment: EnvironmentSpec) -> str:
    """Render a Conda ``environment.yml`` document with provenance headers."""

    lines = [
        "# Generated by scripts/sync_environment_yml.py from pyproject.toml.",
        "# Edit pyproject.toml, then run `make sync-deps`.",
        f"name: {environment.name}",
        "channels:",
    ]
    lines.extend(f"  - {channel}" for channel in environment.channels)
    lines.extend(
        [
            "dependencies:",
            f"  - python={environment.python_version}",
            "  - pip>=23.0",
            "  - pip:",
        ]
    )
    lines.extend(f"      - {dependency}" for dependency in environment.pip_dependencies)
    return "\n".join(lines) + "\n"


def write_environment(
    pyproject_path: Path,
    output_path: Path,
    *,
    extras: tuple[str, ...] = DEFAULT_EXTRAS,
) -> None:
    """Write ``environment.yml`` generated from the canonical project metadata."""

    spec = load_dependency_spec(pyproject_path, extras=extras)
    environment = build_environment(spec)
    output_path.write_text(render_environment_yml(environment), encoding="utf-8")


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Generate environment.yml from pyproject.toml."
    )
    parser.add_argument("--pyproject", type=Path, default=Path("pyproject.toml"))
    parser.add_argument("--output", type=Path, default=Path("environment.yml"))
    parser.add_argument(
        "--extra",
        action="append",
        dest="extras",
        default=None,
        help="Optional dependency group to include. Defaults to dev and gui-test.",
    )
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    extras = tuple(args.extras) if args.extras is not None else DEFAULT_EXTRAS
    write_environment(args.pyproject, args.output, extras=extras)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
