"""GAIL (Generative Adversarial Imitation Learning) algorithm."""

from __future__ import annotations

from pathlib import Path
from typing import TYPE_CHECKING

import numpy as np

if TYPE_CHECKING:
    from numpy.typing import NDArray

from src.learning.imitation._base import ImitationLearner, TrainingConfig
from src.learning.imitation.dataset import DemonstrationDataset

_ADAM_BETA1 = 0.9
_ADAM_BETA2 = 0.999
_ADAM_EPS = 1e-8


def _mlp_forward(
    layers: list[dict[str, NDArray[np.floating]]], x: NDArray[np.floating]
) -> tuple[NDArray[np.floating], list[NDArray[np.floating]]]:
    """Forward pass through a ReLU MLP, retaining per-layer inputs.

    Args:
        layers: Layer dicts with ``W`` and ``b``.
        x: Batched input, shape ``(N, in_dim)``.

    Returns:
        ``(output, activations)`` where ``activations[i]`` is the input fed to
        ``layers[i]``. Postcondition: ``len(activations) == len(layers)``.
    """
    activations: list[NDArray[np.floating]] = []
    for i, layer in enumerate(layers):
        activations.append(x)
        x = x @ layer["W"] + layer["b"]
        if i < len(layers) - 1:
            x = np.maximum(0.0, x)
    return x, activations


def _mlp_backward(
    layers: list[dict[str, NDArray[np.floating]]],
    activations: list[NDArray[np.floating]],
    grad_output: NDArray[np.floating],
) -> tuple[list[dict[str, NDArray[np.floating]]], NDArray[np.floating]]:
    """Backpropagate ``grad_output`` through a ReLU MLP.

    Args:
        layers: Layer dicts with ``W`` and ``b``.
        activations: Per-layer inputs from :func:`_mlp_forward`.
        grad_output: Gradient of the loss w.r.t. the network output.

    Returns:
        ``(grads, grad_input)`` where ``grads[i]`` holds ``dW``/``db`` for
        ``layers[i]`` and ``grad_input`` is the gradient w.r.t. the network
        input (needed to chain the discriminator gradient into the policy).
    """
    grads: list[dict[str, NDArray[np.floating]]] = [
        {"W": np.zeros(0), "b": np.zeros(0)} for _ in layers
    ]
    grad = grad_output
    for i in range(len(layers) - 1, -1, -1):
        a = activations[i]
        grads[i] = {"W": a.T @ grad, "b": grad.sum(axis=0)}
        grad = grad @ layers[i]["W"].T
        if i > 0:
            # ReLU derivative: activations[i] is the post-ReLU output of i-1.
            grad = grad * (a > 0)
    return grads, grad


def _adam_step(
    layers: list[dict[str, NDArray[np.floating]]],
    grads: list[dict[str, NDArray[np.floating]]],
    state: list[dict[str, NDArray[np.floating]]],
    lr: float,
    step: int,
    weight_decay: float = 0.0,
) -> None:
    """Apply one in-place Adam update to ``layers``."""
    bias1 = 1.0 - _ADAM_BETA1**step
    bias2 = 1.0 - _ADAM_BETA2**step
    for layer, grad, moments in zip(layers, grads, state, strict=True):
        for key in ("W", "b"):
            g = grad[key] + weight_decay * layer[key]
            moments[f"m_{key}"] = (
                _ADAM_BETA1 * moments[f"m_{key}"] + (1.0 - _ADAM_BETA1) * g
            )
            moments[f"v_{key}"] = _ADAM_BETA2 * moments[f"v_{key}"] + (
                1.0 - _ADAM_BETA2
            ) * (g * g)
            m_hat = moments[f"m_{key}"] / bias1
            v_hat = moments[f"v_{key}"] / bias2
            layer[key] -= lr * m_hat / (np.sqrt(v_hat) + _ADAM_EPS)


def _init_adam_state(
    layers: list[dict[str, NDArray[np.floating]]],
) -> list[dict[str, NDArray[np.floating]]]:
    """Create zeroed Adam moment buffers matching ``layers``."""
    return [
        {
            "m_W": np.zeros_like(layer["W"]),
            "v_W": np.zeros_like(layer["W"]),
            "m_b": np.zeros_like(layer["b"]),
            "v_b": np.zeros_like(layer["b"]),
        }
        for layer in layers
    ]


class GAIL(ImitationLearner):
    """Generative Adversarial Imitation Learning.

    GAIL uses a discriminator to distinguish between expert and
    policy state-action pairs, and trains the policy to fool it.

    Scope and limitations (issue #7973):
        This implementation performs **real** gradient-based optimisation of
        both networks - the discriminator is trained with binary
        cross-entropy, and the policy is trained by backpropagating the
        discriminator's gradient into the policy's action output.

        It is still a *simplified* GAIL: there is no environment rollout, so
        the states visited by the policy are drawn from the demonstration
        distribution (with exploration noise) rather than generated by
        executing the policy. Full GAIL couples the discriminator reward to
        an on-policy RL algorithm such as PPO. Use
        :class:`~src.learning.imitation.BehaviorCloning` when a direct
        supervised fit to the demonstrations is what you want.
    """

    def __init__(
        self,
        observation_dim: int,
        action_dim: int,
        config: TrainingConfig | None = None,
        device: str = "cpu",
    ) -> None:
        """Initialize GAIL learner."""
        if observation_dim is None:
            raise ValueError("observation_dim must be provided")
        super().__init__(observation_dim, action_dim, config, device)
        self._policy: list[dict[str, NDArray[np.floating]]] = []
        self._discriminator: list[dict[str, NDArray[np.floating]]] = []
        self._build_networks()

    def _build_networks(self) -> None:
        """Build policy and discriminator networks."""
        # Build simple MLP policy
        policy_layers = []
        input_dim = self.observation_dim

        for hidden_dim in self.config.hidden_sizes:
            policy_layers.append(
                {
                    "W": np.random.randn(input_dim, hidden_dim) * 0.01,
                    "b": np.zeros(hidden_dim),
                }
            )
            input_dim = hidden_dim

        policy_layers.append(
            {
                "W": np.random.randn(input_dim, self.action_dim) * 0.01,
                "b": np.zeros(self.action_dim),
            }
        )
        self._policy = policy_layers  # type: ignore[assignment]

        # Build discriminator (state-action -> [0, 1])
        disc_layers = []
        input_dim = self.observation_dim + self.action_dim

        for hidden_dim in self.config.hidden_sizes:
            disc_layers.append(
                {
                    "W": np.random.randn(input_dim, hidden_dim) * 0.01,
                    "b": np.zeros(hidden_dim),
                }
            )
            input_dim = hidden_dim

        disc_layers.append(
            {
                "W": np.random.randn(input_dim, 1) * 0.01,
                "b": np.zeros(1),
            }
        )
        self._discriminator = disc_layers  # type: ignore[assignment]

    def _forward_policy(self, x: NDArray[np.floating]) -> NDArray[np.floating]:
        """Forward pass through policy network."""
        if x is None:
            raise ValueError("x must be provided")
        output, _ = _mlp_forward(self._policy, x)
        return output

    @staticmethod
    def _stable_sigmoid(z: NDArray[np.floating]) -> NDArray[np.floating]:
        """Overflow-safe elementwise logistic sigmoid (issue #7567).

        ``1 / (1 + exp(-z))`` overflows for large negative ``z`` (``exp`` of a
        large positive number). Branching on the sign keeps every ``exp``
        argument <= 0, so the result is finite for any input.
        """
        z = np.asarray(z, dtype=float)
        out = np.empty_like(z)
        pos = z >= 0
        out[pos] = 1.0 / (1.0 + np.exp(-z[pos]))
        exp_z = np.exp(z[~pos])
        out[~pos] = exp_z / (1.0 + exp_z)
        return out

    def _discriminator_logits(
        self, state: NDArray[np.floating], action: NDArray[np.floating]
    ) -> NDArray[np.floating]:
        """Pre-sigmoid discriminator logits for a state-action pair."""
        if state is None:
            raise ValueError("state must be provided")
        x = np.concatenate([state, action], axis=-1)
        logits, _ = _mlp_forward(self._discriminator, x)
        return logits

    def _forward_discriminator(
        self, state: NDArray[np.floating], action: NDArray[np.floating]
    ) -> NDArray[np.floating]:
        """Discriminator output: probability the input is expert, in [0, 1]."""
        return self._stable_sigmoid(self._discriminator_logits(state, action))

    def train(
        self,
        dataset: DemonstrationDataset,
        validation_split: float = 0.1,
    ) -> dict[str, list[float]]:
        """Train GAIL adversarially with real gradient updates (issue #7973).

        Each epoch runs mini-batch updates of:

        1. the **discriminator**, minimising the binary cross-entropy of
           classifying expert pairs as 1 and policy pairs as 0; and
        2. the **policy**, minimising ``softplus(-D_logit(s, pi(s)))`` -
           i.e. the discriminator's gradient is backpropagated through the
           discriminator's action input and into the policy network.

        Both use Adam with ``config.learning_rate`` and ``config.weight_decay``.

        Args:
            dataset: Expert demonstration dataset.
            validation_split: Fraction held out for validation reporting.
                Must be in ``[0, 1)``.

        Returns:
            Training history with ``discriminator_loss``, ``policy_loss`` and
            (when a validation split is held out) ``val_policy_loss``. Both
            losses are the quantities actually minimised, so a converging run
            shows them decreasing.

        Raises:
            ValueError: If ``dataset`` is empty or ``validation_split`` is
                outside ``[0, 1)``.
        """
        if dataset is None:
            raise ValueError("dataset must be provided")
        if not 0.0 <= validation_split < 1.0:
            raise ValueError(
                f"validation_split must be in [0, 1), got {validation_split}"
            )
        expert_states, expert_actions = dataset.to_state_action_pairs()

        if len(expert_states) == 0:
            raise ValueError("Dataset has no state-action pairs")

        expert_states = np.asarray(expert_states, dtype=float)
        expert_actions = np.asarray(expert_actions, dtype=float)

        n_total = len(expert_states)
        n_val = int(n_total * validation_split)
        train_states = expert_states[n_val:] if n_val else expert_states
        train_actions = expert_actions[n_val:] if n_val else expert_actions
        val_states = expert_states[:n_val]
        if len(train_states) == 0:
            raise ValueError("validation_split leaves no training samples")

        history: dict[str, list[float]] = {"discriminator_loss": [], "policy_loss": []}
        if n_val:
            history["val_policy_loss"] = []

        lr = self.config.learning_rate
        weight_decay = self.config.weight_decay
        batch_size = max(1, min(self.config.batch_size, len(train_states)))

        disc_state = _init_adam_state(self._discriminator)
        policy_state = _init_adam_state(self._policy)
        step = 0

        for _epoch in range(self.config.epochs):
            order = np.random.permutation(len(train_states))
            epoch_disc: list[float] = []
            epoch_policy: list[float] = []

            for start in range(0, len(order), batch_size):
                idx = order[start : start + batch_size]
                step += 1
                disc_loss, policy_loss = self._adversarial_step(
                    train_states[idx],
                    train_actions[idx],
                    disc_state,
                    policy_state,
                    lr,
                    weight_decay,
                    step,
                )
                epoch_disc.append(disc_loss)
                epoch_policy.append(policy_loss)

            history["discriminator_loss"].append(float(np.mean(epoch_disc)))
            history["policy_loss"].append(float(np.mean(epoch_policy)))
            if n_val:
                val_logits = self._discriminator_logits(
                    val_states, self._forward_policy(val_states)
                )
                history["val_policy_loss"].append(
                    float(np.mean(np.logaddexp(0.0, -val_logits)))
                )

        self._training_history = history
        return history

    def _adversarial_step(
        self,
        states: NDArray[np.floating],
        actions: NDArray[np.floating],
        disc_state: list[dict[str, NDArray[np.floating]]],
        policy_state: list[dict[str, NDArray[np.floating]]],
        lr: float,
        weight_decay: float,
        step: int,
    ) -> tuple[float, float]:
        """Run one discriminator update and one policy update on a mini-batch.

        Args:
            states: Expert states for this mini-batch, shape ``(N, obs_dim)``.
            actions: Matching expert actions, shape ``(N, action_dim)``.
            disc_state: Adam moments for the discriminator.
            policy_state: Adam moments for the policy.
            lr: Learning rate.
            weight_decay: L2 coefficient.
            step: 1-based global optimiser step (for Adam bias correction).

        Returns:
            ``(discriminator_loss, policy_loss)`` for this mini-batch.
        """
        n = len(states)
        # Exploration noise stands in for the missing environment rollout.
        policy_states = states + np.random.randn(*states.shape) * 0.1

        # --- Discriminator update: expert -> 1, policy -> 0. ---
        policy_actions = self._forward_policy(policy_states)
        expert_in = np.concatenate([states, actions], axis=-1)
        policy_in = np.concatenate([policy_states, policy_actions], axis=-1)

        expert_logits, expert_acts = _mlp_forward(self._discriminator, expert_in)
        policy_logits, policy_acts = _mlp_forward(self._discriminator, policy_in)

        # Stable BCE via softplus (issue #7567).
        disc_loss = float(
            np.mean(np.logaddexp(0.0, -expert_logits))
            + np.mean(np.logaddexp(0.0, policy_logits))
        )

        # d/dz softplus(-z) = sigmoid(z) - 1 ; d/dz softplus(z) = sigmoid(z).
        grad_expert = (self._stable_sigmoid(expert_logits) - 1.0) / n
        grad_policy = self._stable_sigmoid(policy_logits) / n
        disc_grads_e, _ = _mlp_backward(self._discriminator, expert_acts, grad_expert)
        disc_grads_p, _ = _mlp_backward(self._discriminator, policy_acts, grad_policy)
        disc_grads = [
            {"W": ge["W"] + gp["W"], "b": ge["b"] + gp["b"]}
            for ge, gp in zip(disc_grads_e, disc_grads_p, strict=True)
        ]
        _adam_step(self._discriminator, disc_grads, disc_state, lr, step, weight_decay)

        # --- Policy update: make the (updated) discriminator call us expert. ---
        policy_out, policy_net_acts = _mlp_forward(self._policy, policy_states)
        disc_in = np.concatenate([policy_states, policy_out], axis=-1)
        logits, disc_acts = _mlp_forward(self._discriminator, disc_in)
        policy_loss = float(np.mean(np.logaddexp(0.0, -logits)))

        grad_logits = (self._stable_sigmoid(logits) - 1.0) / n
        _, grad_disc_in = _mlp_backward(self._discriminator, disc_acts, grad_logits)
        grad_action = grad_disc_in[:, self.observation_dim :]
        policy_grads, _ = _mlp_backward(self._policy, policy_net_acts, grad_action)
        _adam_step(self._policy, policy_grads, policy_state, lr, step, weight_decay)

        return disc_loss, policy_loss

    def predict(
        self,
        observation: NDArray[np.floating],
        deterministic: bool = True,
    ) -> NDArray[np.floating]:
        """Predict action from observation.

        Args:
            observation: Current observation.
            deterministic: If True, return deterministic action.

        Returns:
            Predicted action.
        """
        if observation is None:
            raise ValueError("observation must be provided")
        if observation.ndim == 1:
            observation = observation.reshape(1, -1)

        action = self._forward_policy(observation)

        if not deterministic:
            action = action + np.random.randn(*action.shape) * 0.1

        if observation.shape[0] == 1:
            action = action.flatten()

        return action

    def get_reward(
        self,
        state: NDArray[np.floating],
        action: NDArray[np.floating],
    ) -> float:
        """Get GAIL reward for state-action pair.

        Args:
            state: Current state.
            action: Taken action.

        Returns:
            GAIL reward value.
        """
        if state is None:
            raise ValueError("state must be provided")
        if state.ndim == 1:
            state = state.reshape(1, -1)
        if action.ndim == 1:
            action = action.reshape(1, -1)

        # Reward = -log(1 - D(s,a)) = softplus(logit), overflow-safe (#7567).
        logits = self._discriminator_logits(state, action)
        return float(np.logaddexp(0.0, logits).item())

    def save(self, path: str | Path) -> None:
        """Save GAIL networks."""
        if path is None:
            raise ValueError("path must be provided")
        path = Path(path)

        save_data = {
            "observation_dim": np.array(self.observation_dim),
            "action_dim": np.array(self.action_dim),
            "num_policy_layers": np.array(len(self._policy)),
            "num_disc_layers": np.array(len(self._discriminator)),
        }

        for i, layer in enumerate(self._policy):
            save_data[f"policy_{i}_W"] = layer["W"]
            save_data[f"policy_{i}_b"] = layer["b"]

        for i, layer in enumerate(self._discriminator):
            save_data[f"disc_{i}_W"] = layer["W"]
            save_data[f"disc_{i}_b"] = layer["b"]

        np.savez(path, **save_data)

    def load(self, path: str | Path) -> None:
        """Load GAIL networks."""
        if path is None:
            raise ValueError("path must be provided")
        path = Path(path)

        # Security: allow_pickle=False prevents arbitrary code execution
        data = np.load(path, allow_pickle=False)

        self.observation_dim = int(data["observation_dim"])
        self.action_dim = int(data["action_dim"])

        if "num_policy_layers" in data:
            num_policy_layers = int(data["num_policy_layers"])
            self._policy = [
                {"W": data[f"policy_{i}_W"], "b": data[f"policy_{i}_b"]}
                for i in range(num_policy_layers)
            ]

            num_disc_layers = int(data["num_disc_layers"])
            self._discriminator = [
                {"W": data[f"disc_{i}_W"], "b": data[f"disc_{i}_b"]}
                for i in range(num_disc_layers)
            ]
        else:
            raise ValueError(
                "Legacy format requiring allow_pickle=True is no longer supported for security reasons."
            )
