"""Vendor-neutral launch-monitor ingestion and analytics.

The package keeps PyQt6 and scikit-learn optional. Importing this façade needs
only the core scientific/data dependencies; the shallow MLP imports
scikit-learn lazily when selected.
"""

from src.shared.python.launch_monitor.comparison import (
    MonitorComparisonResult,
    MonitorSummary,
    PairwiseMonitorComparison,
    compare_monitors,
)
from src.shared.python.launch_monitor.corpus import (
    CORPUS_COLUMN_MAP,
    corpus_dataset_path,
    load_private_corpus,
)
from src.shared.python.launch_monitor.contract_v2 import (
    CONTRACT_VERSION_V2,
    AnalysisContextV2,
    AnalysisLineageV2,
    AvailabilityV2,
    BackingRecordV2,
    ClaimsV2,
    DatasetAuthorityV2,
    LaunchMonitorAnalysisResultV2,
    MetricUnitsV2,
    ModelProvenanceV2,
    PlayerIdentityV2,
    SourceFileReferenceV2,
    TransformRecordV2,
    UncertaintyV2,
    VendorProvenanceV2,
    adapt_v2_to_v1,
    analyze_variables_v2,
    contract_v2_json_schema,
)
from src.shared.python.launch_monitor.dispersion import (
    DispersionResult,
    analyze_dispersion,
)
from src.shared.python.launch_monitor.flexible_analysis import (
    CONTRACT_VERSION,
    AnalysisMode,
    CoefficientEstimate,
    CorrelationMethod,
    CorrelationEstimate,
    DatasetSummary,
    FlexibleAnalysisRequest,
    FlexibleAnalysisResult,
    GroupAnalysis,
    MissingPolicy,
    RegressionEstimate,
    ResidualDiagnostics,
    analyze_variables,
)
from src.shared.python.launch_monitor.importer import import_session
from src.shared.python.launch_monitor.modeling import (
    PredictiveModelResult,
    fit_predictive_model,
)
from src.shared.python.launch_monitor.multivariate import (
    PCAResult,
    VIFResult,
    compute_pca,
    compute_vif,
)
from src.shared.python.launch_monitor.outcome_proxy import analyze_outcome_proxy
from src.shared.python.launch_monitor.profiles import (
    PROFILES,
    ImportProfile,
    ProfileDetection,
    detect_profile,
    normalize_header,
)
from src.shared.python.launch_monitor.project import LaunchMonitorProject
from src.shared.python.launch_monitor.relationships import (
    CorrelationResult,
    DependencyEdge,
    compute_correlations,
)
from src.shared.python.launch_monitor.schema import (
    IDENTITY_COLUMNS,
    METRICS,
    ColumnMapping,
    ImportedSession,
    ImportManifest,
    ImportOptions,
    MetricDefinition,
    numeric_metric_columns,
)
from src.shared.python.launch_monitor.trends import (
    ChangeCandidate,
    TrendResult,
    analyze_trend,
)
from src.shared.python.launch_monitor.strokes_gained import (
    analyze_source_backed_strokes_gained,
    strokes_gained_contract_json_schema,
)
from src.shared.python.launch_monitor.strokes_gained_types import (
    BASELINE_CONTRACT_VERSION,
    OUTCOME_PROXY_CONTRACT_VERSION,
    STROKES_GAINED_CONTRACT_VERSION,
    CourseStateColumnsV1,
    ExpectedStrokesBaselineV2,
    ExpectedStrokesStateV2,
    GroupingDimensionV1,
    LongitudinalDimensionV1,
    OutcomeProxyRequestV1,
    OutcomeProxyResultV1,
    StrokesGainedAnalysisResultV1,
    StrokesGainedRequestV1,
    baseline_table_sha256,
)
from src.shared.python.launch_monitor.treatment import (
    TreatmentConfig,
    TreatmentResult,
    FilterRule,
    apply_treatment,
)

__all__ = [
    "IDENTITY_COLUMNS",
    "METRICS",
    "PROFILES",
    "AnalysisContextV2",
    "AnalysisLineageV2",
    "ChangeCandidate",
    "CONTRACT_VERSION",
    "CONTRACT_VERSION_V2",
    "AnalysisMode",
    "AvailabilityV2",
    "BASELINE_CONTRACT_VERSION",
    "BackingRecordV2",
    "ClaimsV2",
    "CoefficientEstimate",
    "ColumnMapping",
    "CorrelationEstimate",
    "CorrelationMethod",
    "CorrelationResult",
    "CourseStateColumnsV1",
    "DatasetSummary",
    "DatasetAuthorityV2",
    "DependencyEdge",
    "DispersionResult",
    "FlexibleAnalysisRequest",
    "FlexibleAnalysisResult",
    "ExpectedStrokesBaselineV2",
    "ExpectedStrokesStateV2",
    "GroupingDimensionV1",
    "GroupAnalysis",
    "ImportManifest",
    "ImportOptions",
    "ImportProfile",
    "ImportedSession",
    "LaunchMonitorProject",
    "LongitudinalDimensionV1",
    "LaunchMonitorAnalysisResultV2",
    "MetricDefinition",
    "MetricUnitsV2",
    "MonitorComparisonResult",
    "MonitorSummary",
    "ModelProvenanceV2",
    "MissingPolicy",
    "OUTCOME_PROXY_CONTRACT_VERSION",
    "OutcomeProxyRequestV1",
    "OutcomeProxyResultV1",
    "PairwiseMonitorComparison",
    "PredictiveModelResult",
    "PCAResult",
    "ProfileDetection",
    "PlayerIdentityV2",
    "SourceFileReferenceV2",
    "RegressionEstimate",
    "ResidualDiagnostics",
    "STROKES_GAINED_CONTRACT_VERSION",
    "StrokesGainedAnalysisResultV1",
    "StrokesGainedRequestV1",
    "TreatmentConfig",
    "TreatmentResult",
    "TransformRecordV2",
    "FilterRule",
    "TrendResult",
    "VIFResult",
    "UncertaintyV2",
    "VendorProvenanceV2",
    "adapt_v2_to_v1",
    "analyze_outcome_proxy",
    "analyze_source_backed_strokes_gained",
    "analyze_dispersion",
    "analyze_variables",
    "analyze_variables_v2",
    "analyze_trend",
    "apply_treatment",
    "baseline_table_sha256",
    "compare_monitors",
    "CORPUS_COLUMN_MAP",
    "corpus_dataset_path",
    "compute_correlations",
    "compute_pca",
    "compute_vif",
    "contract_v2_json_schema",
    "detect_profile",
    "fit_predictive_model",
    "import_session",
    "load_private_corpus",
    "normalize_header",
    "numeric_metric_columns",
    "strokes_gained_contract_json_schema",
]
