# WARNING: DO NOT EDIT THIS FILE DIRECTLY.
# This file is a child copy that shadows or shares code with the Tools repository.
# Canonical changes must be made in the Tools repository under src/shared/python/
# and synchronized back to UpstreamDrift. Direct edits here risk being lost.

"""Mechanical Calculators - Vessel geometry and structural models."""

from .trc_geometry import TRCGeometryEngine, VesselDimensions, VesselGeometryResult

__all__ = [
    "TRCGeometryEngine",
    "VesselDimensions",
    "VesselGeometryResult",
]
