"""Saved expert video and motion references for camera comparison."""

from .comparison import (
    COMPARISON_EXPORT_SCHEMA,
    COMPARISON_SESSION_SCHEMA,
    ComparisonExportSidecarSpec,
    ComparisonLayer,
    ComparisonSession,
    build_comparison_sidecar,
    comparison_session_path,
    load_comparison_session,
    save_comparison_session,
)
from .evidence import CameraSnapshot, ViewClock
from .scene import session_camera, session_clock
from .model import Asset, ReferenceMotion, ReferenceSource, ReferenceVideo
from .registration import (
    EventAnchors,
    ReferenceRegistration,
    ReferenceTransform,
    TimeMapping,
    canonical_z_up_to_adr0041_world,
    project_reference_to_camera,
    sample_reference_motion,
    transform_reference_motion,
)
from .force_alignment import (
    force_frame_for_video,
    load_trace_forces,
    series_to_viewport_payload_wrench,
    write_trace_forces,
)
from .swing_pairing import (
    PairingConfidence,
    PairingDecisionStatus,
    PairingMatrix,
    PairingOptions,
    SideEvidence,
    SwingPairingFeatures,
    SwingPairingResult,
    build_pairing_matrix,
    compute_inter_capture_envelope_median,
    pair_video_swing,
)

__all__ = [
    "COMPARISON_EXPORT_SCHEMA",
    "COMPARISON_SESSION_SCHEMA",
    "Asset",
    "ComparisonExportSidecarSpec",
    "ComparisonLayer",
    "CameraSnapshot",
    "ViewClock",
    "session_camera",
    "session_clock",
    "ComparisonSession",
    "EventAnchors",
    "ReferenceMotion",
    "ReferenceRegistration",
    "ReferenceSource",
    "ReferenceTransform",
    "ReferenceVideo",
    "TimeMapping",
    "build_comparison_sidecar",
    "build_pairing_matrix",
    "canonical_z_up_to_adr0041_world",
    "comparison_session_path",
    "compute_inter_capture_envelope_median",
    "force_frame_for_video",
    "load_comparison_session",
    "load_trace_forces",
    "PairingConfidence",
    "PairingDecisionStatus",
    "PairingMatrix",
    "PairingOptions",
    "pair_video_swing",
    "project_reference_to_camera",
    "sample_reference_motion",
    "save_comparison_session",
    "series_to_viewport_payload_wrench",
    "SideEvidence",
    "SwingPairingFeatures",
    "SwingPairingResult",
    "transform_reference_motion",
    "write_trace_forces",
]
