# WARNING: DO NOT EDIT THIS FILE DIRECTLY.
# This file is a child copy that shadows or shares code with the Tools repository.
# Canonical changes must be made in the Tools repository under src/shared/python/
# and synchronized back to UpstreamDrift. Direct edits here risk being lost.

"""Compatibility shim for signal_toolkit.

This module delegates to the vendored ud-tools signal_toolkit package
so that ``src.shared.python.signal_toolkit.*`` imports continue to work
after the toolkit was moved to ``vendor/ud-tools``.

By extending ``__path__`` with the vendor directory, Python's normal
submodule resolution will find ``calculus.py``, ``core.py``, etc.
"""

from __future__ import annotations

import sys
from pathlib import Path

# Locate the vendor signal_toolkit directory
# __file__ is: <repo>/src/shared/python/signal_toolkit/__init__.py
# parents[4] is: <repo> root
_REPO_ROOT = Path(__file__).parents[4]
_VENDOR_ST = (
    _REPO_ROOT / "vendor" / "ud-tools" / "src" / "shared" / "python" / "signal_toolkit"
)

if _VENDOR_ST.is_dir():
    _vendor_st_str = str(_VENDOR_ST)
    if _vendor_st_str not in __path__:
        __path__.append(_vendor_st_str)
sys.modules.setdefault("signal_toolkit", sys.modules[__name__])
