%REGEN_CONTROL_NAMES_FIXTURE Regenerate tests/fixtures/control_names_matlab.json.
%
% Run this script from the repo root after any intentional change to the
% canonical control-name registry. It writes the MATLAB-side ordering as
% JSON so the Python test
% tests/unit/motion_matching/test_control_names.py can assert byte-for-byte
% equivalence.

here = fileparts(mfilename('fullpath'));
repoRoot = fullfile(here, '..');
matlabRoot = fullfile(repoRoot, 'src', 'engines', 'Simscape_Multibody_Models', ...
    '3D_Golf_Model', 'matlab', 'motion_matching', 'shared');
addpath(matlabRoot);

map = control_names.get_torque_to_polynomial_base();
keysList = keys(map);
valsList = values(map);
pairs = cell(numel(keysList), 1);
for ii = 1:numel(keysList)
    pairs{ii} = {keysList{ii}, valsList{ii}};
end

fixture = struct( ...
    'x_provenance', 'Generated by tools/regen_control_names_fixture.m', ...
    'torque_to_polynomial_base', {pairs}, ...
    'coefficient_letters', {control_names.get_coefficient_letters()}, ...
    'all_coefficient_names', {control_names.all_coefficient_names()}, ...
    'manifest_sha256', control_names.manifest_sha256() ...
);

outPath = fullfile(repoRoot, 'tests', 'fixtures', 'control_names_matlab.json');
fid = fopen(outPath, 'w');
fprintf(fid, '%s', jsonencode(fixture, 'PrettyPrint', true));
fclose(fid);
fprintf('Wrote %s\n', outPath);
