"""Engine-agnostic model appearance: schema, material library, smooth meshes."""

from src.shared.python.model_appearance.geometry import (
    Mesh,
    ellipsoid_mesh,
    lofted_segment,
)
from src.shared.python.model_appearance.head import (
    HeadAnchor,
    HeadPart,
    build_head_parts,
    head_frame_in_body,
    head_override_rotation,
    place_parts,
    resolve_head_anchor,
)
from src.shared.python.model_appearance.library import (
    CLOTHING,
    MATERIALS,
    classify_body,
    library_materials,
)
from src.shared.python.model_appearance.schema import (
    BALL_SOURCES,
    SCHEMA_VERSION,
    AppearanceDocument,
    BallSettings,
    Environment,
    HeadOrientationOverride,
    HeadSettings,
    Material,
    SegmentRule,
    Texture,
    appearance_path_for,
    document_from_dict,
    document_to_dict,
    load_appearance,
    physics_spec_sha256,
    save_appearance,
    validate_document,
)

__all__ = [
    "BALL_SOURCES",
    "CLOTHING",
    "MATERIALS",
    "SCHEMA_VERSION",
    "AppearanceDocument",
    "BallSettings",
    "Environment",
    "HeadAnchor",
    "HeadOrientationOverride",
    "HeadPart",
    "HeadSettings",
    "Material",
    "Mesh",
    "SegmentRule",
    "Texture",
    "appearance_path_for",
    "build_head_parts",
    "head_frame_in_body",
    "place_parts",
    "classify_body",
    "document_from_dict",
    "document_to_dict",
    "ellipsoid_mesh",
    "head_override_rotation",
    "library_materials",
    "load_appearance",
    "lofted_segment",
    "physics_spec_sha256",
    "resolve_head_anchor",
    "save_appearance",
    "validate_document",
]
